// GENERATED CATEGORY WORDS: Adulting Disasters
const List<String> adulting_disasters_words = [
  'Forgot Rent',
  'Burned Dinner',
  'Called in Sick',
  'Unread Emails',
  'Dead Plant',
  'Overdrawn Account',
  'Impulse Buy',
  'Skipped Gym',
  'Netflix Instead of Study',
  'Lost Charger',
  'Messy Car',
  'Expired Food',
  'Forgot Password',
  'Driving Anxiety',
  'Tax Panic',
  'Coffee Addiction',
  'Alarm Fail',
  'Self Talk',
  'Doom Scroll',
  'Sunday Scaries',
  'Imposter Syndrome',
  'Inbox Zero',
  'Crying in Car',
  'Therapy Homework',
  'Resignation',
  'Plant Rescue',
  'Meal Prep',
  'Quarter Life',
  'Situationship',
  'Unmuted',
  'Dishes Later',
  'Online Shopping',
  'Screen Time',
  'Anxiety Attack',
  'Hating Job',
  'Doctor Avoid',
  'Lost Keys',
  'Food Delivery',
  'Unfiled Tax',
  'Wrong Text',
  'Reply All',
  'Forgot to Eat',
  'Drunk Shopping',
  'People Pleasing',
  'Can’t Adult',
  'Plans Cancelled',
  'Savings Raid',
  'Overdraft',
  'Clothes Still Tagged',
  'Laundry Mountain',
  'Rent Reminder',
  'Broken Dishwasher',
  'Broken Heater',
  'Phone Bill',
  'Car Wash',
  'Utility Cutoff',
  'Parking Ticket',
  'Expired ID',
  'Appointment Missed',
  'Overpacked Bag',
  'Car Trouble',
  'No Hot Water',
  'Flat Tire',
  'New Job',
  'Second Job',
  'Coffee Run',
  'Morning Commute',
  'Lost Ticket',
  'Recipe Fail',
  'Missing Socks',
  'DIY Fail',
  'Cleaning Day',
  'Workout Skip',
  'Laundry Day',
  'Meal Plan',
  'Budget App',
  'Savings App',
  'Budget Spreadsheet',
  'Late Payment',
  'Invoice',
  'Debt',
  'Rent Due',
  'College Loan',
  'Credit Score',
  'Insurance',
  'Gas Bill',
  'Mortgage',
  'Shared Bill',
  'Budget Meal',
  'Weekend Budget',
  'Late Fee',
  'Paycheck',
  'Rent Increase',
  'Library Fine',
  'Unpaid Bill',
  'Job Interview',
  'Pay Stub',
  'Invoice Due',
  'Extra 99',
  'Extra 100',
];