// GENERATED CATEGORY WORDS: Brands & Sneakers
const List<String> brands_sneakers_words = [
  'Air Force 1',
  'Jordan 1',
  'Yeezy',
  'New Balance 550',
  'Dunk Low',
  'Adidas Samba',
  'Vans Old Skool',
  'Converse Chuck Taylor',
  'Reebok Classic',
  'Travis Scott',
  'Supreme Drop',
  'Off-White',
  'Balenciaga',
  'Palace',
  'Stussy',
  'BAPE',
  'Fear of God',
  'Essentials Hoodie',
  'Champion',
  'Carhartt',
  'Stone Island',
  'Corteiz',
  'Gallery Dept',
  'Anti Social Social Club',
  'Kith',
  'Noah',
  'Aime Leon Dore',
  'Human Made',
  'A Bathing Ape',
  'Nike Tech Fleece',
  'Levis 501',
  'Ralph Lauren',
  'Tommy Hilfiger',
  'Lacoste',
  'Burberry Check',
  'Louis Vuitton',
  'Gucci Belt',
  'Dior Oblique',
  'OVO',
  'Sp5der',
  'Hellstar',
  'Eric Emanuel',
  'Madhappy',
  'Broken Planet',
  'Represent',
  'Weekend Offender',
  'Hoka Bondi',
  'On Cloud',
  'Air Max',
  'Jordan 4',
  'Jordan 11',
  'Adidas NMD',
  'Nike SB',
  'Converse One Star',
  'Jordan 3',
  'Nike Cortez',
  'Vans Sk8-Hi',
  'Air Jordan',
  'Supreme Box Logo',
  'Billionaire Boys Club',
  'Nike Dunks',
  'Nike Air',
  'New Balance 990',
  'FILA Disruptor',
  'Adidas Yeezy',
  'Crocs',
  'Birkenstock',
  'Ugg Boots',
  'FILA Mindblower',
  'ASICS Gel',
  'Puma Suede',
  'Reebok Pump',
  'Air Jordan 12',
  'Puma Clyde',
  'Nike VaporMax',
  'Converse Platform',
  'Veja',
  'Kith Hoodie',
  'Saint Laurent',
  'Gosha Rubchinskiy',
  'Comme des Garcons',
  'Heron Preston',
  'Palm Angels',
  'Rhude',
  'Patta',
  'UltraBoost',
  'Jordan 5',
  'Jordan 6',
  'Jordan 13',
  'Air Max 97',
  'Adidas Gazelle',
  'Adidas Stan Smith',
  'Vans Era',
  'Puma RS',
  'New Balance 990v5',
  'Jordan 1 Low',
  'Jordan 1 High',
  'Nike React',
  'Nike Presto',
  'Extra 100',
];