// GENERATED CATEGORY WORDS: Celebrity & Pop Culture Chaos
const List<String> celebrity_pop_culture_chaos_words = [
  'Taylor Swift',
  'Beyonce',
  'Ariana Grande',
  'Drake',
  'Bad Bunny',
  'Doja Cat',
  'Billie Eilish',
  'Olivia Rodrigo',
  'Kanye West',
  'Kendrick Lamar',
  'Rihanna',
  'Harry Styles',
  'Selena Gomez',
  'Zendaya',
  'BTS',
  'BLACKPINK',
  'Justin Bieber',
  'The Weeknd',
  'Kylie Jenner',
  'Kim Kardashian',
  'Shawn Mendes',
  'Lizzo',
  'Cardi B',
  'Megan Thee Stallion',
  'Travis Scott',
  'Ed Sheeran',
  'Adele',
  'Bruno Mars',
  'Dua Lipa',
  'SZA',
  'Paris Hilton',
  'Britney Spears',
  'Madonna',
  'Lady Gaga',
  'Elon Musk',
  'Billboard',
  'Grammy',
  'Oscars',
  'Met Gala',
  'Red Carpet',
  'Coachella',
  'Super Bowl',
  'NBA Finals',
  'World Cup',
  'Pop Culture',
  'Reality TV',
  'Influencer',
  'Memes',
  'Viral Dance',
  'TikTok Trend',
  'Celebrity Couple',
  'Breakup',
  'Scandal',
  'Collab',
  'Tour',
  'Album Release',
  'Fashion Line',
  'Brand Deal',
  'Reality Show',
  'Award Show',
  'Movie Premiere',
  'Social Media',
  'Fan Base',
  'K-Pop Group',
  'Idol Group',
  'Brand Campaign',
  'Podcast',
  'Interview',
  'Movie Trailer',
  'Blockbuster',
  'Comic Con',
  'Superhero Movie',
  'Biopic',
  'Director',
  'Producer',
  'Celebrity Chef',
  'Fashion Icon',
  'Style Moment',
  'Viral Video',
  'Dating Rumor',
  'Fan Art',
  'Trend',
  'Cover Song',
  'Remix',
  'Merch Drop',
  'Red Carpet Dress',
  'Guitar Solo',
  'Dance Crew',
  'Billboard Hot 100',
  'Celeb Gossip',
  'Reality Drama',
  'Fan Account',
  'Photo Leak',
  'Stage Name',
  'Netflix Original',
  'Disney Star',
  'YouTube Channel',
  'Viral Clip',
  'Celebrity Baby',
  'Podcast Guest',
];