// GENERATED CATEGORY WORDS: Cousin Chaos Dares & Confessions
const List<String> cousin_chaos_dares_confessions_words = [
  'Truth or Dare',
  'Confess Crush',
  'Swap Clothes',
  'Dance in Public',
  'Call Ex',
  'Tell a Secret',
  'Do a Dare',
  'Say Something Embarrassing',
  'Eat Something Weird',
  'Sing Loudly',
  'Text Your Crush',
  'Act Like a Celebrity',
  'Confess Fear',
  'Show Your Phone',
  'Do a Cartwheel',
  'Spend \$5 on a Wish',
  'Say I Love You',
  'Do a Dramatic Monologue',
  'Confess a Lie',
  'Impersonate Someone',
  'Reveal Biggest Regret',
  'Do 10 Jumping Jacks',
  'Share a Family Secret',
  'Do a Funny Voice',
  'Attempt a Tongue Twist',
  'Tell a Joke',
  'Confess a Crush',
  'Post an Old Photo',
  'Send a Random Meme',
  'Do an Impression',
  'Do a Dance Move',
  'Confess Biggest Pet Peeve',
  'Show Your Search History',
  'Call Best Friend',
  'Speak in Accent',
  'Give Someone a Compliment',
  'Confess a Bad Habit',
  'Eat a Spoonful of Spice',
  'Share Your Crush',
  'Do a Dramatic Scene',
  'Reveal Your Worst Date',
  'Post a Silly Selfie',
  'Confess a Habit',
  'Sing a Chorus',
  'Act Like a Robot',
  'Reveal Your Guilty Pleasure',
  'Wear Something Ridiculous',
  'Do a Handstand',
  'Text Your School Crush',
  'Share a Childhood Mistake',
  'Do a Sassy Walk',
  'Post a Meme',
  'Reveal a Guilty Pleasure',
  'Perform a Dare',
  'Post a Fake Story',
  'Share Your Most Embarrassing Moment',
  'Do a Karaoke Verse',
  'Post a Late Night Selfie',
  'Do a Dare Call',
  'Confess Your Worst Habit',
  'Reveal Your Weirdest Dream',
  'Send a Random Text',
  'Do a Dare on Camera',
  'Share Your Secret',
  'Show Your Dance',
  'Do an Accent',
  'Confess a Fear',
  'Sing a Disney Song',
  'Swap Shoes',
  'Do a 10-Second Challenge',
  'Confess an Online Habit',
  'Tell a Childhood Secret',
  'Reveal Your Crush',
  'Do a Dare Song',
  'Share a Secret',
  'Show your Dance',
  'Do a Dare with Props',
  'Reveal Your Fake Name',
  'Text a Random Contact',
  'Confess your Weirdest Dream',
  'Tell a Lie',
  'Pass a Note',
  'Act Out a Scene',
  'Share an Embarrassing Text',
  'Extra 85',
  'Extra 86',
  'Extra 87',
  'Extra 88',
  'Extra 89',
  'Extra 90',
  'Extra 91',
  'Extra 92',
  'Extra 93',
  'Extra 94',
  'Extra 95',
  'Extra 96',
  'Extra 97',
  'Extra 98',
  'Extra 99',
  'Extra 100',
];