// GENERATED CATEGORY WORDS: House Chaos
const List<String> house_chaos_words = [
  'Living Room',
  'Kitchen',
  'Bathroom',
  'Bedroom',
  'Laundry',
  'Dishes',
  'Trash Day',
  'Dust Bunnies',
  'Clutter',
  'Floor Stains',
  'Broken Lamp',
  'Creaky Door',
  'Leaky Faucet',
  'Lost Remote',
  'Mismatched Socks',
  'Vacuum',
  'Washing Machine',
  'Dryer',
  'Microwave',
  'Oven',
  'Fridge',
  'Toaster',
  'Cookware',
  'Pantry',
  'Couch',
  'TV Remote',
  'Blanket',
  'Pillow',
  'Mattress',
  'Curtains',
  'Rug',
  'Light Switch',
  'Wall Art',
  'Plant',
  'Water Spill',
  'Laundry Basket',
  'Closet',
  'Drawer',
  'Shelf',
  'Cleaning Spray',
  'Broom',
  'Mop',
  'Dish Soap',
  'Towel',
  'Shower Curtain',
  'Toilet Paper',
  'Dentist Mirror',
  'Phone Charger',
  'Mirror',
  'Clock',
  'Bookshelf',
  'Coffee Table',
  'Nightstand',
  'Doormat',
  'Scented Candle',
  'Photo Frame',
  'Indoor Plant',
  'Throw Pillow',
  'Heating Bill',
  'Leak',
  'Squeaky Floor',
  'Window',
  'Window Sill',
  'Balcony',
  'Patio',
  'Garden',
  'Mailbox',
  'Doorbell',
  'Flood',
  'Pest Control',
  'Fire Alarm',
  'Smoke Detector',
  'Door Lock',
  'Keys',
  'House Plant',
  'Furniture',
  'Cushion',
  'Remote',
  'TV Show',
  'Pillow Fort',
  'Coin',
  'Sock',
  'Dust',
  'Mirror Selfie',
  'House Party',
  'Neighbor',
  'Roommate',
  'Rent',
  'Lease',
  'Mortgage',
  'Home Office',
  'Study Desk',
  'Laptop',
  'Cable',
  'Wi-Fi',
  'Router',
  'Internet',
  'Guest Room',
  'Storage',
  'Garage',
  'Attic',
  'Basement',
  'Garden Hose',
  'Front Door',
  'Backyard',
  'Dishwasher',
  'Trash Can',
  'Light Bulb',
];