// GENERATED CATEGORY WORDS: Movies & Shows
const List<String> movies_shows_words = [
  'Squid Game',
  'Money Heist',
  'Breaking Bad',
  'The Office',
  'Stranger Things',
  'Avatar',
  'The Dark Knight',
  'Spider-Man',
  'Black Panther',
  'Interstellar',
  'Parasite',
  'Get Out',
  'Avengers Endgame',
  'Titanic',
  'The Lion King',
  'Shrek',
  'Fast and Furious',
  'John Wick',
  'Inception',
  'The Matrix',
  'Harry Potter',
  'Game of Thrones',
  'Euphoria',
  'Peaky Blinders',
  'Narcos',
  'Prison Break',
  'Outer Banks',
  'One Piece',
  'Attack on Titan',
  'Demon Slayer',
  'Jujutsu Kaisen',
  'Death Note',
  'Fullmetal Alchemist',
  'Naruto',
  'Dragon Ball Z',
  'Hunter x Hunter',
  'Sword Art Online',
  'Tokyo Ghoul',
  'Your Name',
  'Spirited Away',
  'Princess Mononoke',
  'Cowboy Bebop',
  'Vinland Saga',
  'Blue Lock',
  'Chainsaw Man',
  'Solo Leveling',
  'Lord of the Rings',
  'The Witcher',
  'Chernobyl',
  'Succession',
  'Black Mirror',
  'The Crown',
  'Bridgerton',
  'The Mandalorian',
  'Star Wars',
  'The Simpsons',
  'Rick and Morty',
  'The Boys',
  'Ozark',
  'Westworld',
  'The Queen’s Gambit',
  'The Handmaid’s Tale',
  'Modern Family',
  'Friends',
  'Seinfeld',
  'The Big Bang Theory',
  'The Flash',
  'Arrow',
  'Smallville',
  'Supernatural',
  'Lucifer',
  'The Walking Dead',
  'The Sopranos',
  'Better Call Saul',
  'Mad Men',
  'The West Wing',
  'The Good Place',
  'Community',
  'Brooklyn Nine-Nine',
  'Arrested Development',
  'Fleabag',
  'Yellowjackets',
  'Hannibal',
  'Killing Eve',
  'Schitt’s Creek',
  'Cobra Kai',
  'Gossip Girl',
  'How I Met Your Mother',
  'Parks and Recreation',
  'Marvel Cinematic Universe',
  'Disney+',
  'Netflix Original',
  'HBO Max',
  'Prime Video',
  'Crunchyroll',
  'Anime Expo',
  'Comic Con',
  'Spoiler Alert',
  'Season Finale',
  'Extra 100',
];