// GENERATED CATEGORY WORDS: Music
const List<String> music_words = [
  'Pop',
  'Rap',
  'EDM',
  'R&B',
  'Alternative',
  'Indie',
  'Hip Hop',
  'Rock',
  'Jazz',
  'Classical',
  'K-Pop',
  'Lo-fi',
  'Trap',
  'Drill',
  'Girls Pop',
  'Boy Band',
  'Concert',
  'Festival',
  'Soundcloud',
  'Viral Song',
  'Mixtape',
  'Album Drop',
  'Listening Party',
  'Summer Anthem',
  'Breakup Ballad',
  'Throwback',
  'Banger',
  'Beat Drop',
  'Chorus',
  'Verse',
  'Hook',
  'Studio Session',
  'Record Deal',
  'Spotify Wrapped',
  'Viral Remix',
  'Collaborations',
  'Turntables',
  'DJ Set',
  'Soundcheck',
  'Encore',
  'Backstage',
  'Tour Bus',
  'Headliner',
  'Opening Act',
  'Fan Club',
  'Merch',
  'Limited Edition',
  'Vinyl',
  'Cassette',
  'Debut Single',
  'Grammy',
  'Award Show',
  'Music Video',
  'Lyric Video',
  'Studio Album',
  'Single Release',
  'Remastered',
  'Mashup',
  'Acoustic',
  'Live Session',
  'Radio Hit',
  'Chart Topper',
  'Billboard',
  'Producer Tag',
  'Feature Verse',
  'Sampled Beat',
  'Drum Kit',
  'Synth',
  'Bassline',
  'Breathy Vocals',
  'Crowd Surf',
  'Stage Dive',
  'Festival Wristband',
  'Backstage Pass',
  'Sound Engineer',
  'Auto-Tune',
  'Sampler',
  'Mixdown',
  'Mastering',
  'Setlist',
  'High Note',
  'Roadie',
  'Rehearsal',
  'Album Art',
  'Music Theory',
  'Earworm',
  'Breakbeat',
  'Glowstick',
  'Retro Pop',
  'Bedroom Producer',
  'Hookline',
  'Bridge',
  'Outro',
  'Intro',
  'Remix',
  'Fan Art',
  'Songwriting',
  'Chord Progression',
  'Tempo',
  'Time Signature',
  'Rhythm',
];