// GENERATED CATEGORY WORDS: Nights Out Chaos
const List<String> nights_out_chaos_words = [
  'Pre-Drinks',
  'Lost Phone',
  'Splitting Bill',
  'Uber Surge',
  'Missing Shoes',
  'Drunk Text',
  'Group Photo',
  'Bouncer Drama',
  'Long Queue',
  'Bad DJ',
  'Spilled Drink',
  'Bathroom Cry',
  'Random Confession',
  'Kebab Run',
  'Stranger Jacket',
  'Dance Floor Fall',
  'Karaoke Disaster',
  'Mixing Drinks',
  'Losing Group',
  'Disappearing Friend',
  'Dress Code Panic',
  'Hangover',
  'Regret Selfie',
  'Sober Driver',
  'Leaving Early',
  'Table Drama',
  'Bar Tab',
  'Flirting Bartender',
  'VIP Line',
  'Afterparty',
  'Walk Home',
  'Stolen Lighter',
  'Lost Cash',
  'Venue Change',
  'Overpacked Bag',
  'Social Anxiety',
  'All-Nighter',
  'Maccas Run',
  'Separated Squad',
  'Heels vs Flats',
  'Rainy Night',
  'Wrong Uber',
  'Not Remembering',
  'Arguing Next Stop',
  'Best Night Ever',
  'Regret Outfit',
  'Found Money',
  'Phone Charge',
  'Silent Journey',
  'Morning Recap',
  'Club Fly',
  'Last Call',
  'Bottle Service',
  'Dance Off',
  'Crowd Surf',
  'Lost Ticket',
  'Wristband',
  'VIP Area',
  'Coat Check',
  'Glass Break',
  'Smoke Machine',
  'DJ Drop',
  'Glow Sticks',
  'Stranger Chat',
  'Song Request',
  'Broken Heel',
  'Friendship Test',
  'Taxi Line',
  'Bus Delay',
  'Backseat Laugh',
  'Aftermath',
  'Headache',
  'Blood Sugar',
  'Club Light',
  'Bar Stool',
  'Nightlife',
  'Noise Complaint',
  'Drink Special',
  'Street Food',
  'Raincoat',
  'Bar Fight',
  'Sleeping In',
  'Hangover Cure',
  'Lost Keys',
  'Cabbie',
  'Neon Sign',
  'Night Scene',
  'Champagne',
  'VIP Guest',
  'Rooftop Bar',
  'Late Snack',
  'Venue Hop',
  'Dancing Shoes',
  'Phone Drain',
  'Bar Sampler',
  'Party Mood',
  'Extra 97',
  'Extra 98',
  'Extra 99',
  'Extra 100',
];