// GENERATED CATEGORY WORDS: Relationship Chaos
const List<String> relationship_chaos_words = [
  'Leaving on Read',
  'Posting Then Deleting',
  'Talking Stage',
  'Situationship',
  'Double Texting',
  'Sliding into DMs',
  'Moving Fast',
  'Mixed Signals',
  'Ghosting',
  'Being Ghosted',
  'We Need to Talk',
  'Jealousy',
  'Stalking Page',
  'Thirst Trap',
  'Third Wheeling',
  'Comparing Partners',
  'Commitment Issues',
  'Meeting Family',
  'Fight Over Nothing',
  'Silent Treatment',
  'On Off',
  'Paragraph Text',
  'Emoji Overthink',
  'Watching Stories',
  'Deleting Number',
  'Falling for Friend',
  'Friend Zone',
  'Asking Friends',
  'Bad Advice',
  'Catching Feelings',
  'Pretending Fine',
  'Couple Fight',
  'Low Commitment',
  'Venting',
  'Snapchat Streak',
  'First Date',
  'Anniversary Panic',
  'Official on Social',
  'Breakup Text',
  'Crying Over Ex',
  'Block then Unblock',
  'Reconciliation',
  'Love Bombing',
  'Benching',
  'Breadcrumbing',
  'Orbiting',
  'Haunting',
  'Public Display',
  'Couple Goals',
  'Love Language',
  'Partner Swap',
  'Long Distance',
  'Jealousy Spiral',
  'Cuffing Season',
  'Heart Emoji',
  'Secret Gift',
  'Trust Issues',
  'Future Talk',
  'Mythical Relationship',
  'Love Quote',
  'Happy Place',
  'Trust Fall',
  'Date Night',
  'Relationship Poll',
  'Secret Crush',
  'Partner Search',
  'Relationship App',
  'Text Freeze',
  'Mixed Emotions',
  'Heartbreak',
  'Love Letter',
  'Dinner Date',
  'Proposal',
  'Friendship',
  'Why Are We',
  'Couples Therapy',
  'Movie Night',
  'Walk and Talk',
  'Breakup Song',
  'Sweet Talk',
  'Road Trip',
  'Sunday Morning',
  'Couple Selfie',
  'Ex Drama',
  'Relationship Habit',
  'Heartache',
  'Gift Forgetting',
  'Partner Text',
  'Relationship Joke',
  'Rumor',
  'Double Date',
  'Third Wheel',
  'Relationship Game',
  'Love Song',
  'Cuddle',
  'First Kiss',
  'Relationship Test',
  'Couple Chat',
  'Relationship Advice',
  'Extra 100',
];