// GENERATED CATEGORY WORDS: School Life
const List<String> school_life_words = [
  'Homework',
  'Detention',
  'Locker',
  'Cafeteria',
  'Group Project',
  'Freshman',
  'Senior Skip Day',
  'Pop Quiz',
  'Teacher',
  'Principal',
  'Graduation',
  'Club Fair',
  'Yearbook',
  'Hall Pass',
  'Study Group',
  'Field Trip',
  'Syllabus',
  'Backpack',
  'Prom',
  'Exam Stress',
  'Late to Class',
  'Late Assignment',
  'Exam Hall',
  'Pencil Case',
  'Math Class',
  'English Lit',
  'Chemistry Lab',
  'History Lecture',
  'Gym Class',
  'Psych Class',
  'Art Studio',
  'Lab Partner',
  'School Bus',
  'After School',
  'Sat Test',
  'Wi-Fi Password',
  'Cafeteria Food',
  'Pep Rally',
  'Teacher Pet',
  'Detention Slip',
  'Parent Teacher Conference',
  'College Essay',
  'Scholarship',
  'School Dance',
  'Spirit Week',
  'Locker Combo',
  'Quiz Bowl',
  'Student Council',
  'Yearbook Photo',
  'Senior Prank',
  'School Play',
  'Audition',
  'Hallway Drama',
  'Lunch Table',
  'Homeroom',
  'Study Hall',
  'Group Chat',
  'Textbook',
  'Teachers Lounge',
  'School Supplies',
  'Back to School',
  'Early Dismissal',
  'Final Exam',
  'Report Card',
  'School Spirit',
  'Science Fair',
  'Book Report',
  'Reading List',
  'Classroom',
  'Assembly',
  'Drama Club',
  'Chess Club',
  'Debate Team',
  'Honor Roll',
  'Principal’s Office',
  'Valedictorian',
  'Class Trip',
  'Summer Break',
  'School Nurse',
  'P.E. Uniform',
  'Grade Curve',
  'Extra Credit',
  'Reading Log',
  'Class Rank',
  'Homework Pass',
  'College Tour',
  'Cafeteria Menu',
  'Locker Decoration',
  'Bus Ticket',
  'Summer Assignment',
  'Study Break',
  'Essay Deadline',
  'Dress Code',
  'Tardy',
  'Fire Drill',
  'Teacher’s Pet',
  'Late Bus',
  'Extra 98',
  'Extra 99',
  'Extra 100',
];