// GENERATED CATEGORY WORDS: Sports
const List<String> sports_words = [
  'Football',
  'Basketball',
  'Soccer',
  'Cricket',
  'Baseball',
  'Tennis',
  'Golf',
  'Boxing',
  'MMA',
  'Yoga',
  'Surfing',
  'Skateboarding',
  'Snowboarding',
  'Skiing',
  'Athletics',
  'Track',
  'Field',
  'Swimming',
  'Diving',
  'Gymnastics',
  'Volleyball',
  'Table Tennis',
  'Badminton',
  'Cycling',
  'Rugby',
  'Hockey',
  'Auto Racing',
  'Motorsport',
  'Formula 1',
  'NASCAR',
  'Skating',
  'Cheerleading',
  'Crossfit',
  'Weightlifting',
  'Bowling',
  'Rock Climbing',
  'Fishing',
  'Hunting',
  'Archery',
  'Equestrian',
  'Fencing',
  'Ski Jump',
  'Bobsled',
  'Lacrosse',
  'Curling',
  'Polo',
  'Drone Racing',
  'Parkour',
  'Ultimate Frisbee',
  'Handball',
  'Softball',
  'Judo',
  'Karate',
  'Taekwondo',
  'Muay Thai',
  'Wrestling',
  'Triathlon',
  'Marathon',
  'Half Marathon',
  'Pole Vault',
  'Discus',
  'Shot Put',
  'Javelin',
  'Steeplechase',
  'Decathlon',
  'Biathlon',
  'Rally',
  'Kayaking',
  'Rowing',
  'Sailing',
  'Stand Up Paddle',
  'Kite Surfing',
  'BMX',
  'Mountain Bike',
  'Roller Derby',
  'Horse Racing',
  'Skeet Shooting',
  'Powerlifting',
  'Sprinter',
  'Relay',
  'High Jump',
  'Long Jump',
  'Triple Jump',
  'Obstacle Course',
  'Spinning',
  'Zumba',
  'Dance Sport',
  'Basket',
  'Field Goal',
  'Home Run',
  'Strikeout',
  'Offside',
  'Dribble',
  'Tackle',
  'Foul',
  'Penalty',
  'Overtime',
  'Timeout',
  'Coach',
  'Captain',
  'MVP',
  'Playoffs',
  'Draft',
];