// GENERATED CATEGORY WORDS: Superheroes & Villains
const List<String> superheroes_villains_words = [
  'Superman',
  'Batman',
  'Wonder Woman',
  'Spider-Man',
  'Iron Man',
  'Captain America',
  'Thor',
  'Hulk',
  'Black Panther',
  'Doctor Strange',
  'Hawkeye',
  'Black Widow',
  'Scarlet Witch',
  'Loki',
  'Thanos',
  'Joker',
  'Harley Quinn',
  'Catwoman',
  'Mystique',
  'Magneto',
  'Deadpool',
  'Venom',
  'Green Lantern',
  'Flash',
  'Aquaman',
  'Cyborg',
  'Supergirl',
  'Shazam',
  'Daredevil',
  'Punisher',
  'Wolverine',
  'Storm',
  'Cyclops',
  'Jean Grey',
  'Professor X',
  'Doctor Octopus',
  'Sandman',
  'Vulture',
  'Bane',
  'Two-Face',
  'Poison Ivy',
  'Riddler',
  'Penguin',
  'Nightwing',
  'Robin',
  'Batgirl',
  'Star-Lord',
  'Gamora',
  'Drax',
  'Groot',
  'Rocket',
  'Nebula',
  'Mantis',
  'Elektra',
  'Silver Surfer',
  'Galactus',
  'Dr. Doom',
  'Red Skull',
  'Kingpin',
  'Killmonger',
  'Hela',
  'Odin',
  'Ego',
  'Ultron',
  'Quicksilver',
  'Vision',
  'Falcon',
  'Winter Soldier',
  'Ghost Rider',
  'Blade',
  'Moon Knight',
  'She-Hulk',
  'Jessica Jones',
  'Luke Cage',
  'Iron Fist',
  'Ms. Marvel',
  'Spider-Gwen',
  'Anti-Venom',
  'Carnage',
  'Cable',
  'Deadshot',
  'Black Adam',
  'Shredder',
  'Foot Clan',
  'Green Goblin',
  'Electro',
  'Mr. Freeze',
  'Rogue',
  'Psylocke',
  'Beast',
  'Beast Boy',
  'Starfire',
  'Raven',
  'Cheetah',
  'Black Manta',
  'Deathstroke',
  'Zod',
  'Doomsday',
  'Brainiac',
  'Captain Marvel',
  'Wasp',
  'Hank Pym',
  'Iceman',
  'Nightcrawler',
  'Wanda',
];