// GENERATED CATEGORY WORDS: TikTok & Memes
const List<String> tiktok_memes_words = [
  'Ratio',
  'Shadowban',
  'Caught in 4K',
  'No Cap',
  'Rizz',
  'Slay',
  'Touch Grass',
  'Main Character',
  'It\'s Giving',
  'Lowkey',
  'Highkey',
  'NPC Trend',
  'POV',
  'Simp',
  'Based',
  'Red Flag',
  'Green Flag',
  'Beige Flag',
  'Delulu',
  'Rent Free',
  'Ate and Left No Crumbs',
  'Era',
  'Lore',
  'Side Eye',
  'Chefs Kiss',
  'That Girl',
  'Roman Empire',
  'Situationship',
  'Hot Take',
  'Brain Rot',
  'Unhinged',
  'Vibe Check',
  'Period',
  'Say Less',
  'Ick',
  'W Rizz',
  'Glazing',
  'Real One',
  'Core',
  'Mid',
  'Bussin',
  'Snatched',
  'Feral',
  'Clout',
  'Ratio\'d',
  'Stan',
  'Chronically Online',
  'Gaslight',
  'Main Character Energy',
  'FYP',
  'Viral',
  'Duet',
  'Stitch',
  'For You',
  'Trending',
  'Filter',
  'Hashtag',
  'Dance Challenge',
  'Lip Sync',
  'Sound Bite',
  'Vibe',
  'Mood',
  'Thirst Trap',
  'Green Screen',
  'Transition',
  'Glow Up',
  'Outfit Check',
  'Snack Hack',
  'Live Stream',
  'Creator',
  'Comment Section',
  'Buzz Cut',
  'Hair Flip',
  'Face Reveal',
  'Voiceover',
  'Tutorial',
  'Mukbang',
  'No Filter',
  'Sleepy',
  'Cozy',
  'Aesthetic',
  'Y2K',
  'Cottagecore',
  'Dark Academia',
  'Soft Girl',
  'Goblin Mode',
  'Creatives',
  'Vibe Shift',
  'Snack',
  'Trend',
  'For You Page',
  'Extra 92',
  'Extra 93',
  'Extra 94',
  'Extra 95',
  'Extra 96',
  'Extra 97',
  'Extra 98',
  'Extra 99',
  'Extra 100',
];