// GENERATED CATEGORY WORDS: Wild Card Chaos
const List<String> wild_card_chaos_words = [
  'Spin the Bottle',
  'Truth Roulette',
  'Dare Double',
  'Mystery Bag',
  'Whisper Challenge',
  'Charades',
  'Dance Battle',
  'Scavenger Hunt',
  'Truth Tower',
  'Wheel of Chaos',
  'Mystery Box',
  'Blindfold Challenge',
  'Lip Sync Battle',
  'Freeze Dance',
  'Guess the Song',
  'Act It Out',
  'Secret Mission',
  'Improv Story',
  'Emoji Challenge',
  'Who Am I',
  'Guess the Word',
  'Flash Mob',
  'Sudden Freeze',
  'Joke Off',
  'Penalty Spin',
  'Tongue Twister',
  'Paint with Mouth',
  'Pillow Fight',
  'Prank Call',
  'Balloon Pop',
  'Confession Circle',
  'Risk or Reward',
  'Snack Roulette',
  'Mimic Battle',
  'Story Chain',
  'Two Truths',
  'One Lie',
  'Mystery Partner',
  'Mystery Drink',
  'Good Luck Charm',
  'Truth Circle',
  'Dare Circle',
  'Secret Swap',
  'Costume Run',
  'Mystery Gift',
  'Guess the Celebrity',
  'Hidden Talent',
  'Truth Wall',
  'Flash Card',
  'Rapid Fire',
  'Meme Off',
  'Whisper Duel',
  'Voice Swap',
  'Dance Freeze',
  'Mirror Mirror',
  'Caption This',
  'Fortune Cookie',
  'Truth Scroll',
  'Dare Grill',
  'Mystery Card',
  'Mafia Round',
  'Spy Game',
  'Secret Code',
  'Light Show',
  'Neon Tag',
  'Parachute Game',
  'Secret Weapon',
  'Soundtrack',
  'Glow Paint',
  'Balloon Dare',
  'Pass the Parcel',
  'Mystery Word',
  'Draw It',
  'Emoji Story',
  'Guess the Movie',
  'Truth Tattoo',
  'Badge Swap',
  'Risk Round',
  'Truth Balloon',
  'Dare Box',
  'Wake Up Call',
  'Flash Fame',
  'Trust Fall',
  'Spotlight',
  'Secret Draw',
  'Role Play',
  'Sound Effect',
  'Glow Game',
  'Mystery Letter',
  'Wildcard',
  'Party Favour',
  'Time Bomb',
  'Clue Hunt',
  'Magic Trick',
  'Memory Game',
  'Lucky Draw',
  'Costume Switch',
  'Random Rule',
  'Puzzle Race',
  'Now or Never',
  'Truth Freeze',
];