// Cousin Chaos Party Game Content
final Map<String, dynamic> partyGameContent = {
  'rankIt': {
    'People': [
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
      'Rank by who would survive chaos longest | [Player 1], [Player 2], [Player 3], [Player 4], [Player 5]',
    ],
    'Things': [
      'Rank by most addictive | Instagram, Coffee, Pizza, Netflix, Online Shopping',
      'Rank by most addictive | Spotify, Energy Drinks, Fast Food, TikTok, Weekend Trips',
      'Rank by most addictive | Gaming, Memes, Late Night Chats, Sneakers, Vacation Plans',
      'Rank by most addictive | Ice Cream, YouTube, Cafes, Anime, Road Trips',
      'Rank by most addictive | Shopping Apps, Burgers, Soda, Group Chats, Music',
      'Rank by most addictive | Instagram, Coffee, Pizza, Netflix, Online Shopping',
      'Rank by most addictive | Spotify, Energy Drinks, Fast Food, TikTok, Weekend Trips',
      'Rank by most addictive | Gaming, Memes, Late Night Chats, Sneakers, Vacation Plans',
      'Rank by most addictive | Ice Cream, YouTube, Cafes, Anime, Road Trips',
      'Rank by most addictive | Shopping Apps, Burgers, Soda, Group Chats, Music',
      'Rank by most addictive | Instagram, Coffee, Pizza, Netflix, Online Shopping',
      'Rank by most addictive | Spotify, Energy Drinks, Fast Food, TikTok, Weekend Trips',
      'Rank by most addictive | Gaming, Memes, Late Night Chats, Sneakers, Vacation Plans',
      'Rank by most addictive | Ice Cream, YouTube, Cafes, Anime, Road Trips',
      'Rank by most addictive | Shopping Apps, Burgers, Soda, Group Chats, Music',
      'Rank by most addictive | Instagram, Coffee, Pizza, Netflix, Online Shopping',
      'Rank by most addictive | Spotify, Energy Drinks, Fast Food, TikTok, Weekend Trips',
      'Rank by most addictive | Gaming, Memes, Late Night Chats, Sneakers, Vacation Plans',
      'Rank by most addictive | Ice Cream, YouTube, Cafes, Anime, Road Trips',
      'Rank by most addictive | Shopping Apps, Burgers, Soda, Group Chats, Music',
      'Rank by most addictive | Instagram, Coffee, Pizza, Netflix, Online Shopping',
      'Rank by most addictive | Spotify, Energy Drinks, Fast Food, TikTok, Weekend Trips',
      'Rank by most addictive | Gaming, Memes, Late Night Chats, Sneakers, Vacation Plans',
      'Rank by most addictive | Ice Cream, YouTube, Cafes, Anime, Road Trips',
      'Rank by most addictive | Shopping Apps, Burgers, Soda, Group Chats, Music',
    ],
    'Scenarios': [
      'Rank by most stressful | Accidental text, Family argument, Lost wallet, Missed flight, Ex calling',
      'Rank by most stressful | Parents checking phone, Awkward silence, Failed exam, Wrong group message, Late payment',
      'Rank by most stressful | Job interview, Bad haircut, Party drama, Friend betrayal, Surprise guests',
      'Rank by most stressful | Phone battery 1%, Public speech, WiFi dead, Toxic group chat, Forgotten birthday',
      'Rank by most stressful | Cringe voice note, Family gossip, Suspicious DM, Getting ghosted, Breaking something',
      'Rank by most stressful | Accidental text, Family argument, Lost wallet, Missed flight, Ex calling',
      'Rank by most stressful | Parents checking phone, Awkward silence, Failed exam, Wrong group message, Late payment',
      'Rank by most stressful | Job interview, Bad haircut, Party drama, Friend betrayal, Surprise guests',
      'Rank by most stressful | Phone battery 1%, Public speech, WiFi dead, Toxic group chat, Forgotten birthday',
      'Rank by most stressful | Cringe voice note, Family gossip, Suspicious DM, Getting ghosted, Breaking something',
      'Rank by most stressful | Accidental text, Family argument, Lost wallet, Missed flight, Ex calling',
      'Rank by most stressful | Parents checking phone, Awkward silence, Failed exam, Wrong group message, Late payment',
      'Rank by most stressful | Job interview, Bad haircut, Party drama, Friend betrayal, Surprise guests',
      'Rank by most stressful | Phone battery 1%, Public speech, WiFi dead, Toxic group chat, Forgotten birthday',
      'Rank by most stressful | Cringe voice note, Family gossip, Suspicious DM, Getting ghosted, Breaking something',
      'Rank by most stressful | Accidental text, Family argument, Lost wallet, Missed flight, Ex calling',
      'Rank by most stressful | Parents checking phone, Awkward silence, Failed exam, Wrong group message, Late payment',
      'Rank by most stressful | Job interview, Bad haircut, Party drama, Friend betrayal, Surprise guests',
      'Rank by most stressful | Phone battery 1%, Public speech, WiFi dead, Toxic group chat, Forgotten birthday',
      'Rank by most stressful | Cringe voice note, Family gossip, Suspicious DM, Getting ghosted, Breaking something',
      'Rank by most stressful | Accidental text, Family argument, Lost wallet, Missed flight, Ex calling',
      'Rank by most stressful | Parents checking phone, Awkward silence, Failed exam, Wrong group message, Late payment',
      'Rank by most stressful | Job interview, Bad haircut, Party drama, Friend betrayal, Surprise guests',
      'Rank by most stressful | Phone battery 1%, Public speech, WiFi dead, Toxic group chat, Forgotten birthday',
      'Rank by most stressful | Cringe voice note, Family gossip, Suspicious DM, Getting ghosted, Breaking something',
    ],
  },
  'mostLikelyTo': {
    'Classic': [
      'Most likely to forget their own birthday',
      'Most likely to get famous accidentally',
      'Most likely to panic during emergencies',
      'Most likely to oversleep important events',
      'Most likely to waste money instantly',
      'Most likely to forget their own birthday',
      'Most likely to get famous accidentally',
      'Most likely to panic during emergencies',
      'Most likely to oversleep important events',
      'Most likely to waste money instantly',
      'Most likely to forget their own birthday',
      'Most likely to get famous accidentally',
      'Most likely to panic during emergencies',
      'Most likely to oversleep important events',
      'Most likely to waste money instantly',
      'Most likely to forget their own birthday',
      'Most likely to get famous accidentally',
      'Most likely to panic during emergencies',
      'Most likely to oversleep important events',
      'Most likely to waste money instantly',
      'Most likely to forget their own birthday',
      'Most likely to get famous accidentally',
      'Most likely to panic during emergencies',
      'Most likely to oversleep important events',
      'Most likely to waste money instantly',
    ],
    'Cousin Chaos': [
      'Most likely to expose family secrets',
      'Most likely to start cousin drama',
      'Most likely to hide snacks secretly',
      'Most likely to mute the family group',
      'Most likely to blame another cousin',
      'Most likely to expose family secrets',
      'Most likely to start cousin drama',
      'Most likely to hide snacks secretly',
      'Most likely to mute the family group',
      'Most likely to blame another cousin',
      'Most likely to expose family secrets',
      'Most likely to start cousin drama',
      'Most likely to hide snacks secretly',
      'Most likely to mute the family group',
      'Most likely to blame another cousin',
      'Most likely to expose family secrets',
      'Most likely to start cousin drama',
      'Most likely to hide snacks secretly',
      'Most likely to mute the family group',
      'Most likely to blame another cousin',
      'Most likely to expose family secrets',
      'Most likely to start cousin drama',
      'Most likely to hide snacks secretly',
      'Most likely to mute the family group',
      'Most likely to blame another cousin',
    ],
    'Roast Mode': [
      'Most likely to text their ex tonight',
      'Most likely to think they're secretly famous',
      'Most likely to post cringe captions',
      'Most likely to lose arguments instantly',
      'Most likely to get catfished online',
      'Most likely to text their ex tonight',
      'Most likely to think they're secretly famous',
      'Most likely to post cringe captions',
      'Most likely to lose arguments instantly',
      'Most likely to get catfished online',
      'Most likely to text their ex tonight',
      'Most likely to think they're secretly famous',
      'Most likely to post cringe captions',
      'Most likely to lose arguments instantly',
      'Most likely to get catfished online',
      'Most likely to text their ex tonight',
      'Most likely to think they're secretly famous',
      'Most likely to post cringe captions',
      'Most likely to lose arguments instantly',
      'Most likely to get catfished online',
      'Most likely to text their ex tonight',
      'Most likely to think they're secretly famous',
      'Most likely to post cringe captions',
      'Most likely to lose arguments instantly',
      'Most likely to get catfished online',
    ],
  },
  'twoTruthsOneLie': {
    'inspirationPrompts': [
      'Your most embarrassing school memory',
      'A weird thing you believed as a child',
      'A secret talent nobody expects',
      'Your worst online shopping mistake',
      'A lie you told your parents',
      'Your weirdest food combination',
      'A celebrity interaction story',
      'Something risky you once did',
      'A travel disaster memory',
      'Your funniest relationship moment',
      'Your most embarrassing school memory',
      'A weird thing you believed as a child',
      'A secret talent nobody expects',
      'Your worst online shopping mistake',
      'A lie you told your parents',
      'Your weirdest food combination',
      'A celebrity interaction story',
      'Something risky you once did',
      'A travel disaster memory',
      'Your funniest relationship moment',
      'Your most embarrassing school memory',
      'A weird thing you believed as a child',
      'A secret talent nobody expects',
      'Your worst online shopping mistake',
      'A lie you told your parents',
      'Your weirdest food combination',
      'A celebrity interaction story',
      'Something risky you once did',
      'A travel disaster memory',
      'Your funniest relationship moment',
      'Your most embarrassing school memory',
      'A weird thing you believed as a child',
      'A secret talent nobody expects',
      'Your worst online shopping mistake',
      'A lie you told your parents',
      'Your weirdest food combination',
      'A celebrity interaction story',
      'Something risky you once did',
      'A travel disaster memory',
      'Your funniest relationship moment',
      'Your most embarrassing school memory',
      'A weird thing you believed as a child',
      'A secret talent nobody expects',
      'Your worst online shopping mistake',
      'A lie you told your parents',
      'Your weirdest food combination',
      'A celebrity interaction story',
      'Something risky you once did',
      'A travel disaster memory',
      'Your funniest relationship moment',
    ],
    'exampleSets': [
      {
        '1': 'I skipped school once',
        '2': 'I met a celebrity accidentally',
        '3': 'I own a pet snake — LIE',
      },
      {
        '1': 'I failed a driving test',
        '2': 'I cried during a movie',
        '3': 'I climbed Mount Everest — LIE',
      },
      {
        '1': 'I broke my phone twice',
        '2': 'I got lost in a mall',
        '3': 'I hate pizza — LIE',
      },
      {
        '1': 'I lied about being sick',
        '2': 'I won a school competition',
        '3': 'I have never used Instagram — LIE',
      },
      {
        '1': 'I stayed awake 30 hours',
        '2': 'I got caught cheating once',
        '3': 'I can speak 6 languages — LIE',
      },
      {
        '1': 'I skipped school once',
        '2': 'I met a celebrity accidentally',
        '3': 'I own a pet snake — LIE',
      },
      {
        '1': 'I failed a driving test',
        '2': 'I cried during a movie',
        '3': 'I climbed Mount Everest — LIE',
      },
      {
        '1': 'I broke my phone twice',
        '2': 'I got lost in a mall',
        '3': 'I hate pizza — LIE',
      },
      {
        '1': 'I lied about being sick',
        '2': 'I won a school competition',
        '3': 'I have never used Instagram — LIE',
      },
      {
        '1': 'I stayed awake 30 hours',
        '2': 'I got caught cheating once',
        '3': 'I can speak 6 languages — LIE',
      },
      {
        '1': 'I skipped school once',
        '2': 'I met a celebrity accidentally',
        '3': 'I own a pet snake — LIE',
      },
      {
        '1': 'I failed a driving test',
        '2': 'I cried during a movie',
        '3': 'I climbed Mount Everest — LIE',
      },
      {
        '1': 'I broke my phone twice',
        '2': 'I got lost in a mall',
        '3': 'I hate pizza — LIE',
      },
      {
        '1': 'I lied about being sick',
        '2': 'I won a school competition',
        '3': 'I have never used Instagram — LIE',
      },
      {
        '1': 'I stayed awake 30 hours',
        '2': 'I got caught cheating once',
        '3': 'I can speak 6 languages — LIE',
      },
      {
        '1': 'I skipped school once',
        '2': 'I met a celebrity accidentally',
        '3': 'I own a pet snake — LIE',
      },
      {
        '1': 'I failed a driving test',
        '2': 'I cried during a movie',
        '3': 'I climbed Mount Everest — LIE',
      },
      {
        '1': 'I broke my phone twice',
        '2': 'I got lost in a mall',
        '3': 'I hate pizza — LIE',
      },
      {
        '1': 'I lied about being sick',
        '2': 'I won a school competition',
        '3': 'I have never used Instagram — LIE',
      },
      {
        '1': 'I stayed awake 30 hours',
        '2': 'I got caught cheating once',
        '3': 'I can speak 6 languages — LIE',
      },
      {
        '1': 'I skipped school once',
        '2': 'I met a celebrity accidentally',
        '3': 'I own a pet snake — LIE',
      },
      {
        '1': 'I failed a driving test',
        '2': 'I cried during a movie',
        '3': 'I climbed Mount Everest — LIE',
      },
      {
        '1': 'I broke my phone twice',
        '2': 'I got lost in a mall',
        '3': 'I hate pizza — LIE',
      },
      {
        '1': 'I lied about being sick',
        '2': 'I won a school competition',
        '3': 'I have never used Instagram — LIE',
      },
      {
        '1': 'I stayed awake 30 hours',
        '2': 'I got caught cheating once',
        '3': 'I can speak 6 languages — LIE',
      },
    ]
  }
};