import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:flutter/material.dart';

class LucideIcons {
  LucideIcons._();

  static const IconData settings = FontAwesomeIcons.gear;
  static const IconData user = FontAwesomeIcons.user;
  static const IconData users = FontAwesomeIcons.users;
  static const IconData arrowLeft = FontAwesomeIcons.arrowLeft;
  static const IconData arrowRight = FontAwesomeIcons.arrowRight;
  static const IconData plus = FontAwesomeIcons.plus;
  static const IconData plusCircle = FontAwesomeIcons.circlePlus;
  static const IconData x = FontAwesomeIcons.xmark;
  static const IconData info = FontAwesomeIcons.circleInfo;
  static const IconData star = FontAwesomeIcons.star;
  static const IconData refreshCw = FontAwesomeIcons.rotateRight;
  static const IconData check = FontAwesomeIcons.check;
  static const IconData checkCircle = FontAwesomeIcons.circleCheck;
  static const IconData circle = FontAwesomeIcons.circle;
  static const IconData timer = FontAwesomeIcons.stopwatch;
  static const IconData trophy = FontAwesomeIcons.trophy;
  static const IconData logOut = FontAwesomeIcons.rightFromBracket;
  static const IconData volume2 = FontAwesomeIcons.volumeHigh;
  static const IconData volumeX = FontAwesomeIcons.volumeXmark;
  static const IconData zap = FontAwesomeIcons.bolt;
  static const IconData lock = FontAwesomeIcons.lock;
  static const IconData play = FontAwesomeIcons.play;
  static const IconData pause = FontAwesomeIcons.pause;
  static const IconData skipForward = FontAwesomeIcons.forwardStep;
  static const IconData dices = FontAwesomeIcons.dice;
  static const IconData gamepad2 = FontAwesomeIcons.gamepad;
  static const IconData flame = FontAwesomeIcons.fire;
  static const IconData userX = FontAwesomeIcons.userXmark;
  static const IconData helpCircle = FontAwesomeIcons.circleQuestion;
  static const IconData shield = FontAwesomeIcons.shield;
  static const IconData gitBranch = FontAwesomeIcons.codeBranch;
  static const IconData alertTriangle = FontAwesomeIcons.triangleExclamation;
  static const IconData share2 = FontAwesomeIcons.shareNodes;
  static const IconData home = FontAwesomeIcons.house;
  static const IconData list = FontAwesomeIcons.list;
  static const IconData edit = FontAwesomeIcons.pen;
  static const IconData trash = FontAwesomeIcons.trash;
  static const IconData search = FontAwesomeIcons.magnifyingGlass;
  static const IconData eye = FontAwesomeIcons.eye;
  static const IconData eyeOff = FontAwesomeIcons.eyeSlash;
  static const IconData chevronRight = FontAwesomeIcons.chevronRight;
  static const IconData chevronLeft = FontAwesomeIcons.chevronLeft;
  static const IconData chevronDown = FontAwesomeIcons.chevronDown;
  static const IconData chevronUp = FontAwesomeIcons.chevronUp;
  static const IconData calendar = FontAwesomeIcons.calendar;
  static const IconData clock = FontAwesomeIcons.clock;
  static const IconData heart = FontAwesomeIcons.heart;
  static const IconData sparkles = FontAwesomeIcons.wandMagicSparkles;
  static const IconData package = FontAwesomeIcons.box;
  static const IconData layers = FontAwesomeIcons.layerGroup;
  static const IconData tag = FontAwesomeIcons.tag;
  static const IconData crown = FontAwesomeIcons.crown;
  static const IconData medal = FontAwesomeIcons.medal;
  static const IconData swords = FontAwesomeIcons.personFalling;
  static const IconData laugh = FontAwesomeIcons.faceGrinBeam;
  static const IconData meh = FontAwesomeIcons.faceMeh;
  static const IconData frown = FontAwesomeIcons.faceFrown;
  static const IconData theater = FontAwesomeIcons.masksTheater;
  static const IconData speed = FontAwesomeIcons.gaugeHigh;
  static const IconData verified = FontAwesomeIcons.userCheck;
  static const IconData chartBar = FontAwesomeIcons.chartBar;
  static const IconData history = FontAwesomeIcons.clockRotateLeft;
  static const IconData brain = FontAwesomeIcons.brain;
  static const IconData volume1 = FontAwesomeIcons.volumeLow;
  static const IconData loader = FontAwesomeIcons.spinner;
  static const IconData sun = FontAwesomeIcons.sun;
  static const IconData moon = FontAwesomeIcons.moon;
}
