// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboarding/FullscreenSteps.tsx": () => import("../components/mockups/onboarding/FullscreenSteps.tsx"),
  "./components/mockups/onboarding/MinimalWelcome.tsx": () => import("../components/mockups/onboarding/MinimalWelcome.tsx"),
  "./components/mockups/onboarding/SwipeCards.tsx": () => import("../components/mockups/onboarding/SwipeCards.tsx")
};
