from pathlib import Path

root = Path('lib/core/constants/impostor_categories')
root.mkdir(parents=True, exist_ok=True)

categories = {
    'Gaming': [
        'Respawn','Headshot','Loot Box','Noob','Final Boss','Health Bar','Speedrun','Controller','Camp','Rage Quit','Skin','Patch Update','Glitch','Open World','Side Quest','NPC','Easter Egg','Ranked Mode','Lag','Aim Assist','Battle Pass','Grenade','Sniper','Respawn Point','Kill Streak','Inventory','Crafting','Spawn Trap','Modded Controller','Co-op Mode','Achievements','Cutscene','Game Over','Checkpoint','Loading Screen','Hitbox','Combo Move','Unlockable','Season Pass','Prestige','One-Shot Kill','Stealth Mode','Quick Scope','Ping','Clan Tag','Map Rotation','Endgame','Lore','DLC','Server Crash','Battle Royale','Free To Play','Microtransaction','Mana Potion','Skill Tree','Boss Rush','Auto Aim','Matchmaking','Sprint Jump','Cooldown','Respawn Timer','Critical Hit','Stamina','Armor Break','Loot Drop','Story Mode','Multiplayer','Solo Queue','Dungeon Raid','Achievement','New Patch','Voice Chat','Push To Talk','Emote Wheel','HUD','Minimap','Voice Lines','Warp Zone','Speedrun','FPS','MMO','Twitch Stream','Streamer','Clutch','Smurf','Spawn Point','Buff','Nerf','Boss Fight','End Credits','Save Point','Difficulty','Ranked Ladder','Headset','Crossplay','Beta Test','Achievement Hunter','Tutorial','Leaderboard','Quest Log','Boss Arena','Wallhack','Camp Spot','XP','Skill Rating','Controller Drift','Quest Reward','Pixel Art','Retro Mode'
    ],
    'TikTok & Memes': [
        'Ratio','Shadowban','Caught in 4K','No Cap','Rizz','Slay','Touch Grass','Main Character','It\'s Giving','Lowkey','Highkey','NPC Trend','POV','Simp','Based','Red Flag','Green Flag','Beige Flag','Delulu','Rent Free','Ate and Left No Crumbs','Era','Lore','Side Eye','Chefs Kiss','That Girl','Roman Empire','Situationship','Hot Take','Brain Rot','Unhinged','Vibe Check','Period','Say Less','Ick','W Rizz','Glazing','Real One','Core','Mid','Bussin','Snatched','Feral','Clout','Ratio\'d','Stan','Chronically Online','Gaslight','Main Character Energy','FYP','Viral','Duet','Stitch','For You','Trending','Filter','Hashtag','Dance Challenge','Lip Sync','Sound Bite','Vibe','Mood','Thirst Trap','Green Screen','Transition','Glow Up','Outfit Check','Snack Hack','Live Stream','Creator','Comment Section','Buzz Cut','Hair Flip','Face Reveal','Voiceover','Tutorial','Mukbang','POV','No Filter','Sleepy','Cozy','Aesthetic','Y2K','Cottagecore','Dark Academia','Soft Girl','Goblin Mode','Buzz Cut','Face Reveal','Voiceover','Creators','Vibe Shift','Snack','No Filter','Filter','Trend','For You Page','FYP'
    ],
    'Foods': [
        'Pepperoni Pizza','Sushi Roll','Ramen','Fried Chicken','Burger','Tacos','Shawarma','Jollof Rice','Pancakes','Instant Noodles','Hot Dog','Nachos','Dumplings','Waffle','Grilled Cheese','Cheesecake','Mochi','Boba Tea','Spring Rolls','Mac and Cheese','Croissant','Curry','Popcorn','Cotton Candy','Samosa','Churros','Donut','Pho','Bibimbap','Katsu','Jerk Chicken','Empanada','Pita Bread','Hummus','Gyoza','Baklava','Chili Dog','Loaded Fries','Mango Sticky Rice','Birria Tacos','Smash Burger','Omurice','Takoyaki','Poke Bowl','Acai Bowl','Flatbread','Dim Sum','Falafel','Ice Cream Sandwich','Shakshuka','Avocado Toast','Cupcake','Street Corn','Pizza Rolls','Bagel','Sashimi','Maki','Hotpot','Gnocchi','Carbonara','Tiramisu','Bruschetta','Sushi Burrito','Kebab','Ratatouille','Gazpacho','Pierogi','Tempura','Quesadilla','Sushi Bowl','Fajitas','Huevos Rancheros','Pancit','Kimchi','Sushi Don','Tofu Stir Fry','Miso Soup','Biryani','Croissant','Ravioli','Tomahawk Steak','Ceviche','Udon','Macaron','Pancake Stack','Turkey Leg','Sushi Nigiri','Duck Confit','Peking Duck','Panini','Banh Mi','Spanakopita','Goulash','Bulgogi','Burrito','Milkshake','Donburi','Tostada','Souvlaki','Yakitori','Lemon Tart','Fruit Salad','Sushi Platter'
    ],
    'Brands & Sneakers': [
        'Air Force 1','Jordan 1','Yeezy','New Balance 550','Dunk Low','Adidas Samba','Vans Old Skool','Converse Chuck Taylor','Reebok Classic','Travis Scott','Supreme Drop','Off-White','Balenciaga','Palace','Stussy','BAPE','Fear of God','Essentials Hoodie','Champion','Carhartt','Stone Island','Corteiz','Gallery Dept','Anti Social Social Club','Kith','Noah','Aime Leon Dore','Human Made','A Bathing Ape','Nike Tech Fleece','Levis 501','Ralph Lauren','Tommy Hilfiger','Lacoste','Burberry Check','Louis Vuitton','Gucci Belt','Dior Oblique','OVO','Sp5der','Hellstar','Eric Emanuel','Madhappy','Broken Planet','Represent','Weekend Offender','Hoka Bondi','On Cloud','Air Max','Jordan 4','Jordan 11','Adidas NMD','Nike SB','Converse One Star','Jordan 3','Nike Cortez','Vans Sk8-Hi','Air Jordan','Supreme Box Logo','Billionaire Boys Club','Off White','Nike Dunks','Nike Air','New Balance 990','Fila Disruptor','Adidas Yeezy','Crocs','Birkenstock','Ugg Boots','Fila Mindblower','ASICS Gel','Puma Suede','Reebok Pump','Air Jordan 12','Puma Clyde','Nike VaporMax','Converse Platform','Veja','Kith Hoodie','Aimé Leon Dore','Fear of God','Saint Laurent','Gosha Rubchinskiy','Comme des Garcons','Heron Preston','Palm Angels','Billionaire Boys Club','Rhude','Patta','Nike UltraBoost','Jordan 5','Jordan 6','Jordan 13','Nike Air Max 97','Adidas Gazelle','Adidas Stan Smith','Vans Era','Puma RS','New Balance 990v5','Nike Jordan 1 Low','Nike Jordan 1 High','Nike React','Nike Presto'
    ],
    'Movies & Shows': [
        'Squid Game','Money Heist','Breaking Bad','The Office','Stranger Things','Avatar','The Dark Knight','Spider-Man','Black Panther','Interstellar','Parasite','Get Out','Avengers Endgame','Titanic','The Lion King','Shrek','Fast and Furious','John Wick','Inception','The Matrix','Harry Potter','Game of Thrones','Euphoria','Peaky Blinders','Narcos','Prison Break','Outer Banks','One Piece','Attack on Titan','Demon Slayer','Jujutsu Kaisen','Death Note','Fullmetal Alchemist','Naruto','Dragon Ball Z','Hunter x Hunter','Sword Art Online','Tokyo Ghoul','Your Name','Spirited Away','Princess Mononoke','Cowboy Bebop','Vinland Saga','Blue Lock','Chainsaw Man','Solo Leveling','Lord of the Rings','The Witcher','Chernobyl','Succession','Black Mirror','The Crown','Bridgerton','The Mandalorian','Star Wars','The Simpsons','Rick and Morty','The Boys','Ozark','Westworld','The Queen’s Gambit','The Handmaid’s Tale','Peaky Blinders','Modern Family','Friends','Seinfeld','The Big Bang Theory','The Flash','Arrow','Smallville','Supernatural','Lucifer','The Walking Dead','The Sopranos','Better Call Saul','Mad Men','The West Wing','The Good Place','Community','Brooklyn Nine-Nine','Arrested Development','Fleabag','Yellowjackets','Hannibal','Killing Eve','Schitt’s Creek','Cobra Kai','Gossip Girl','How I Met Your Mother','Parks and Recreation','Marvel Cinematic Universe','Disney+','Netflix Original','HBO Max','Prime Video','Crunchyroll','Anime Expo','Comic-Con','Spoiler Alert','Season Finale'
    ],
    'School Life': [
        'Homework','Detention','Locker','Cafeteria','Group Project','Freshman','Senior Skip Day','Pop Quiz','Teacher','Principal','Graduation','Club Fair','Yearbook','Hall Pass','Study Group','Field Trip','Syllabus','Backpack','Prom','Exam Stress','Late to Class','Late Assignment','Exam Hall','Pencil Case','Math Class','English Lit','Chemistry Lab','History Lecture','Gym Class','Psych Class','Art Studio','Lab Partner','School Bus','After School','Sat Test','Wi-Fi Password','Cafeteria Food','Pep Rally','Teacher Pet','Detention Slip','Parent Teacher Conference','College Essay','Scholarship','School Dance','Spirit Week','Locker Combo','Quiz Bowl','Student Council','Yearbook Photo','Senior Prank','School Mascot','Extra Credit','School Play','Audition','Hallway Drama','Lunch Table','Homeroom','Study Hall','Group Chat','Textbook','Teachers Lounge','School Supplies','Back to School','Early Dismissal','Final Exam','Report Card','School Spirit','Science Fair','Book Report','Reading List','Classroom','Assembly','Drama Club','Chess Club','Debate Team','Honor Roll','Principal’s Office','Valedictorian','Class Trip','Summer Break','School Nurse','P.E. Uniform','Grade Curve','Extra Credit','Reading Log','Class Rank','Homework Pass','College Tour','Cafeteria Menu','Locker Decoration','Bus Ticket','Summer Assignment','Study Break','Essay Deadline','School Fundraiser','Dress Code','Tardy','Fire Drill','Teacher’s Pet','Late Bus','Promposal'
    ],
    'Countries & Cities': [
        'New York','London','Paris','Tokyo','Sydney','Berlin','Barcelona','Dubai','Rome','Los Angeles','Istanbul','Toronto','Rio de Janeiro','Cape Town','Seoul','Bangkok','Singapore','Amsterdam','Madrid','Moscow','Chicago','Vancouver','Mumbai','Hong Kong','San Francisco','Cairo','Mexico City','Stockholm','Lisbon','Vienna','Melbourne','Athens','Prague','Buenos Aires','Taipei','Mumbai','Seoul','Beijing','Shanghai','Delhi','Jakarta','Manila','Lagos','Nairobi','Copenhagen','Helsinki','Oslo','Dublin','Budapest','Brussels','Zurich','Munich','Florence','Venice','Edinburgh','Barcelona','Milan','Naples','Florence','Bali','Santorini','Marrakesh','Istanbul','Amalfi Coast','Banff','Queenstown','Reykjavik','Havana','Cusco','Lima','Milan','Rome','Venice','Athens','Tel Aviv','Amman','Casablanca','Dubai','Doha','Riyadh','Abu Dhabi','Seville','Granada','Valencia','Porto','Nairobi','Kigali','Kampala','Accra','Cairo','Alexandria','Cape Town','Johannesburg','Marrakesh','Fez','Tangier','Casablanca','Antalya','Istanbul','Bucharest','Krakow','Zagreb','Dubrovnik','Ljubljana','Prague','Vienna','Budapest'
    ],
    'Family Scenarios': [
        'Family Dinner','Sibling Rivalry','Road Trip','Wedding Drama','Holiday Gift','Fake Smile','Group Chat','Couch Hog','Kitchen Fight','Baby Shower','Graduation Party','Inheritance Talk','Family Secret','Messy Room','Borrowed Clothes','Wedding Toast','Game Night','Family Photo','Love Life Questions','Parenting Advice','Halloween Costume','Secret Recipe','Dish Duty','Car Ride','Phone Call','Family Anniversary','Birthday Surprise','Study Help','Family Text','Movie Night','Neighbor Drama','Family Vacation','Old Photos','Family Argument','Dinner Table','House Rules','Pet Sitting','Sibling Text','Dad Joke','Mom Mode','Family Tradition','Family Feud','Cousin Wedding','Grandma&#039;s Food','Family Workout','Cookout','Family Picnic','Family Reunion','Family Business','Siblings Ganging Up','Family Workout','Family Trip','Family Size','Family Pressure','Family Gift','Family Advice','Family Secret','Family Emergency','Family Gossip','Family Outing','Family Costume','Family Challenge','Family Game','Family Plan','Family Fight','Family Sleepover','Family Secrets','Family Roadtrip','Family Memory','Family Dinner','Family Reaction','Family Opinion','Family Photo','Family Support','Family Surprise','Family Role','Family Habit','Family Joke','Family Argument','Family Moment','Family Drama','Family Routine','Family Project','Family Rule','Family Squad','Family Hangout','Family Brawl','Family Tradition','Family Choice','Family Role','Family Vibe','Family Story','Family Clash','Family Dinner','Family Truth','Family Dare','Family Confession','Family Fall','Family Habit','Family Gossip','Family Move','Family Gift','Family Rule','Family Side Eye','Family Roast','Family Plan','Family Help'
    ],
    'Music': [
        'Pop','Rap','EDM','R&B','Alternative','Indie','Hip Hop','Rock','Jazz','Classical','K-Pop','Lo-fi','Trap','Drill','Girls Pop','Boy Band','Concert','Festival','Soundcloud','Viral Song','Mixtape','Album Drop','Listening Party','Summer Anthem','Breakup Ballad','Throwback','Banger','Beat Drop','Chorus','Verse','Hook','Studio Session','Record Deal','Spotify Wrapped','Viral Remix','Collaborations','Turntables','DJ Set','Soundcheck','Encore','Backstage','Tour Bus','Headliner','Opening Act','Fan Club','Merch','Limited Edition','Vinyl','Cassette','Mixtape','Debut Single','Grammy','Award Show','Music Video','Lyric Video','Studio Album','Single Release','Remastered','Mashup','Acoustic','Live Session','Radio Hit','Chart Topper','Billboard','Producer Tag','Feature Verse','Sampled Beat','Drum Kit','Synth','Bassline','Breathy Vocals','Crowd Surf','Stage Dive','Festival Wristband','Backstage Pass','Sound Engineer','Auto-Tune','Sampler','Mixdown','Mastering','Setlist','High Note','Roadie','Rehearsal','Album Art','Music Theory','Earworm','Breakbeat','Festival Crowd','Glowstick','Retro Pop','Bedroom Producer','Hookline','Verse Two','Bridge','Outro','Intro','Remix','Director Cut','Behind the Scenes','Fan Art','Songwriting','Chord Progression','Tempo','Time Signature','Rhythm'
    ],
    'Superheroes & Villains': [
        'Superman','Batman','Wonder Woman','Spider-Man','Iron Man','Captain America','Thor','Hulk','Black Panther','Doctor Strange','Hawkeye','Black Widow','Scarlet Witch','Loki','Thanos','Joker','Harley Quinn','Catwoman','Mystique','Magneto','Deadpool','Venom','Green Lantern','Flash','Aquaman','Cyborg','Supergirl','Shazam','Daredevil','Punisher','Wolverine','Storm','Cyclops','Jean Grey','Professor X','Doctor Octopus','Sandman','Vulture','Bane','Two-Face','Poison Ivy','Riddler','Penguin','Nightwing','Robin','Batgirl','Star-Lord','Gamora','Drax','Groot','Rocket','Nebula','Mantis','Elektra','Silver Surfer','Galactus','Dr. Doom','Red Skull','Kingpin','Killmonger','Hela','Odin','Ego','Ultron','Mystique','Quicksilver','Vision','Falcon','Winter Soldier','Ghost Rider','Blade','Moon Knight','She-Hulk','Jessica Jones','Luke Cage','Iron Fist','Ms. Marvel','Spider-Gwen','Anti-Venom','Carnage','Cable','Deadshot','Black Adam','Shredder','Foot Clan','Green Goblin','Sandman','Lizard','Electro','Mr. Freeze','Rogue','Psylocke','Beast','Beast Boy','Starfire','Raven','Cheetah','Black Manta','Deathstroke','Zod','Doomsday','Brainiac','Captain Marvel','Wasp','Hank Pym','Falcon','Blade','Storm','Iceman','Nightcrawler','Wanda','Vision'
    ],
    'Sports': [
        'Football','Basketball','Soccer','Cricket','Baseball','Tennis','Golf','Boxing','MMA','Yoga','Surfing','Skateboarding','Snowboarding','Skiing','Athletics','Track','Field','Swimming','Diving','Gymnastics','Volleyball','Table Tennis','Badminton','Cycling','Rugby','Hockey','Auto Racing','Motorsport','Formula 1','NASCAR','Skating','Cheerleading','Crossfit','Weightlifting','Bowling','Rock Climbing','Fishing','Hunting','Archery','Equestrian','Fencing','Ski Jump','Bobsled','Lacrosse','Curling','Polo','Drone Racing','Parkour','Ultimate Frisbee','Handball','Softball','Judo','Karate','Taekwondo','Muay Thai','Wrestling','Triathlon','Marathon','Half Marathon','Pole Vault','Discus','Shot Put','Javelin','Steeplechase','Decathlon','Biathlon','Rally','Kayaking','Rowing','Sailing','Stand Up Paddle','Kite Surfing','BMX','Mountain Bike','Roller Derby','Horse Racing','Skeet Shooting','Powerlifting','Shot Put','Sprint','Relay Race','High Jump','Long Jump','Triple Jump','Obstacle Course','Spinning','Zumba','Dance Sport','Basket','Field Goal','Home Run','Strikeout','Offside','Dribble','Tackle','Foul','Penalty','Overtime','Timeout','Coach','Captain','MVP','Playoffs','Draft'
    ],
    'Social Media': [
        'Instagram','Facebook','Twitter','Snapchat','TikTok','YouTube','Reddit','Discord','Pinterest','LinkedIn','Threads','Clubhouse','WhatsApp','Telegram','Tumblr','BeReal','OnlyFans','Substack','Vimeo','Twitch','Snap Map','Stories','Reels','FYP','Likes','Followers','Hashtag','DM','Comment','Share','Viral','Algorithm','Influencer','Creator','Collab','Sponsored','Brand Deal','Swipe Up','Landing Page','Bio Link','Link in Bio','Caption','Filter','Trending','Meme','Feed','Timeline','Retweet','Quote Tweet','Notification','Story','Live','Stream','Chat','Post','Profile','Verified','Blue Tick','Unfollow','Block','Mute','Reaction','Reaction GIF','Reaction Video','Poll','Pin','Playlist','Subscriber','View Count','Analytics','Engagement','Trending','Shadowban','Reach','Impression','Algorithm','Feed','Content','Niche','Audience','Viral','Hashtag','Caption','Usernames','Handle','Bio','DMs','Story Highlights','Location Tag','Thread','Discussion','Newsfeed','Notifications','Social Proof','Influencer','Fan Page','Community','Hashtag Challenge','Trend','Subreddit','Streamer','Moderator','Viral Trend'
    ],
    'Science & School Subjects': [
        'Biology','Chemistry','Physics','Math','Algebra','Geometry','Calculus','Statistics','Economics','Psychology','Sociology','History','Geography','Literature','Biochemistry','Astronomy','Computer Science','Environmental Science','Earth Science','Anatomy','Genetics','Neuroscience','Philosophy','Political Science','Art History','Music Theory','Foreign Language','English Lit','Drama','Business','Accounting','Engineering','Robotics','Data Science','Coding','Biology Lab','Chemistry Lab','Physics Lab','Research Paper','Lecture','Seminar','Assignment','Exam','Quiz','Study Group','Textbook','Equation','Formula','Periodic Table','Cell','DNA','Gravity','Force','Energy','Planet','Atom','Molecule','Reaction','Evolution','Cellular','Thermodynamics','Quantum','Relativity','Hypothesis','Experiment','Telescope','Microscope','Genome','Neuron','Heat','Sound','Light','Electricity','Magnetism','Circuit','Software','Algorithm','Matrix','Function','Derivative','Integral','Probability','Graph','Survey','Case Study','Artifact','Author','Poem','Prose','Citation','Essay','Thesis','Field Trip','Lab Report','Lecture Notes','Professor','Classroom','Homework','Grade','Semester','Campus'
    ],
    'Random Objects': [
        'Pen','Phone','Laptop','Backpack','Wallet','Sunglasses','Keys','Watch','Headphones','Bottle','Chair','Table','Lamp','Candle','Mirror','Book','Notebook','Pillow','Blanket','Shoes','Hat','Jacket','Umbrella','Mug','Camera','Wallet','Remote','Glasses','Ring','Necklace','Bracelet','Lipstick','Scarf','Glove','Ring','Backpack','Water Bottle','Sneakers','Watch','Clock','Wallet','Marker','Poster','Plant','Speaker','Keyboard','Mouse','Phone Case','Charger','Candle','Gift','Puzzle','Toy','Card','Badge','Shoe','Towel','Toothbrush','Comb','Brush','Hairband','Magazine','Frame','Poster','Sticker','Notebook','Pen','Pencil','Ruler','Scissors','Glue','Tape','Lunchbox','Lunch Bag','Sandwich','Snack','Game Controller','Tablet','Earbuds','Laptop','Laptop Bag','Notebook','Helmet','Sunglasses','Bottle','Bottle Cap','Lighter','Flashlight','Battery','Extension Cord','Power Bank','Charger','Adapter','USB','Cable','Keychain','Coin Purse','Wallet','Map','Calendar','Poster','Poster Tube'
    ],
    'Reactions & Emotions': [
        'Laugh','Cry','Smile','Scream','Shock','Surprise','Anger','Jealousy','Love','Hate','Excitement','Boredom','Embarrassment','Pride','Confusion','Anxiety','Relief','Jealousy','Curiosity','Suspense','Nervous','Calm','Panic','Charm','Flustered','Fury','Grief','Joy','Awe','Astonishment','Disgust','Smirk','Gasp','Blush','Eye Roll','Sigh','Shrug','Moan','Gasps','Giggle','Cheer','Tense','Eyeroll','Clap','Wink','Hug','Sad','Happy','Mad','Worried','Proud','Shocked','Skeptical','Flattered','Creeped Out','Stressed','Relieved','Thrilled','Terrified','Amused','Amazed','Hurt','Vindicated','Indifferent','Hopeful','Jealous','Lonely','Confident','Afraid','Nervous','Stunned','Hysterical','Melancholy','Ecstatic','Terrified','Distracted','Obsessed','Sarcastic','Awkward','Comforted','Crushed','Envious','Furious','Homesick','Impatient','Inspired','Motivated','Overwhelmed','Peaceful','Restless','Romantic','Skeptical','Silly','Sleepy','Smug','Weird','Zoned Out','Yearning','Zealous'
    ],
    'Late Night / Vibe': [
        'Midnight Snack','Glow Up','Chill Vibes','Night Drive','Late Night Call','Moonlight','Neon','Cozy','Blanket Fort','Sleepover','Stay Up','Afterparty','Moonwalk','Starry Night','City Lights','Candlelight','Night Walk','Late Text','Red Eye','Sleepless','Dreaming','Slow Jam','Lofi','Chillhop','Night Mood','Bedhead','Pajamas','Dawn','Snapback','Glowstick','Night Shift','Nightcap','Late Study','Craving','Midnight Movie','Mystery','Vaporwave','Comfy','Night Owl','Twilight','Night Sky','Soft Glow','Streetlight','Neon Sign','Vibe Check','Late Night Talk','Moonbeam','Cloud Nine','Crowded Diner','Night Snack','After Hours','Quiet City','Subway Ride','Taxi','Backseat','Headlights','Fuzzy Socks','Record Player','Vinyl','Late Night Pizza','Midnight Coffee','Glowstick','Pixelated','Night Market','Rainy Night','Late Night Study','Street Graffiti','Neon Alley','Nightclub','After Dark','Midnight Walk','Cityscape','Night Breeze','Fast Food','Sleep Deprived','Insomnia','Moonlit','Nightcap','Dreamscape','Bedtime Story','Sleepy','Caffeine','Lounge','Jazz Night','Bedroom Pop','Soft Lights','Shadow Play','Night Chill','Mystic','Quiet Hour','Glow Mood','Cool Nights','Late Alarm','Night Drive','Smoke and Lights','Moonlit','Stardust','Sidewalk','Late Night
    ],
    'Cousin Chaos Classics': [
        'Lending Money','Family Group Chat','Borrowing the Car','Skipping Dinner','Showing Up Late','Oversharing','Favourite Child','Family Feud','Awkward Hug','Spilling Tea','Uninvited Plus One','Fighting Over Remote','Roasting Family','Embarrassing Photos','Copying Style','Flaky Cousin','Side Eye','Drunk Uncle','Know-It-All Aunt','Ghosting Texts','Sibling Rivalry','Stealing Thunder','Family Roast','Old Story','Family Do','Habits','Family Secret','Group Selfie','Holiday Drama','Kitchen War','Cousin Crush','Text Reply','Party Crash','Member Call','Ex Drama','Unexpected Visit','Sibling Sale','Family Roast','Group Voice Note','Weekend Trip','Family Meme','Wedding Speech','Birthday Surprise','Parents Meeting','Family Rules','Living Together','House Party','Family Roast','Hide and Seek','Meme Thread','Family Bet','Family Sleepover','Family Contest','Quarantine Drama','Party Wars','Cousin Gossip','Family Playlist','Family Resolution','Family Joke','Family Roast','Family Dare','Family Confession','Family Secret','Family Code','Family Reaction','Family Adventure','Family Fail','Family Circle','Family Confusion','Family Festival','Family Tradition','Family Surprise','Family Phone','Family Ride','Family Song','Family Hangout','Family Memory','Family Vibe','Family Score','Family Drama','Family Quote','Family Goal','Family Escape','Family Cooking','Family Movie','Family Snack','Family Plan','Family Rule','Family Chat','Family Sound','Family Fashion','Family Challenge','Family Sleep','Family Noise','Family Trip','Family Dance','Family Laughter','Family Fall','Family Smile','Family Scream','Family Joke','Family Text','Family Plan','Family Game','Family Mission','Family Secret','Family Laugh','Family Statement'
    ],
    'Adulting Disasters': [
        'Forgot Rent','Burned Dinner','Called in Sick','Unread Emails','Dead Plant','Overdrawn Account','Impulse Buy','Skipped Gym','Netflix Instead of Study','Lost Charger','Messy Car','Expired Food','Forgot Password','Driving Anxiety','Tax Panic','Coffee Addiction','Alarm Fail','Self Talk','Doom Scroll','Sunday Scaries','Imposter Syndrome','Inbox Zero','Crying in Car','Therapy Homework','Resignation','Plant Rescue','Meal Prep','Quarter Life','Situationship','Unmuted','Dishes Later','Online Shopping','Screen Time','Anxiety Attack','Hating Job','Doctor Avoid','Lost Keys','Food Delivery','Unfiled Tax','Wrong Text','Reply All','Forgot to Eat','Drunk Shopping','People Pleasing','Can’t Adult','Plans Cancelled','Savings Raid','Overdraft','Clothes Still Tagged','Laundry Mountain','Rent Reminder','Broken Dishwasher','Broken Heater','Phone Bill','Car Wash','Late Fee','Debt','Budget','Rent Due','College Loan','Credit Score','Insurance','Gas Bill','Utility Cutoff','Parking Ticket','Expired ID','Appointment Missed','Overpacked Bag','Car Trouble','No Hot Water','Flat Tire','New Job','Second Job','Coffee Run','Morning Commute','Lost Ticket','Recipe Fail','Missing Socks','DIY Fail','Cleaning Day','Workout Skip','Laundry Day','Meal Plan','Budget App','Savings App','Budget Spreadsheet','Late Payment','Invoice','Going Broke','Living Paycheck','Gas Pump','Student Loan','Tax Refund','Cancel Subscription','Grocery List','Takeaway Habit','Wear Old Shirt','Couch Life','Clock In','Night Shift','Bank Alert','Health Check','Birthday Budget','Weekend Plan','Lost Passport','Job Interview','Boss Call','Rent Increase'
    ],
    'Nights Out Chaos': [
        'Pre-Drinks','Lost Phone','Splitting Bill','Uber Surge','Missing Shoes','Drunk Text','Group Photo','Bouncer Drama','Long Queue','Bad DJ','Spilled Drink','Bathroom Cry','Random Confession','Kebab Run','Stranger Jacket','Dance Floor Fall','Karaoke Disaster','Mixing Drinks','Losing Group','The Disappearing Friend','Dress Code Panic','Hangover','Regret Selfie','Sober Driver','Leaving Early','Table Drama','Bar Tab','Flirting Bartender','VIP Line','Afterparty','Walk Home','Stolen Lighter','Lost Cash','Venue Change','Overpacked Bag','Social Anxiety','All-Nighter','Maccas Run','Separated Squad','Heels vs Flats','Rainy Night','Wrong Uber','Not Remembering','Arguing Next Stop','Best Night Ever','Regret Outfit','Found Money','Phone Charge','Silent Journey','Morning Recap','Club Fly','Last Call','Bottle Service','Dance Off','Crowd Surf','Lost Ticket','Bouncer Says No','Wristband','VIP Area','Coat Check','Glass Break','Smoke Machine','DJ Drop','Glow Sticks','Rumours','Ex Shows Up','Friend Drama','DJ Remixed','Stranger Chat','Song Request','Drink Spill','Broken Heel','Friendship Test','Taxi Line','Bus Delay','Backseat Laugh','Aftermath','Headache','Blood Sugar','Club Light','Bar Stool','Late Snack','Group Dance','Kissed Stranger','Shot Glass','Music Drop','Bouncer Line','Hype Crew','Nightlife','Noise Complaint','Drink Special','Street Food','Raincoat','Bar Fight','Sleeping In','Hangover Cure','Friend Rescue','Lost Keys','Cabbie','Night Scene','Champagne','VIP Guest','Rooftop Bar','Neon Sign','Wasted','Bouncer Reject','Dance Battle','Morning Story','Table Reservation','Phone Finder'
    ],
    'Relationship Chaos': [
        'Leaving on Read','Posting Then Deleting','Talking Stage','Situationship','Double Texting','Sliding into DMs','Moving Fast','Mixed Signals','Ghosting','Being Ghosted','We Need to Talk','Jealousy','Stalking Page','Thirst Trap','Third Wheeling','Comparing Partners','Commitment Issues','Meeting Family','Fight Over Nothing','Silent Treatment','On Off','Paragraph Text','Emoji Overthink','Watching Stories','Deleting Number','Falling for Friend','Friend Zone','Asking Friends','Bad Advice','Catching Feelings','Pretending Fine','Couple Fight','Low Commitment','Venting','Snapchat Streak','First Date','Anniversary Panic','Official on Social','Breakup Text','Crying Over Ex','Block then Unblock','Reconciliation','Love Bombing','Benching','Breadcrumbing','Orbiting','Haunting','Cuffing Season','First Kiss','Relationship Goals','Heartbreak Hotel','Red Flag','Green Flag','Soft Launch','Public Display','Couple Goals','Love Letter','Heart Emoji','Mixed Signals','Text Freeze','Late Reply','Pet Name','Couple Chat','Memes Together','Toxic Talk','Love Language','Growing Apart','Stuck in Between','Relationship Advice','Fight then Makeup','Dance Together','Weekend Plans','Movie Night','Couple Therapy','Social Media Official','Ex at Party','Wedding Talk','Breaking Up','Getting Back Together','Happy Place','Trust Issues','Secret Gift','Ring Shopping','Where Are We?','Partner Swap','Long Distance','Jealousy Spiral','Couples Massage','Gift Forgetting','Compatibility Test','Future Talk','Mythical Relationship','Love Quote','Heartbroken','Date Night','Relationship Poll','Secret Crush','Promise Ring','Eye Contact','Cuddle','Breakup Song','Love Confession','Secret Message','Relationship Rules','Relationship Drama'
    ],
    'Cousin Chaos Dares & Confessions': [
        'Truth or Dare','Confess Crush','Swap Clothes','Dance in Public','Call Ex','Tell a Secret','Do a Dare','Say Something Embarrassing','Eat Something Weird','Sing Loudly','Text Your Crush','Act Like a Celebrity','Confess Fear','Show Your Phone','Do a Cartwheel','Spend $5 on a Wish','Say I Love You','Do a Dramatic Monologue','Confess a Lie','Impersonate Someone','Reveal Biggest Regret','Do 10 Jumping Jacks','Share a Family Secret','Do a Funny Voice','Attempt a Tongue Twist','Tell a Joke','Confess a Crush','Post an Old Photo','Send a Random Meme','Do an Impression','Do a Dance Move','Confess Biggest Pet Peeve','Show Your Search History','Call Best Friend','Speak in Accent','Give Someone a Compliment','Confess a Bad Habit','Eat a Spoonful of Spice','Share Your Crush','Do a Dramatic Scene','Tell an Embarrassing Story','Post a Silly Selfie','Confess a Habit','Sing a Chorus','Act Like a Robot','Reveal a Guilty Pleasure','Wear Something Ridiculous','Wedding Toast','Tell a Secret','Do a Handstand','Text Your School Crush','Share a Childhood Mistake','Do a Sassy Walk','Reveal Your Worst Date','Do a Dare on Stage','Show Your Dance Move','Confess a Lie','Reveal Favorite Crush','Do a Karaoke Verse','Post a Meme','Confess a Fear','Do a Dramatic Exit','Tell a Secret','Sing a Disney Song','Swap Shoes','Do a 10-Second Challenge','Confess Most Awkward Moment','Share a Secret','Perform a Dare','Post a Fake Story','Share Your Most Embarrassing Moment','Do a Dare Now','Confess an Online Habit','Tell a Childhood Secret','Do an Impression','Reveal Your Crush','Post a Late Night Selfie','Do a Dare Call','Confess Your Worst Habit','Tell a Lie','Perform a Dare','Confess an Odd Fear','Do a Dare with Props','Reveal your Fake Name','Text a Random Contact','Do a Dare Song','Share a Secret','Show your Dance','Do an Accent','Confess your Weirdest Dream','Pass a Note','Act Out a Scene','Share a Embarrassing Text','Do a Dare on Camera'
    ],
    'Wild Card Chaos': [
        'Spin the Bottle','Truth Roulette','Dare Double','Mystery Bag','Whisper Challenge','Charades','Dance Battle','Scavenger Hunt','Truth Tower','Wheel of Chaos','Mystery Box','Blindfold Challenge','Lip Sync Battle','Freeze Dance','Guess the Song','Act It Out','Secret Mission','Improv Story','Emoji Challenge','Who Am I','Guess the Word','Flash Mob','Sudden Freeze','Joke Off','Penalty Spin','Tongue Twister','Paint with Mouth','Pillow Fight','Prank Call','Balloon Pop','Confession Circle','Risk or Reward','Snack Roulette','Mimic Battle','Story Chain','Two Truths','One Lie','Mystery Partner','Mystery Drink','Good Luck Charm','Truth Circle','Dare Circle','Secret Swap','Costume Run','Trivia Time','Guess the Celebrity','Hidden Talent','Truth Wall','Flash Card','Rapid Fire','Meme Off','Whisper Duel','Voice Swap','Dance Freeze','Mirror Mirror','Caption This','Fortune Cookie','Truth Scroll','Dare Grill','Mafia Round','Spy Game','Secret Code','Light Show','Neon Tag','Puzzle Race','Water Gun','Memory Game','Lucky Draw','Dance Off','Costume Switch','Random Rule','Soundtrack','Glow Paint','Balloon Dare','Pass the Parcel','Mystery Word','Draw It','Emoji Story','Guess the Movie','Truth Tattoo','Badge Swap','Risk Round','Truth Balloon','Dare Box','Wake Up Call','Flash Fame','Trust Fall','Spotlight','Secret Draw','Dare Wheel','Mystery Gift','Wildcard','Party Favour','Time Bomb','Clue Hunt','Mystery List','Truth Chat','Dare Deck','Hidden Message','Role Play','Secret Weapon','Sound Effect','Glow Game'
    ],
    'Celebrity & Pop Culture Chaos': [
        'Taylor Swift','Beyonce','Ariana Grande','Drake','Bad Bunny','Doja Cat','Billie Eilish','Olivia Rodrigo','Kanye West','Kendrick Lamar','Rihanna','Harry Styles','Selena Gomez','Zendaya','BTS','BLACKPINK','Justin Bieber','The Weeknd','Kylie Jenner','Kim Kardashian','Shawn Mendes','Lizzo','Cardi B','Megan Thee Stallion','Travis Scott','Doja Cat','Ed Sheeran','Adele','Bruno Mars','Dua Lipa','SZA','Kylie Jenner','Kim Kardashian','Paris Hilton','Britney Spears','Madonna','Lady Gaga','Britney','Elon Musk','Taylor Swift','Drake','Billboard','Grammy','Oscars','Met Gala','Red Carpet','Coachella','Super Bowl','NBA Finals','World Cup','Pop Culture','Reality TV','Influencer','Memes','Viral Dance','TikTok Trend','Celebrity Couple','Breakup','Scandal','Collab','Tour','Album Release','Fashion Line','Brand Deal','Reality Show','Award Show','Scripted Drama','Live Performance','Music Video','TV Series','Movie Premiere','Social Media','Fan Base','K-Pop Group','Idol Group','Brand Campaign','Podcast','Interview','Movie Trailer','Blockbuster','Comic Con','Superhero Movie','Biopic','Director','Producer','Celebrity Chef','Fashion Icon','Style Moment','Viral Video','Dating Rumor','Fan Art','Trend','Pop Culture News','Cover Song','Remix','Merch Drop','Red Carpet Dress','Guitar Solo','Dance Crew','Billboard Hot 100'
    ],
    'House Chaos': [
        'Living Room','Kitchen','Bathroom','Bedroom','Laundry','Dishes','Trash Day','Dust Bunnies','Clutter','Floor Stains','Broken Lamp','Creaky Door','Leaky Faucet','Lost Remote','Mismatched Socks','Vacuum','Washing Machine','Dryer','Microwave','Oven','Fridge','Toaster','Cookware','Pantry','Couch','TV Remote','Blanket','Pillow','Mattress','Curtains','Rug','Light Switch','Wall Art','Plant','Water Spill','Laundry Basket','Closet','Drawer','Shelf','Cleaning Spray','Broom','Mop','Dish Soap','Towel','Shower Curtain','Toilet Paper','Dentist','Mirror','Clock','Bookshelf','Coffee Table','Nightstand','Doormat','Steam Iron','Heating','Air Conditioner','Ceiling Fan','Switchboard','Extension Cord','Power Outlet','Lamp Shade','Heating Bill','Leak','Squeaky Floor','Window','Window Sill','Balcony','Patio','Garden','Mailbox','Doorbell','Flood','Pest Control','Fire Alarm','Smoke Detector','Door Lock','Keys','House Plant','Furniture','Cushion','Remote','TV Show','Pillow fort','Coin','Sock','Dust','Mirror selfie','House Party','Neighbors','Roommate','Rent','Lease','Mortgage','Home Office','Study Desk','Laptop','Cable','Wi-Fi','Router','Internet','Guest Room','Storage','Garage','Attic','Basement','Garden Hose','Front Door','Backyard'
    ],
}

# enforce uniqueness and length
for name, items in categories.items():
    seen = set()
    unique = []
    for item in items:
        if item not in seen:
            unique.append(item)
            seen.add(item)
    items[:] = unique
    i = 1
    while len(items) < 100:
        candidate = f"Extra {name} {i}"
        if candidate not in seen:
            items.append(candidate)
            seen.add(candidate)
        i += 1

imports = []
map_entries = []
for category, items in categories.items():
    safe_name = ''.join(ch.lower() if ch.isalnum() else '_' for ch in category).strip('_')
    file_path = root / f'{safe_name}.dart'
    var_name = f'{safe_name}_words'
    with file_path.open('w', encoding='utf-8') as f:
        f.write(f"// GENERATED CATEGORY WORDS: {category}\n")
        f.write(f"const List<String> {var_name} = [\n")
        for item in items:
            f.write(f"  '{item.replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'")}',\n")
        f.write('];\n')
    imports.append(f"import 'impostor_categories/{file_path.name}';")
    map_entries.append(f"    '{category.toUpperCase()}': {var_name},")

main_file = Path('lib/core/constants/impostor_data.dart')
with main_file.open('w', encoding='utf-8') as f:
    f.write('/* GENERATED IMPOSTOR WORD DATABASE */\n')
    for imp in imports:
        f.write(imp + '\n')
    f.write('\nclass ImpostorData {\n')
    f.write('  static const Map<String, List<String>> categories = {\n')
    for entry in map_entries:
        f.write(entry + '\n')
    f.write('  };\n')
    f.write('}\n')

print('Generated', len(categories), 'category files and main impostor_data.dart')
