// Cousin Chaos Alibi Mode Data
// 5 categories × 75 questions = 375 alibi questions

final Map<String, List<String>> alibiQuestionsByCategory = {
  'Food Crime': [
    'Someone ate the secret dessert after the group split up. What was your excuse?',
    'Someone ate the secret dessert at midnight. What was your excuse?',
    'Someone ate the secret dessert during a family gathering. What was your excuse?',
    'Someone ate the secret dessert during summer vacation. Why should we believe you did not eat it?',
    'Someone ate the secret dessert when everyone was hungry. What were you eating?',
    'Someone ate the secret dessert when the lights went off. Who saw you near the food?',
    'Someone ate the secret dessert when the room became chaotic. What food item did you notice missing?',
    'Someone ate the secret dessert while music was playing. Why were you in the kitchen?',
    'Someone blamed the dog for missing food after someone shouted. What were you eating?',
    'Someone blamed the dog for missing food during a family gathering. Why should we believe you did not eat it?',
    'Someone blamed the dog for missing food when the lights went off. Why were you in the kitchen?',
    'Someone drank the cold drink without asking before the argument started. What were you eating?',
    'Someone drank the cold drink without asking during game night. What were you eating?',
    'Someone drank the cold drink without asking during the funniest moment. Who saw you near the food?',
    'Someone drank the cold drink without asking when everyone was hungry. Why were you holding a plate?',
    'Someone drank the cold drink without asking while everyone was distracted. What did you smell first?',
    'Someone finished the biryani before dinner before everyone noticed. Who was acting hungry?',
    'Someone finished the biryani before dinner while people were taking photos. What did you smell first?',
    'Someone hid the good snacks at midnight. Why were you in the kitchen?',
    'Someone hid the good snacks before the argument started. Why were you holding a plate?',
    'Someone hid the good snacks during a family gathering. Why were you holding a plate?',
    'Someone hid the good snacks during summer vacation. Why were you in the kitchen?',
    'Someone mixed up the food orders after someone shouted. Why should we believe you did not eat it?',
    'Someone mixed up the food orders after someone shouted. Why were you holding a plate?',
    'Someone mixed up the food orders during a family gathering. Why were you in the kitchen?',
    'Someone mixed up the food orders during summer vacation. What was your excuse?',
    'Someone mixed up the food orders when the lights went off. Why should we believe you did not eat it?',
    'Someone mixed up the food orders when the room became chaotic. What was your excuse?',
    'Someone mixed up the food orders while music was playing. What food item did you notice missing?',
    'Someone stole fries from everyone\'s plate before the argument started. Who was acting hungry?',
    'Someone stole fries from everyone\'s plate before the argument started. Why were you holding a plate?',
    'Someone stole fries from everyone\'s plate while people were taking photos. Who saw you near the food?',
    'The cake had one bite missing after the group split up. Why should we believe you did not eat it?',
    'The cake had one bite missing at midnight. Why were you holding a plate?',
    'The cake had one bite missing before everyone noticed. Why were you in the kitchen?',
    'The cake had one bite missing during a family gathering. Who was acting hungry?',
    'The cake had one bite missing during summer vacation. What were you eating?',
    'The cake had one bite missing while music was playing. What did you smell first?',
    'The cake had one bite missing while people were taking photos. Why were you holding a plate?',
    'The chips packet was opened secretly after someone shouted. Who was acting hungry?',
    'The chips packet was opened secretly at midnight. Why should we believe you did not eat it?',
    'The chips packet was opened secretly before everyone noticed. Why were you in the kitchen?',
    'The chips packet was opened secretly before the argument started. What snack did you last touch?',
    'The chips packet was opened secretly during a family gathering. Why should we believe you did not eat it?',
    'The chips packet was opened secretly during game night. Why were you in the kitchen?',
    'The chips packet was opened secretly during summer vacation. What food item did you notice missing?',
    'The chips packet was opened secretly during the funniest moment. Why were you in the kitchen?',
    'The chips packet was opened secretly when everyone was hungry. What snack did you last touch?',
    'The chocolate box was found empty during game night. Why were you in the kitchen?',
    'The chocolate box was found empty when everyone was hungry. What was your excuse?',
    'The ice cream tub was left open at midnight. What were you eating?',
    'The ice cream tub was left open at midnight. Who saw you near the food?',
    'The ice cream tub was left open when the lights went off. What was your excuse?',
    'The ice cream tub was left open when the lights went off. Who saw you near the food?',
    'The ice cream tub was left open when the lights went off. Why should we believe you did not eat it?',
    'The ice cream tub was left open when the room became chaotic. What snack did you last touch?',
    'The kitchen smelled like food at 2AM after the group split up. What snack did you last touch?',
    'The kitchen smelled like food at 2AM after the group split up. What were you eating?',
    'The kitchen smelled like food at 2AM before everyone noticed. What snack did you last touch?',
    'The kitchen smelled like food at 2AM before everyone noticed. What were you eating?',
    'The kitchen smelled like food at 2AM before the argument started. Why were you in the kitchen?',
    'The kitchen smelled like food at 2AM during game night. What did you smell first?',
    'The kitchen smelled like food at 2AM during game night. What was your excuse?',
    'The kitchen smelled like food at 2AM during the funniest moment. Why were you holding a plate?',
    'The kitchen smelled like food at 2AM while everyone was distracted. What did you smell first?',
    'The last slice of pizza disappeared after the group split up. What snack did you last touch?',
    'The last slice of pizza disappeared during a family gathering. What were you eating?',
    'The last slice of pizza disappeared during the funniest moment. Why were you in the kitchen?',
    'The last slice of pizza disappeared while music was playing. What food item did you notice missing?',
    'The last slice of pizza disappeared while people were taking photos. Who was acting hungry?',
    'The midnight snack stash vanished after the group split up. What food item did you notice missing?',
    'The midnight snack stash vanished before everyone noticed. Why were you in the kitchen?',
    'The midnight snack stash vanished when the lights went off. What snack did you last touch?',
    'The spicy sauce was added to someone\'s food before the argument started. What did you smell first?',
    'The spicy sauce was added to someone\'s food while music was playing. Why were you in the kitchen?',
  ],

  'Money Crime': [
    'A UPI payment screenshot looked suspicious before everyone noticed. Why was your wallet out?',
    'A UPI payment screenshot looked suspicious before the argument started. What did you buy?',
    'A UPI payment screenshot looked suspicious during the funniest moment. Who was near the cash?',
    'A UPI payment screenshot looked suspicious when the lights went off. What was your payment proof?',
    'A UPI payment screenshot looked suspicious when the room became chaotic. What did you spend money on?',
    'A UPI payment screenshot looked suspicious while music was playing. Why did the bill not match?',
    'A mysterious online order was placed when everyone was hungry. Where was the money last seen?',
    'A split bill became confusing before everyone noticed. Who handled the payment?',
    'A split bill became confusing before the argument started. Where was the money last seen?',
    'A split bill became confusing during a family gathering. Why did the bill not match?',
    'A split bill became confusing while people were taking photos. Why should we trust your calculation?',
    'A wallet was moved from the table during a family gathering. What did you spend money on?',
    'A wallet was moved from the table during the funniest moment. Why should we trust your calculation?',
    'A wallet was moved from the table while everyone was distracted. Why did the bill not match?',
    'A wallet was moved from the table while everyone was distracted. Why should we trust your calculation?',
    'Someone borrowed cash and forgot to return it before the argument started. Why did the bill not match?',
    'Someone borrowed cash and forgot to return it during a family gathering. Who was near the cash?',
    'Someone borrowed cash and forgot to return it when the room became chaotic. Why did the bill not match?',
    'Someone borrowed cash and forgot to return it while music was playing. What did you spend money on?',
    'Someone borrowed cash and forgot to return it while music was playing. What was your payment proof?',
    'Someone borrowed cash and forgot to return it while people were taking photos. What did you spend money on?',
    'Someone bought snacks with shared money after the group split up. Who was near the cash?',
    'Someone bought snacks with shared money at midnight. Why should we trust your calculation?',
    'Someone bought snacks with shared money during game night. What was your payment proof?',
    'Someone bought snacks with shared money while music was playing. What was your payment proof?',
    'Someone bought snacks with shared money while music was playing. Why should we trust your calculation?',
    'Someone bought snacks with shared money while people were taking photos. Where was the money last seen?',
    'Someone claimed they already paid during summer vacation. Who asked for change?',
    'Someone ordered extra food without telling anyone while music was playing. Who was near the cash?',
    'Someone ordered extra food without telling anyone while people were taking photos. What was your payment proof?',
    'Someone paid less but ate more after someone shouted. Who asked for change?',
    'Someone paid less but ate more at midnight. Who was near the cash?',
    'Someone paid less but ate more during the funniest moment. Who was near the cash?',
    'Someone spent the group budget during the funniest moment. What did you spend money on?',
    'Someone spent the group budget during the funniest moment. Who was near the cash?',
    'Someone spent the group budget while everyone was distracted. Who handled the payment?',
    'Someone used the coupon alone at midnight. Who was near the cash?',
    'Someone used the coupon alone before the argument started. Why should we trust your calculation?',
    'Someone used the coupon alone during a family gathering. What did you buy?',
    'Someone used the coupon alone when everyone was hungry. Why was your wallet out?',
    'Someone used the coupon alone while music was playing. What was your payment proof?',
    'Someone used the coupon alone while music was playing. Where was the money last seen?',
    'Someone used the coupon alone while people were taking photos. Why should we trust your calculation?',
    'The change from the shop disappeared during game night. What did you spend money on?',
    'The change from the shop disappeared during summer vacation. What was your payment proof?',
    'The change from the shop disappeared during the funniest moment. Why did the bill not match?',
    'The change from the shop disappeared during the funniest moment. Why was your wallet out?',
    'The change from the shop disappeared when everyone was hungry. Who handled the payment?',
    'The change from the shop disappeared while everyone was distracted. Where was the money last seen?',
    'The change from the shop disappeared while people were taking photos. What did you spend money on?',
    'The emergency cash envelope was opened during summer vacation. Why did the bill not match?',
    'The emergency cash envelope was opened during summer vacation. Why was your wallet out?',
    'The emergency cash envelope was opened when everyone was hungry. Why did the bill not match?',
    'The emergency cash envelope was opened when the room became chaotic. Who handled the payment?',
    'The emergency cash envelope was opened while music was playing. Why was your wallet out?',
    'The game prize money went missing during summer vacation. Why was your wallet out?',
    'The game prize money went missing when the room became chaotic. Why should we trust your calculation?',
    'The game prize money went missing while everyone was distracted. Who asked for change?',
    'The game prize money went missing while everyone was distracted. Who handled the payment?',
    'The party contribution money went missing after someone shouted. Who asked for change?',
    'The party contribution money went missing after the group split up. Where was the money last seen?',
    'The party contribution money went missing at midnight. What did you buy?',
    'The party contribution money went missing at midnight. Who was near the cash?',
    'The party contribution money went missing at midnight. Why did the bill not match?',
    'The party contribution money went missing at midnight. Why should we trust your calculation?',
    'The party contribution money went missing before the argument started. Who asked for change?',
    'The party contribution money went missing during a family gathering. Who handled the payment?',
    'The party contribution money went missing during a family gathering. Why should we trust your calculation?',
    'The party contribution money went missing during the funniest moment. Who handled the payment?',
    'The party contribution money went missing when everyone was hungry. Who asked for change?',
    'The party contribution money went missing when the lights went off. What did you buy?',
    'The party contribution money went missing when the lights went off. Why should we trust your calculation?',
    'The party contribution money went missing while everyone was distracted. What did you buy?',
    'The party contribution money went missing while everyone was distracted. Who asked for change?',
    'The party contribution money went missing while music was playing. What did you spend money on?',
  ],

  'House': [
    'A pillow fight destroyed the room while everyone was distracted. Why should we believe you did not do it?',
    'A pillow fight destroyed the room while music was playing. What did you notice first?',
    'A pillow fight destroyed the room while people were taking photos. Who was with you?',
    'Someone broke a glass before the argument started. Why should we believe you did not do it?',
    'Someone broke a glass during the funniest moment. Who was with you?',
    'Someone broke a glass during the funniest moment. Why should we believe you did not do it?',
    'Someone broke a glass when the lights went off. What sound did you hear?',
    'Someone broke a glass while music was playing. Why were you near the scene?',
    'Someone left wet footprints inside before everyone noticed. What was already broken?',
    'Someone left wet footprints inside before the argument started. What did you notice first?',
    'Someone left wet footprints inside during the funniest moment. Why were you near the scene?',
    'Someone left wet footprints inside when everyone was hungry. What sound did you hear?',
    'Someone left wet footprints inside when the room became chaotic. What did you notice first?',
    'Someone left wet footprints inside while everyone was distracted. Where were you in the house?',
    'Someone locked the balcony door while people were taking photos. What did you touch?',
    'Someone locked the balcony door while people were taking photos. Who looked most nervous?',
    'Someone moved the furniture during summer vacation. Where were you in the house?',
    'Someone moved the furniture when the room became chaotic. Who looked most nervous?',
    'Someone moved the furniture while music was playing. Who was with you?',
    'Someone moved the furniture while people were taking photos. Who looked most nervous?',
    'The TV remote disappeared during game night. Who was with you?',
    'The TV remote disappeared during the funniest moment. What sound did you hear?',
    'The TV remote disappeared when everyone was hungry. What did you touch?',
    'The TV remote disappeared when the room became chaotic. What did you notice first?',
    'The bathroom was flooded after someone shouted. What did you notice first?',
    'The bathroom was flooded after the group split up. What did you touch?',
    'The bathroom was flooded after the group split up. What sound did you hear?',
    'The bathroom was flooded during a family gathering. What was already broken?',
    'The bathroom was flooded during game night. Where were you in the house?',
    'The bathroom was flooded during the funniest moment. What did you notice first?',
    'The bathroom was flooded when the lights went off. Who looked most nervous?',
    'The bathroom was flooded while music was playing. What did you notice first?',
    'The bathroom was flooded while music was playing. What was already broken?',
    'The charger disappeared from the plug after someone shouted. Who looked most nervous?',
    'The charger disappeared from the plug before everyone noticed. Who was with you?',
    'The charger disappeared from the plug before the argument started. What was already broken?',
    'The charger disappeared from the plug during a family gathering. What did you notice first?',
    'The charger disappeared from the plug during summer vacation. What sound did you hear?',
    'The charger disappeared from the plug when the lights went off. Who was with you?',
    'The charger disappeared from the plug when the room became chaotic. What did you touch?',
    'The charger disappeared from the plug while music was playing. What did you touch?',
    'The fan was left running at midnight. What was already broken?',
    'The fan was left running during summer vacation. What did you touch?',
    'The fan was left running when the room became chaotic. Why should we believe you did not do it?',
    'The house keys went missing after someone shouted. What did you notice first?',
    'The house keys went missing after someone shouted. What was already broken?',
    'The house keys went missing after the group split up. What did you notice first?',
    'The house keys went missing before the argument started. Who was with you?',
    'The house keys went missing during summer vacation. Where were you in the house?',
    'The house keys went missing when everyone was hungry. Why should we believe you did not do it?',
    'The house keys went missing when the room became chaotic. What did you touch?',
    'The house keys went missing while music was playing. Who looked most nervous?',
    'The lights were left on all night after someone shouted. Where were you in the house?',
    'The lights were left on all night after the group split up. What did you touch?',
    'The lights were left on all night during a family gathering. Who looked most nervous?',
    'The lights were left on all night during game night. What did you touch?',
    'The lights were left on all night when the lights went off. Who looked most nervous?',
    'The lights were left on all night when the room became chaotic. What was already broken?',
    'The lights were left on all night while music was playing. Who was with you?',
    'The living room was messy after everyone left during a family gathering. Where were you in the house?',
    'The living room was messy after everyone left when everyone was hungry. Why should we believe you did not do it?',
    'The living room was messy after everyone left when the room became chaotic. Who looked most nervous?',
    'The living room was messy after everyone left while everyone was distracted. What sound did you hear?',
    'The mirror had fingerprints after the group split up. Why should we believe you did not do it?',
    'The mirror had fingerprints at midnight. What sound did you hear?',
    'The mirror had fingerprints during a family gathering. What did you touch?',
    'The mirror had fingerprints during a family gathering. Why were you near the scene?',
    'The mirror had fingerprints during the funniest moment. Who looked most nervous?',
    'The mirror had fingerprints when the lights went off. What did you touch?',
    'The mirror had fingerprints while people were taking photos. Where were you in the house?',
    'The sofa had a mysterious stain at midnight. Why were you near the scene?',
    'The sofa had a mysterious stain before everyone noticed. Who looked most nervous?',
    'The sofa had a mysterious stain before the argument started. What room did you enter last?',
    'The sofa had a mysterious stain before the argument started. What was already broken?',
    'The sofa had a mysterious stain while everyone was distracted. Why should we believe you did not do it?',
  ],

  'Social': [
    'A fake rumor started in the group after the group split up. Why were you holding someone\'s phone?',
    'A fake rumor started in the group before the argument started. Why were you laughing?',
    'A fake rumor started in the group during a family gathering. Who sent the message?',
    'A fake rumor started in the group while music was playing. What did you see on the screen?',
    'A funny photo was posted without permission before everyone noticed. What was your last notification?',
    'A funny photo was posted without permission before the argument started. What did you see on the screen?',
    'A funny photo was posted without permission during a family gathering. Who had the phone last?',
    'A funny photo was posted without permission when the lights went off. What screenshot did you see?',
    'A funny photo was posted without permission while everyone was distracted. What screenshot did you see?',
    'A funny photo was posted without permission while music was playing. Who was acting too quiet?',
    'A meme was made about someone before the argument started. Why should we believe you did not post it?',
    'A meme was made about someone during game night. Why were you holding someone\'s phone?',
    'A meme was made about someone when the lights went off. Why were you holding someone\'s phone?',
    'A meme was made about someone while music was playing. What screenshot did you see?',
    'A private story was shown to everyone after the group split up. Why should we believe you did not post it?',
    'A private story was shown to everyone before everyone noticed. Why were you laughing?',
    'A private story was shown to everyone during a family gathering. Who started the drama?',
    'A screenshot appeared in the group after the group split up. Who had the phone last?',
    'A screenshot appeared in the group after the group split up. Why were you holding someone\'s phone?',
    'A screenshot appeared in the group at midnight. Who sent the message?',
    'A screenshot appeared in the group when the lights went off. What did you see on the screen?',
    'A selfie was edited badly and shared before everyone noticed. Why were you laughing?',
    'A selfie was edited badly and shared during game night. Why should we believe you did not post it?',
    'A selfie was edited badly and shared during summer vacation. What was your last notification?',
    'A selfie was edited badly and shared during the funniest moment. Who sent the message?',
    'A selfie was edited badly and shared when everyone was hungry. Who had the phone last?',
    'A selfie was edited badly and shared while people were taking photos. What screenshot did you see?',
    'A voice note was played out loud before everyone noticed. What screenshot did you see?',
    'A voice note was played out loud before everyone noticed. Why were you holding someone\'s phone?',
    'A voice note was played out loud during the funniest moment. Why were you holding someone\'s phone?',
    'Someone changed the playlist during the party after the group split up. What was your last notification?',
    'Someone changed the playlist during the party at midnight. What screenshot did you see?',
    'Someone changed the playlist during the party during the funniest moment. What screenshot did you see?',
    'Someone changed the playlist during the party when everyone was hungry. Who was acting too quiet?',
    'Someone changed the playlist during the party while music was playing. Why were you laughing?',
    'Someone changed the playlist during the party while people were taking photos. What was your last notification?',
    'Someone exposed an old crush before everyone noticed. What was your last notification?',
    'Someone exposed an old crush when everyone was hungry. Who sent the message?',
    'Someone exposed an old crush when everyone was hungry. Why were you holding someone\'s phone?',
    'Someone exposed an old crush while people were taking photos. Who sent the message?',
    'Someone exposed an old crush while people were taking photos. Why were you laughing?',
    'Someone leaked a group chat message during summer vacation. Why were you holding someone\'s phone?',
    'Someone leaked a group chat message while everyone was distracted. Why were you holding someone\'s phone?',
    'Someone leaked a group chat message while music was playing. Who started the drama?',
    'Someone liked an old post by mistake before the argument started. What screenshot did you see?',
    'Someone liked an old post by mistake before the argument started. Who had the phone last?',
    'Someone liked an old post by mistake during game night. Who started the drama?',
    'Someone liked an old post by mistake during summer vacation. Who had the phone last?',
    'Someone liked an old post by mistake when everyone was hungry. What was your last notification?',
    'Someone liked an old post by mistake when the lights went off. Who started the drama?',
    'Someone liked an old post by mistake while everyone was distracted. Why should we believe you did not post it?',
    'Someone liked an old post by mistake while music was playing. Who sent the message?',
    'Someone liked an old post by mistake while people were taking photos. Why should we believe you did not post it?',
    'Someone muted the group chat secretly after the group split up. Why should we believe you did not post it?',
    'Someone muted the group chat secretly after the group split up. Why were you laughing?',
    'Someone muted the group chat secretly before everyone noticed. What did you see on the screen?',
    'Someone muted the group chat secretly before the argument started. Why were you laughing?',
    'Someone replied from the wrong account after someone shouted. Who had the phone last?',
    'Someone replied from the wrong account after the group split up. What screenshot did you see?',
    'Someone replied from the wrong account before the argument started. Who was acting too quiet?',
    'Someone replied from the wrong account during game night. Who sent the message?',
    'Someone replied from the wrong account while music was playing. Who sent the message?',
    'Someone sent a risky message from another phone during summer vacation. Why were you laughing?',
    'Someone sent a risky message from another phone when the lights went off. What screenshot did you see?',
    'Someone sent a risky message from another phone when the lights went off. Why were you holding someone\'s phone?',
    'Someone sent a risky message from another phone when the room became chaotic. Who was acting too quiet?',
    'Someone sent a risky message from another phone while everyone was distracted. Who started the drama?',
    'Someone started drama in the comments after the group split up. Why should we believe you did not post it?',
    'Someone started drama in the comments before the argument started. Who had the phone last?',
    'Someone started drama in the comments during a family gathering. Who sent the message?',
    'Someone started drama in the comments during a family gathering. Why should we believe you did not post it?',
    'Someone started drama in the comments during game night. Who sent the message?',
    'Someone started drama in the comments during summer vacation. Why were you holding someone\'s phone?',
    'Someone started drama in the comments when the lights went off. Why should we believe you did not post it?',
    'Someone started drama in the comments while people were taking photos. Who was acting too quiet?',
  ],

  'Family Crime': [
    'A cousin ate from another cousin\'s plate before the argument started. Why were you hiding?',
    'A cousin ate from another cousin\'s plate during the funniest moment. Who started the confusion?',
    'A cousin ate from another cousin\'s plate during the funniest moment. Why were you laughing quietly?',
    'A cousin ate from another cousin\'s plate when everyone was hungry. Who looked guilty?',
    'A cousin ate from another cousin\'s plate when the lights went off. Why should the family trust you?',
    'A cousin ate from another cousin\'s plate while everyone was distracted. What did you tell the elders?',
    'A cousin ate from another cousin\'s plate while music was playing. Who started the confusion?',
    'A cousin stole another cousin\'s charger while music was playing. What did you tell the elders?',
    'A family function plan was changed secretly after the group split up. Who looked guilty?',
    'A family function plan was changed secretly during a family gathering. What did you tell the elders?',
    'A family function plan was changed secretly during summer vacation. Who got blamed first?',
    'A family function plan was changed secretly during summer vacation. Why were you hiding?',
    'A family function plan was changed secretly during the funniest moment. What did you hear?',
    'A family function plan was changed secretly during the funniest moment. Who looked guilty?',
    'A family function plan was changed secretly during the funniest moment. Why should the family trust you?',
    'A family function plan was changed secretly when the lights went off. Which cousin was with you?',
    'A family function plan was changed secretly when the room became chaotic. Who looked guilty?',
    'A family function plan was changed secretly while music was playing. What did you hear?',
    'A family function plan was changed secretly while people were taking photos. Who started the confusion?',
    'A family function plan was changed secretly while people were taking photos. Why should the family trust you?',
    'A family secret was almost revealed during summer vacation. What did you tell the elders?',
    'A family secret was almost revealed when everyone was hungry. Who looked guilty?',
    'A family secret was almost revealed while people were taking photos. Who started the confusion?',
    'A secret nickname got exposed after the group split up. What excuse did you use?',
    'A secret nickname got exposed after the group split up. Which cousin was with you?',
    'A secret nickname got exposed before the argument started. Why were you hiding?',
    'A secret nickname got exposed while people were taking photos. What excuse did you use?',
    'Someone blamed a cousin for a mess after the group split up. Who started the confusion?',
    'Someone blamed a cousin for a mess before everyone noticed. What did you hear?',
    'Someone blamed a cousin for a mess before everyone noticed. What excuse did you use?',
    'Someone blamed a cousin for a mess before everyone noticed. Who started the confusion?',
    'Someone blamed a cousin for a mess while people were taking photos. Why were you hiding?',
    'Someone copied another cousin\'s excuse after someone shouted. Which cousin was with you?',
    'Someone copied another cousin\'s excuse after someone shouted. Who looked guilty?',
    'Someone copied another cousin\'s excuse during game night. What excuse did you use?',
    'Someone copied another cousin\'s excuse during summer vacation. What did you hear?',
    'Someone copied another cousin\'s excuse during summer vacation. Why were you laughing quietly?',
    'Someone copied another cousin\'s excuse when the lights went off. Which cousin was with you?',
    'Someone copied another cousin\'s excuse while everyone was distracted. Why were you hiding?',
    'Someone copied another cousin\'s excuse while people were taking photos. What did you hear?',
    'Someone escaped family photo time before the argument started. What did you hear?',
    'Someone escaped family photo time before the argument started. What excuse did you use?',
    'Someone escaped family photo time during a family gathering. What did you hear?',
    'Someone escaped family photo time when everyone was hungry. Why should the family trust you?',
    'Someone hid during cleanup time when the lights went off. Who looked guilty?',
    'Someone hid during cleanup time while people were taking photos. Who looked guilty?',
    'Someone started a fake argument for fun after someone shouted. What did you tell the elders?',
    'Someone started a fake argument for fun after the group split up. What did you hear?',
    'Someone started a fake argument for fun after the group split up. Why were you laughing quietly?',
    'Someone started a fake argument for fun before the argument started. Why were you laughing quietly?',
    'Someone started a fake argument for fun during a family gathering. Who looked guilty?',
    'Someone started a fake argument for fun when the lights went off. Who got blamed first?',
    'Someone switched teams during a family game during game night. What excuse did you use?',
    'Someone switched teams during a family game during game night. Why were you laughing quietly?',
    'Someone switched teams during a family game during summer vacation. Who started the confusion?',
    'Someone switched teams during a family game during the funniest moment. Why should the family trust you?',
    'Someone switched teams during a family game when the room became chaotic. Who started the confusion?',
    'Someone switched teams during a family game while people were taking photos. Why should the family trust you?',
    'Someone told parents half the truth during game night. What did you hear?',
    'Someone told parents half the truth during summer vacation. Why should the family trust you?',
    'Someone told parents half the truth when everyone was hungry. What excuse did you use?',
    'Someone told parents half the truth when the lights went off. What did you hear?',
    'Someone told parents half the truth while music was playing. Why were you hiding?',
    'Someone told parents half the truth while people were taking photos. Why were you laughing quietly?',
    'Someone took the best seat after the group split up. What excuse did you use?',
    'Someone took the best seat at midnight. Why were you laughing quietly?',
    'Someone took the best seat during summer vacation. Who got blamed first?',
    'The family WhatsApp group got confused before the argument started. Who looked guilty?',
    'The family WhatsApp group got confused during a family gathering. What excuse did you use?',
    'The family WhatsApp group got confused during summer vacation. What did you hear?',
    'The family WhatsApp group got confused when the room became chaotic. Why should the family trust you?',
    'The family WhatsApp group got confused while everyone was distracted. Why were you laughing quietly?',
    'The younger sibling started crying mysteriously after someone shouted. Which cousin was with you?',
    'The younger sibling started crying mysteriously when the lights went off. Who started the confusion?',
    'The younger sibling started crying mysteriously while everyone was distracted. What excuse did you use?',
  ],
};