// IMPOSTOR MODE - COMPLETE WORD DATABASE
// 24 Categories × 100 words each
// Age Group: 18-25

class ImpostorCategoriesData {
  static const Map<String, List<String>> categories = {
    'Gaming': [
      'Minecraft', 'Valorant', 'PUBG', 'Aim Assist', 'Controller', 'Keyboard',
      'Mouse', 'Headset', 'Streaming', 'Twitch', 'Discord', 'Framerate',
      'Graphics Card', 'Monitor', 'Motherboard', 'RAM', 'SSD', 'GPU',
      'CPU', 'Gaming Chair', 'Battlepass', 'Skin', 'Cosmetic', 'Loot',
      'Respawn', 'Killstreak', 'Clutch', 'Toxic', 'GG', 'Noob',
      'Pro Player', 'Speedrun', 'Glitch', 'Exploit', 'Mod', 'Server',
      'Ping', 'Lag', 'FPS', 'Resolution', 'Settings', 'Sensitivity',
      'Crosshair', 'Spray', 'Recoil', 'Weapon', 'Loadout', 'Campaign',
      'Multiplayer', 'Ranked', 'Casual', 'Tournament', 'Esports', 'Prize Pool',
      'Sponsorship', 'Streamer', 'Content Creator', 'Subscriber', 'Viewer', 'Chat',
      'Meta', 'Counter', 'Strategy', 'Tactics', 'Teamwork', 'Communication',
      'Callout', 'Map', 'Position', 'Objective', 'Capture', 'Defend',
      'Attack', 'Support', 'DPS', 'Tank', 'Healer', 'Buffer',
      'Console', 'PC', 'PlayStation', 'Xbox', 'Nintendo', 'Switch',
      'Mobile', 'App', 'Controller Support', 'Cross-play', 'Solo Queue', 'Team',
      'Clan', 'Guild', 'Raid', 'Dungeon', 'Boss', 'Loot Drop',
      'Inventory', 'Backpack', 'Loadout Screen', 'Settings', 'Graphics', 'Audio',
      'Volume', 'Mute', 'Push To Talk', 'Voice Chat', 'Text Chat', 'Whisper',
      'Party', 'Squad', 'Matchmaking', 'Rank', 'Tier', 'ELO',
      'Rating', 'Stats', 'Win Rate', 'Kill Death Ratio', 'Achievement', 'Trophy'
    ],
    'TikTok & Memes': [
      'FYP', 'For You Page', 'Duet', 'Stitch', 'Trending', 'Viral',
      'Sound', 'Audio Clip', 'Transition', 'Filter', 'Effect', 'Green Screen',
      'Voiceover', 'POV', 'Skit', 'Lip Sync', 'Dance Challenge', 'Trend',
      'Hashtag', 'Viral Dance', 'Choreography', 'Entertainment', 'Comedy', 'Drama',
      'Storytelling', 'Mukbang', 'ASMR', 'Unboxing', 'Haul', 'Reaction',
      'Review', 'Tutorial', 'DIY', 'Transformation', 'Makeup', 'Fashion',
      'Outfit', 'Style', 'Aesthetic', 'Vibe', 'Mood', 'Edit',
      'Video Editing', 'Capcut', 'Adobe', 'Speed Ramp', 'Transition Effect', 'Text Overlay',
      'Meme', 'Funny', 'Joke', 'Sarcasm', 'Wit', 'Humor',
      'Comment Section', 'Engagement', 'Like', 'Share', 'Save', 'Repost',
      'Account', 'Creator Fund', 'Monetization', 'Sponsorship', 'Brand Deal', 'Collaboration',
      'Collab', 'Duet War', 'Stitch Battle', 'Comment Fight', 'Tea Spill', 'Drama Tea',
      'Gossip', 'Call Out', 'Clap Back', 'Roast', 'Dis Track', 'Diss',
      'Beef', 'Cancel', 'Canceled', 'Apology Video', 'Redemption Arc', 'Come Back',
      'Influencer', 'Celebrity', 'Personality', 'Content Creator', 'Streamer', 'Vlogger',
      'Youtuber', 'Instagrammer', 'E-Girl', 'E-Boy', 'Simp', 'Simping',
      'Thirst Trap', 'Selfie', 'Mirror Selfie', 'Bathroom Selfie', 'Gym Selfie', 'Car Selfie',
      'Ootd', 'Outfit of the Day', 'Fit Check', 'Drip', 'Fit', 'Flex',
      'Ice Breaker', 'Ice Cold', 'Hot Take', 'Scorching Take', 'Spicy', 'Mild',
      'Ratio', 'Quote Tweet', 'Reply', 'Thread', 'Rant', 'Venting'
    ],
    'Foods': [
      'Pizza', 'Sushi', 'Taco', 'Burger', 'Hotdog', 'Sandwich',
      'Pasta', 'Ramen', 'Pho', 'Biryani', 'Curry', 'Stir Fry',
      'Fried Rice', 'Noodles', 'Dumplings', 'Gyoza', 'Spring Rolls', 'Pad Thai',
      'Burritos', 'Quesadillas', 'Enchiladas', 'Nachos', 'Tacos', 'Fajitas',
      'Kebab', 'Shawarma', 'Falafel', 'Hummus', 'Pita Bread', 'Flatbread',
      'Bagel', 'Donut', 'Croissant', 'Pastry', 'Muffin', 'Brownie',
      'Cookie', 'Cake', 'Cheesecake', 'Tiramisu', 'Chocolate', 'Candy',
      'Ice Cream', 'Gelato', 'Sorbet', 'Popsicle', 'Slurpee', 'Smoothie',
      'Milkshake', 'Protein Shake', 'Coffee', 'Espresso', 'Latte', 'Cappuccino',
      'Iced Coffee', 'Cold Brew', 'Bubble Tea', 'Boba', 'Tea', 'Green Tea',
      'Matcha', 'Juice', 'Smoothie Bowl', 'Acai Bowl', 'Granola', 'Yogurt',
      'Parfait', 'Cereal', 'Oatmeal', 'Pancakes', 'Waffles', 'French Toast',
      'Eggs', 'Scrambled', 'Fried', 'Boiled', 'Omelet', 'Breakfast',
      'Bacon', 'Sausage', 'Ham', 'Salmon', 'Tuna', 'Chicken',
      'Steak', 'Beef', 'Pork', 'Lamb', 'Turkey', 'Vegetarian',
      'Vegan', 'Tofu', 'Tempeh', 'Seitan', 'Lentils', 'Beans',
      'Chickpeas', 'Rice', 'Quinoa', 'Couscous', 'Potatoes', 'Sweet Potato',
      'Broccoli', 'Spinach', 'Lettuce', 'Tomato', 'Cucumber', 'Carrot',
      'Bell Pepper', 'Onion', 'Garlic', 'Ginger', 'Mushroom', 'Cheese',
      'Butter', 'Milk', 'Cream', 'Oil', 'Spice', 'Salt'
    ],
    'Brands & Sneakers': [
      'Nike', 'Adidas', 'Puma', 'Reebok', 'New Balance', 'Converse',
      'Vans', 'Jordan', 'Air Force', 'Yeezy', 'Supreme', 'Stüssy',
      'Carhartt', 'Dickies', 'Timberland', 'Doc Martens', 'Crocs', 'Heely',
      'Sketchers', 'ASICS', 'Mizuno', 'Saucony', 'Brooks', 'Salomon',
      'Merrell', 'Keen', 'Sorel', 'UGG', 'Birkenstock', 'Clarks',
      'Gucci', 'Louis Vuitton', 'Prada', 'Chanel', 'Dior', 'Versace',
      'Balenciaga', 'Givenchy', 'Fendi', 'Hermès', 'Coach', 'Michael Kors',
      'Burberry', 'Tommy Hilfiger', 'Ralph Lauren', 'Lacoste', 'Polo', 'Izod',
      'Hollister', 'Abercrombie', 'American Eagle', 'Gap', 'H&M', 'Uniqlo',
      'Forever 21', 'Zara', 'Mango', 'ASOS', 'Urban Outfitters', 'Target',
      'Walmart', 'Costco', 'Amazon', 'eBay', 'Grailed', 'Depop',
      'Vestiaire Collective', 'The RealReal', 'Goat', 'Sneaker Politics', 'Foot Locker', 'Foot Action',
      'Champs Sports', 'Finish Line', 'JD Sports', 'Size', 'SNKRS', 'Confirmed',
      'Shoe Palace', 'Foot District', 'Offspring', 'Size Exchange', 'Sneaker Con', 'Hype Beast',
      'Hypebeast', 'Grail', 'Cop', 'Drop', 'Release', 'Restock',
      'Collaboration', 'Collab', 'Limited Edition', 'Exclusive', 'Rare', 'Vintage',
      'Deadstock', 'VNDS', 'Worn', 'Condition', 'Quality', 'Authentic',
      'Fake', 'Replica', 'Counterfeit', 'Real Check', 'Legit Check', 'Authentication',
      'Price Tag', 'MSRP', 'Resale', 'Resell', 'Flip', 'Profit',
      'Sneaker Head', 'Collector', 'Hype Beast', 'Flex', 'Drip', 'Fit'
    ],
    'Movies & Shows': [
      'Marvel', 'Avengers', 'Iron Man', 'Captain America', 'Thor', 'Hulk',
      'Spider-Man', 'Black Widow', 'Hawkeye', 'Vision', 'Scarlet Witch', 'Black Panther',
      'Doctor Strange', 'Ant-Man', 'Captain Marvel', 'Shang-Chi', 'Eternals', 'Guardians',
      'Interstellar', 'Inception', 'The Dark Knight', 'Joker', 'Batman', 'Superman',
      'Wonder Woman', 'Aquaman', 'Flash', 'Green Lantern', 'Justice League', 'Suicide Squad',
      'The Matrix', 'The Terminator', 'Avatar', 'Alien', 'Predator', 'The Sixth Sense',
      'Shutter Island', 'Prestige', 'Fight Club', 'Parasite', 'Train to Busan', 'Squid Game',
      'Stranger Things', 'Breaking Bad', 'The Office', 'Friends', 'How I Met Your Mother', 'The Crown',
      'Game of Thrones', 'House of Dragons', 'The Witcher', 'Wednesday', 'Euphoria', 'The Mandalorian',
      'Peaky Blinders', 'Ozark', 'Narcos', 'The Money Heist', 'Godless', 'Lucifer',
      'Supernatural', 'The Vampire Diaries', 'The Originals', 'Legacies', 'Riverdale', 'Sabrina',
      'Wednesday', 'The Haunting', 'Midnight Club', 'You', 'Mindhunter', 'Dark',
      'Glee', 'Wheatley', 'Modern Family', 'Brooklyn Nine-Nine', 'The Good Place', 'Schitts Creek',
      'Fleabag', 'Russian Doll', 'Master of None', 'Aziz Ansari', 'Dave', 'Insecure',
      'Issa Rae', 'The Ultimatum', 'Love Is Blind', 'Floor is Lava', 'Survivor', 'Bachelor',
      'Reality TV', 'Documentary', 'Thriller', 'Horror', 'Comedy', 'Drama',
      'Action', 'Adventure', 'Fantasy', 'Sci-Fi', 'Romance', 'Animation',
      'Anime', 'Manga', 'K-Drama', 'K-Pop', 'Kdrama', 'Turkish Series',
      'Netflix', 'Disney Plus', 'Amazon Prime', 'Hulu', 'HBO Max', 'Paramount Plus',
      'Streaming', 'Binge', 'Episode', 'Season', 'Finale', 'Cliffhanger'
    ],
    'School Life': [
      'Homework', 'Assignment', 'Project', 'Essay', 'Exam', 'Quiz',
      'Test', 'Grade', 'GPA', 'Transcript', 'Report Card', 'Parent-Teacher Conference',
      'Detention', 'Suspension', 'Expulsion', 'Discipline', 'Hall Monitor', 'Cafeteria',
      'Lunch', 'Lunch Money', 'Lunch Lady', 'School Lunch', 'Vending Machine', 'Snack',
      'Class', 'Classroom', 'Lecture', 'Note Taking', 'Studious', 'Nerdy',
      'Popular', 'Jock', 'Cheerleader', 'Band', 'Orchestra', 'Drama Club',
      'Sports', 'Basketball', 'Football', 'Soccer', 'Volleyball', 'Tennis',
      'Track', 'Cross Country', 'Swimming', 'Gymnastics', 'Cheerleading', 'Dance Team',
      'Prom', 'Homecoming', 'Dance', 'Winter Formal', 'Spring Fling', 'After Party',
      'Locker', 'Combination Lock', 'Hallway', 'Passing Period', 'Tardy', 'Absent',
      'Present', 'Attendance', 'Absence Note', 'Excuse', 'Sick Day', 'Skipping Class',
      'Truancy', 'School Spirit', 'School Colors', 'Mascot', 'Banner', 'Trophy Case',
      'Principal', 'Principal\'s Office', 'Dean', 'Teacher\'s Pet', 'Teacher', 'Substitute',
      'Yearbook', 'Yearbook Committee', 'School Newspaper', 'School Photo', 'Senior Photo', 'Class Photo',
      'Locker Decoration', 'Locker Room', 'Gym Class', 'Physical Education', 'PE', 'Coach',
      'Whistle', 'Stopwatch', 'Scoreboard', 'Basketball Court', 'Football Field', 'Track',
      'Tennis Court', 'Swimming Pool', 'Gymnasium', 'Bleachers', 'Spectator', 'Fan',
      'School Bus', 'Bus Stop', 'Bus Driver', 'Rider', 'Carpool', 'Driver',
      'Lunch Box', 'Thermos', 'Water Bottle', 'Backpack', 'Locker', 'Notebook',
      'Pencil', 'Pen', 'Binder', 'Folder', 'Highlighter', 'Eraser'
    ],
    'Countries & Cities': [
      'America', 'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
      'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin',
      'Tokyo', 'Kyoto', 'Osaka', 'Hiroshima', 'Mount Fuji', 'Japan',
      'Seoul', 'Busan', 'Incheon', 'Daegu', 'South Korea', 'Korea',
      'Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'China', 'Great Wall',
      'New Delhi', 'Mumbai', 'Bangalore', 'Taj Mahal', 'India', 'Goa',
      'Paris', 'London', 'Berlin', 'Amsterdam', 'Rome', 'Barcelona',
      'Madrid', 'Venice', 'Florence', 'Vienna', 'Prague', 'Budapest',
      'Moscow', 'Saint Petersburg', 'Istanbul', 'Cairo', 'Dubai', 'Abu Dhabi',
      'Bangkok', 'Phuket', 'Vietnam', 'Hanoi', 'Ho Chi Minh', 'Cambodia',
      'Singapore', 'Malaysia', 'Kuala Lumpur', 'Indonesia', 'Bali', 'Jakarta',
      'Philippines', 'Manila', 'Cebu', 'Boracay', 'Thailand', 'Chiang Mai',
      'Mexico', 'Mexico City', 'Cancun', 'Playa del Carmen', 'Cabo', 'Puerto Vallarta',
      'Brazil', 'Rio de Janeiro', 'São Paulo', 'Salvador', 'Brasília', 'Amazon',
      'Argentina', 'Buenos Aires', 'Mendoza', 'Córdoba', 'La Plata', 'Mar del Plata',
      'Canada', 'Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa',
      'Australia', 'Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Gold Coast',
      'New Zealand', 'Auckland', 'Christchurch', 'Wellington', 'Rotorua', 'Queenstown',
      'South Africa', 'Cape Town', 'Johannesburg', 'Durban', 'Pretoria', 'Safari',
      'Egypt', 'Giza', 'Luxor', 'Aswan', 'Pyramids', 'Nile'
    ],
    'Family Scenarios': [
      'Mom', 'Dad', 'Mother', 'Father', 'Parent', 'Parents',
      'Brother', 'Sister', 'Sibling', 'Siblings', 'Cousin', 'Cousins',
      'Aunt', 'Uncle', 'Grandma', 'Grandpa', 'Grandmother', 'Grandfather',
      'In-Laws', 'Spouse', 'Husband', 'Wife', 'Boyfriend', 'Girlfriend',
      'Son', 'Daughter', 'Child', 'Children', 'Kid', 'Kids',
      'Baby', 'Toddler', 'Infant', 'Newborn', 'Pregnancy', 'Pregnant',
      'Family Dinner', 'Family Meeting', 'Family Trip', 'Family Vacation', 'Road Trip', 'Camping',
      'Thanksgiving', 'Christmas', 'Easter', 'Hanukkah', 'Passover', 'Holiday',
      'Birthday Party', 'Birthday Cake', 'Birthday Candles', 'Make a Wish', 'Blow Out', 'Present',
      'Gift', 'Wrapping', 'Ribbon', 'Bow', 'Card', 'Thank You',
      'Reunion', 'Family Reunion', 'Potluck', 'Barbecue', 'BBQ', 'Picnic',
      'Conversation', 'Argument', 'Fight', 'Disagreement', 'Yelling', 'Shouting',
      'Quiet Time', 'Silent Treatment', 'Tension', 'Drama', 'Conflict', 'Resolution',
      'Forgiveness', 'Apology', 'Sorry', 'Makeup', 'Hug', 'Kiss',
      'Love', 'Care', 'Support', 'Trust', 'Loyalty', 'Bond',
      'Embarrassing Moment', 'Embarrassing Story', 'Childhood Memory', 'Old Photo', 'Album', 'Scrapbook',
      'Embarrassment', 'Shame', 'Red Face', 'Hide', 'Disappear', 'Humiliation',
      'Joke', 'Funny Story', 'Laugh', 'Giggle', 'Chuckle', 'Humor',
      'Chore', 'Cleaning', 'Dishes', 'Laundry', 'Homework Help', 'Tutoring',
      'School Play', 'School Concert', 'School Event', 'Pride', 'Achievement', 'Award'
    ],
    'Music': [
      'Rock', 'Pop', 'Hip-Hop', 'Rap', 'Country', 'Jazz',
      'Blues', 'Classical', 'Opera', 'EDM', 'Electronic', 'Dubstep',
      'Trap', 'Drill', 'Grime', 'Reggae', 'Reggaeton', 'Latin',
      'R&B', 'Soul', 'Gospel', 'Indie', 'Alternative', 'Punk',
      'Metal', 'Heavy Metal', 'Death Metal', 'Black Metal', 'Thrash Metal', 'Power Metal',
      'Folk', 'Acoustic', 'Singer-Songwriter', 'Ballad', 'Ambient', 'Lo-Fi',
      'K-Pop', 'J-Pop', 'C-Pop', 'Anime Opening', 'Soundtrack', 'OST',
      'Album', 'EP', 'Single', 'Track', 'Song', 'Artist',
      'Band', 'Group', 'Vocalist', 'Singer', 'Rapper', 'Producer',
      'DJ', 'Beat', 'Rhythm', 'Melody', 'Harmony', 'Chord',
      'Guitar', 'Bass', 'Drums', 'Piano', 'Keyboard', 'Violin',
      'Saxophone', 'Trumpet', 'Flute', 'Synthesizer', 'Turntable', 'Microphone',
      'Studio', 'Recording', 'Engineer', 'Mixing', 'Mastering', 'Production',
      'Lyrics', 'Verse', 'Chorus', 'Bridge', 'Hook', 'Rap Verse',
      'Freestyle', 'Cipher', 'Cipher Session', 'Spitting Bars', 'Flow', 'Rhyme',
      'Concert', 'Live Performance', 'Festival', 'Tour', 'World Tour', 'Venue',
      'Ticket', 'Front Row', 'Mosh Pit', 'Stage Dive', 'Crowd Surfing', 'Chanting',
      'Spotify', 'Apple Music', 'YouTube Music', 'SoundCloud', 'Tidal', 'Bandcamp',
      'Playlist', 'Favorite', 'Like', 'Share', 'Follow', 'Recommendation',
      'Award', 'Grammy', 'Billboard', 'Chart', 'Number One', 'Hit Song'
    ],
    'Superheroes & Villains': [
      'Superman', 'Batman', 'Wonder Woman', 'The Flash', 'Aquaman', 'Green Lantern',
      'Hawkeye', 'Black Widow', 'Iron Man', 'Captain America', 'Thor', 'Hulk',
      'Spider-Man', 'Doctor Strange', 'Black Panther', 'Shang-Chi', 'Captain Marvel', 'Scarlet Witch',
      'Ant-Man', 'Wasp', 'Vision', 'Falcon', 'War Machine', 'Guardians',
      'Star-Lord', 'Rocket', 'Groot', 'Drax', 'Gamora', 'Nebula',
      'X-Men', 'Wolverine', 'Professor X', 'Cyclops', 'Storm', 'Phoenix',
      'Emma Frost', 'Beast', 'Nightcrawler', 'Magneto', 'Mystique', 'Rogue',
      'Deadpool', 'Daredevil', 'Luke Cage', 'Iron Fist', 'Jessica Jones', 'Punisher',
      'Silver Surfer', 'Fantastic Four', 'Mr. Fantastic', 'Invisible Woman', 'Human Torch', 'The Thing',
      'Joker', 'Penguin', 'Two-Face', 'Scarecrow', 'Riddler', 'Poison Ivy',
      'Harley Quinn', 'Catwoman', 'Bane', 'Killer Croc', 'Lex Luthor', 'Doomsday',
      'Thanos', 'Loki', 'Ultron', 'Kang', 'Darkseid', 'Apocalypse',
      'Magneto', 'Doctor Doom', 'Galactus', 'Annihilus', 'Dormammu', 'Mephisto',
      'Hela', 'Steppenwolf', 'Brainiac', 'Grodd', 'Sinestro', 'Manhunters',
      'Scarlet Witch', 'Venom', 'Carnage', 'Sandman', 'Doc Ock', 'Green Goblin',
      'Vulture', 'Mysterio', 'Electro', 'Lizard', 'Kraven', 'Hydro-Man',
      'Costume', 'Mask', 'Cape', 'Suit', 'Utility Belt', 'Logo',
      'Powers', 'Superpower', 'Strength', 'Speed', 'Flight', 'Invisibility',
      'Teleportation', 'Mind Control', 'Time Travel', 'Immortality', 'Healing Factor', 'Transformation',
      'Villain', 'Heroism', 'Justice', 'Evil', 'Good', 'Moral'
    ],
    'Sports': [
      'Football', 'Basketball', 'Soccer', 'Baseball', 'Hockey', 'Tennis',
      'Golf', 'Volleyball', 'Badminton', 'Ping Pong', 'Table Tennis', 'Squash',
      'Rugby', 'American Football', 'Cricket', 'Lacrosse', 'Lacrosse Stick', 'Polo',
      'Skiing', 'Snowboarding', 'Ice Skating', 'Figure Skating', 'Speed Skating', 'Cross Country',
      'Marathon', 'Half Marathon', ' 5K', '10K', 'Running', 'Jogging',
      'Walking', 'Hiking', 'Rock Climbing', 'Bouldering', 'Rappelling', 'Base Jumping',
      'Skydiving', 'Paragliding', 'Hang Gliding', 'Windsurfing', 'Surfing', 'Kiteboarding',
      'Swimming', 'Diving', 'Synchronized Swimming', 'Water Polo', 'Kayaking', 'Canoeing',
      'Rowing', 'Sailing', 'Boating', 'Jet Skiing', 'White Water Rafting', 'Tubing',
      'Gymnastics', 'Rhythmic Gymnastics', 'Trampoline', 'Parkour', 'Freerunning', 'Skateboarding',
      'Snowboarding', 'Skateboard', 'Roller Skating', 'Rollerblade', 'BMX', 'Mountain Biking',
      'Cycling', 'Road Biking', 'Triathlon', 'Pentathlon', 'Decathlon', 'Biathlon',
      'Archery', 'Shooting', 'Fencing', 'Martial Arts', 'Karate', 'Taekwondo',
      'Judo', 'Jiu-Jitsu', 'Wrestling', 'Boxing', 'Muay Thai', 'Kickboxing',
      'Gymnastics', 'Yoga', 'Pilates', 'CrossFit', 'Weight Lifting', 'Powerlifting',
      'Bodybuilding', 'Crossfit', 'Strength Training', 'Conditioning', 'Endurance', 'Flexibility',
      'Stadium', 'Arena', 'Field', 'Court', 'Gym', 'Fitness Center',
      'Coach', 'Trainer', 'Athlete', 'Professional', 'Amateur', 'Olympic',
      'Medal', 'Gold Medal', 'Silver Medal', 'Bronze Medal', 'Trophy', 'Championship',
      'Score', 'Point', 'Win', 'Loss', 'Draw', 'Tie'
    ],
    'Social Media': [
      'Facebook', 'Instagram', 'Twitter', 'X', 'TikTok', 'Snapchat',
      'Pinterest', 'Reddit', 'Quora', 'Tumblr', 'Medium', 'Substack',
      'LinkedIn', 'WeChat', 'WhatsApp', 'Telegram', 'Discord', 'Slack',
      'Post', 'Story', 'Reel', 'Short', 'Tweet', 'Thread',
      'Comment', 'Reply', 'Like', 'Share', 'Retweet', 'Quote Tweet',
      'Tag', 'Mention', 'Hashtag', 'Hashtag Trend', 'Trending', 'Viral',
      'Followers', 'Following', 'Friends', 'Connection', 'Subscriber', 'Subscription',
      'Bio', 'Profile', 'Avatar', 'Cover Photo', 'Display Name', 'Username',
      'Handle', 'Verification Badge', 'Blue Check', 'Verified', 'Creator Badge', 'Influencer Badge',
      'Notification', 'Alert', 'Ping', 'Message', 'DM', 'Direct Message',
      'Inbox', 'Notification Center', 'Feed', 'Timeline', 'News Feed', 'Explore',
      'Discover', 'Recommended', 'Suggested', 'Algorithm', 'Personalised', 'Curated',
      'Filter', 'Photo Filter', 'Video Filter', 'AR Filter', 'Face Filter', 'Lens',
      'Story Filter', 'Dog Filter', 'Bunny Filter', 'Makeup Filter', 'Beauty Filter', 'Effect',
      'Edit', 'Delete', 'Archive', 'Save', 'Bookmark', 'Collection',
      'Highlight', 'Sticker', 'Poll', 'Quiz', 'Survey', 'Question',
      'Live Stream', 'Live Video', 'Go Live', 'Streaming', 'Broadcast', 'Premiere',
      'Upload', 'Download', 'Share', 'Save', 'Screenshot', 'Screen Record',
      'Privacy', 'Private Account', 'Public Account', 'Block', 'Unblock', 'Report',
      'Ban', 'Suspended', 'Account Deactivated', 'Account Deleted', 'Mute', 'Unmute'
    ],
    'Science & School Subjects': [
      'Biology', 'Chemistry', 'Physics', 'Math', 'Algebra', 'Geometry',
      'Calculus', 'Trigonometry', 'Statistics', 'Probability', 'Literature', 'History',
      'Geography', 'Economics', 'Psychology', 'Sociology', 'Anthropology', 'Philosophy',
      'English', 'Spanish', 'French', 'German', 'Mandarin', 'Japanese',
      'Environmental Science', 'Ecology', 'Marine Biology', 'Anatomy', 'Physiology', 'Microbiology',
      'Genetics', 'Evolution', 'Cell Biology', 'Botany', 'Zoology', 'Entomology',
      'Astronomy', 'Astrophysics', 'Cosmology', 'Meteorology', 'Geology', 'Mineralogy',
      'Paleontology', 'Seismology', 'Oceanography', 'Organic Chemistry', 'Inorganic Chemistry', 'Biochemistry',
      'Physical Chemistry', 'Analytical Chemistry', 'Thermodynamics', 'Mechanics', 'Electromagnetism', 'Optics',
      'Quantum Physics', 'Relativity', 'Nuclear Physics', 'Particle Physics', 'Acoustics', 'Wave',
      'Atom', 'Molecule', 'Element', 'Compound', 'Reaction', 'Catalyst',
      'Photosynthesis', 'Respiration', 'Digestion', 'Circulation', 'Nervous System', 'Immune System',
      'DNA', 'RNA', 'Gene', 'Protein', 'Enzyme', 'Antibody',
      'Mitochondria', 'Chloroplast', 'Ribosome', 'Cell Membrane', 'Nucleus', 'Cytoplasm',
      'Osmosis', 'Diffusion', 'Active Transport', 'Passive Transport', 'Homeostasis', 'Metabolism',
      'Photosynthesis', 'Fermentation', 'Glycolysis', 'Krebs Cycle', 'Electron Transport', 'ATP',
      'Carbohydrate', 'Protein', 'Lipid', 'Nucleic Acid', 'Vitamin', 'Mineral',
      'Fossil', 'Extinction', 'Mutation', 'Natural Selection', 'Adaptation', 'Species',
      'Ecosystem', 'Biome', 'Habitat', 'Niche', 'Food Chain', 'Food Web',
      'Energy Transfer', 'Carbon Cycle', 'Nitrogen Cycle', 'Water Cycle', 'Phosphorus Cycle', 'Climate'
    ],
    'Random Objects': [
      'Pen', 'Pencil', 'Paper', 'Notebook', 'Binder', 'Folder',
      'Stapler', 'Tape', 'Scissors', 'Glue', 'Eraser', 'Highlighter',
      'Marker', 'Crayon', 'Colored Pencil', 'Paintbrush', 'Palette', 'Canvas',
      'Easel', 'Sketchpad', 'Drawing Board', 'Ruler', 'Protractor', 'Compass',
      'Calculator', 'Clock', 'Watch', 'Timer', 'Stopwatch', 'Alarm',
      'Phone', 'Mobile Phone', 'Smartphone', 'Tablet', 'Laptop', 'Computer',
      'Monitor', 'Keyboard', 'Mouse', 'Headphones', 'Earbuds', 'Speaker',
      'Microphone', 'Camera', 'Video Camera', 'Photo Camera', 'Tripod', 'Selfie Stick',
      'Remote Control', 'Charger', 'Cable', 'Wire', 'Cord', 'Adapter',
      'Battery', 'Power Bank', 'Extension Cord', 'Outlet', 'Switch', 'Light Bulb',
      'Flashlight', 'Candle', 'Lantern', 'Lamp', 'Chandelier', 'Ceiling Fan',
      'Door', 'Window', 'Wall', 'Floor', 'Ceiling', 'Roof',
      'Brick', 'Tile', 'Carpet', 'Rug', 'Mat', 'Doormat',
      'Shoe Rack', 'Coat Rack', 'Shelf', 'Cabinet', 'Drawer', 'Closet',
      'Bed', 'Pillow', 'Blanket', 'Sheet', 'Mattress', 'Box Spring',
      'Sofa', 'Couch', 'Chair', 'Table', 'Desk', 'Nightstand',
      'Dresser', 'Wardrobe', 'Hanger', 'Laundry Basket', 'Hamper', 'Trash Can',
      'Mirror', 'Picture Frame', 'Poster', 'Painting', 'Sculpture', 'Statue',
      'Vase', 'Pot', 'Plant', 'Flower', 'Fern', 'Cactus',
      'Picture', 'Photo', 'Decoration', 'Ornament', 'Trinket', 'Souvenir'
    ],
    'Reactions & Emotions': [
      'Happy', 'Sad', 'Angry', 'Confused', 'Surprised', 'Excited',
      'Nervous', 'Anxious', 'Scared', 'Terrified', 'Disgusted', 'Embarrassed',
      'Proud', 'Ashamed', 'Guilty', 'Relieved', 'Grateful', 'Thankful',
      'Jealous', 'Envious', 'Resentful', 'Bitter', 'Frustrated', 'Annoyed',
      'Irritated', 'Angry', 'Furious', 'Enraged', 'Calm', 'Peaceful',
      'Serene', 'Tranquil', 'Content', 'Satisfied', 'Pleased', 'Delighted',
      'Joyful', 'Cheerful', 'Optimistic', 'Hopeful', 'Inspired', 'Motivated',
      'Determined', 'Confident', 'Assured', 'Secure', 'Safe', 'Protected',
      'Loved', 'Cared For', 'Appreciated', 'Valued', 'Respected', 'Admired',
      'Lonely', 'Isolated', 'Rejected', 'Abandoned', 'Unwanted', 'Forgotten',
      'Depressed', 'Melancholy', 'Somber', 'Gloomy', 'Moody', 'Blue',
      'Amused', 'Entertained', 'Diverted', 'Laughing', 'Giggling', 'Chuckling',
      'Smiling', 'Grinning', 'Beaming', 'Radiant', 'Glowing', 'Shining',
      'Frowning', 'Pouting', 'Sulking', 'Brooding', 'Scheming', 'Planning',
      'Thinking', 'Pondering', 'Considering', 'Contemplating', 'Wondering', 'Questioning',
      'Listening', 'Hearing', 'Paying Attention', 'Focused', 'Distracted', 'Preoccupied',
      'Tired', 'Exhausted', 'Fatigued', 'Drained', 'Energized', 'Revitalized',
      'Playful', 'Mischievous', 'Cheeky', 'Impish', 'Silly', 'Goofy',
      'Serious', 'Solemn', 'Grave', 'Stern', 'Strict', 'Rigid',
      'Tender', 'Affectionate', 'Gentle', 'Compassionate', 'Kind', 'Warm'
    ],
    'Late Night / Vibe': [
      'Insomnia', 'Can\'t Sleep', 'Tired', 'Exhausted', 'Energy Drink', 'Coffee',
      'Late Night Snack', 'Midnight Snack', 'Ramen', 'Instant Noodles', 'Pizza', 'Delivery',
      'Night Owl', 'Early Bird', 'Nocturnal', 'Insomniac', '3 AM', 'Ungodly Hour',
      'Midnight', 'Witching Hour', 'Dead of Night', 'Wee Hours', 'Dawn', 'Sunrise',
      'Moonlight', 'Starlight', 'Night Sky', 'Constellations', 'Stars', 'Moon',
      'Darkness', 'Shadows', 'Silhouette', 'Glow', 'Neon', 'Lights',
      'Chill', 'Laid Back', 'Relaxed', 'Vibe', 'Good Vibes', 'Bad Vibes',
      'Atmosphere', 'Ambiance', 'Mood', 'Feeling', 'Energy', 'Aura',
      'Sunset', 'Dusk', 'Twilight', 'Golden Hour', 'Blue Hour', 'Aesthetic',
      'Calm', 'Peaceful', 'Quiet', 'Silence', 'Serenity', 'Tranquility',
      'Lofi', 'Lo-Fi Hip Hop', 'Chill Music', 'Ambient Music', 'Background Music', 'White Noise',
      'Study Music', 'Focus Music', 'Work Music', 'Homework', 'Studying', 'Productive',
      'Procrastinating', 'Procrastination', 'Scrolling', 'Mindlessly Scrolling', 'Doom Scrolling', 'Phone',
      'Social Media', 'Internet', 'Web Browsing', 'Surfing', 'Video', 'YouTube',
      'Streaming', 'Binge Watching', 'Show', 'Series', 'Episode', 'Cliffhanger',
      'Movie', 'Film', 'Documentary', 'Podcast', 'Audiobook', 'Reading',
      'Book', 'Novel', 'Graphic Novel', 'Comic', 'Manga', 'Manhwa',
      'Conversation', 'Deep Talk', 'Philosophy', 'Existential Crisis', 'Life Questions', 'Meaning',
      'Purpose', 'Dream', 'Fantasy', 'Imagination', 'Creativity', 'Art',
      'Drawing', 'Painting', 'Writing', 'Poetry', 'Journaling', 'Reflection'
    ],
    'Cousin Chaos Classics': [
      'Truth', 'Dare', 'Reveal', 'Secret', 'Confession', 'Spill Tea',
      'Gossip', 'Rumor', 'Scandal', 'Controversy', 'Drama', 'Chaos',
      'Crazy', 'Wild', 'Insane', 'Ridiculous', 'Absurd', 'Hilarious',
      'Funny', 'Laugh', 'Comedy', 'Joke', 'Prank', 'Trick',
      'Lie', 'Truth Bomb', 'Plot Twist', 'Unexpected', 'Surprise', 'Shocking',
      'Embarrassing', 'Cringe', 'Awkward', 'Uncomfortable', 'Painful', 'Humiliation',
      'Revenge', 'Payback', 'Retaliation', 'Getting Even', 'Settling Scores', 'Feud',
      'Beef', 'Rivalry', 'Competition', 'Challenge', 'Bet', 'Wager',
      'Lose', 'Lose a Bet', 'Forfeit', 'Consequence', 'Punishment', 'Penalty',
      'Stare', 'Stare Down', 'Eye Contact', 'Intimidating', 'Intense', 'Focused',
      'Laugh', 'Giggle', 'Snort', 'Burst Out Laughing', 'ROFL', 'Rolling on Floor',
      'Crying', 'Tears', 'Emotional', 'Moved', 'Touched', 'Heartfelt',
      'Hug', 'Group Hug', 'Embrace', 'Cuddle', 'Affection', 'Love',
      'Bond', 'Connection', 'Friendship', 'Bestie', 'BFF', 'Squad',
      'Group', 'Crew', 'Gang', 'Fam', 'Family', 'Found Family',
      'Party', 'Celebration', 'Get Together', 'Hangout', 'Meetup', 'Gathering',
      'Host', 'Guest', 'Invite', 'RSVP', 'Attendance', 'Show Up',
      'Late Night', 'Stay Up', 'All Nighter', 'Sleep Deprivation', 'Tired', 'Exhausted',
      'Next Morning', 'Hangover', 'Regret', 'Do It Again', 'Worth It', 'No Regrets',
      'Memories', 'Unforgettable', 'Cherish', 'Reminisce', 'Throwback', 'Classic'
    ],
    'Adulting Disasters': [
      'Bills', 'Rent', 'Mortgage', 'Taxes', 'Insurance', 'Debt',
      'Credit Card', 'Student Loan', 'Car Loan', 'Interest', 'APR', 'Late Fee',
      'Broke', 'Poor', 'Bankrupt', 'Financially Struggling', 'Living Paycheck to Paycheck', 'Overdraft',
      'Washing Machine', 'Laundry', 'Shrink', 'Stain', 'Color Bleeding', 'Fade',
      'Dishes', 'Dirty Dishes', 'Sink Full', 'Procrastination', 'Eventually', 'Moldy',
      'Cleaning', 'Messy', 'Chaos', 'Disaster Zone', 'Trashed', 'Spotless',
      'Cooking', 'Recipe', 'Burnt', 'Overcooked', 'Undercooked', 'Inedible',
      'Food Poisoning', 'Expired', 'Rotten', 'Spoiled', 'Refrigerator', 'Freezer',
      'Grocery Shopping', 'Grocery List', 'Budget', 'Splurge', 'Waste', 'Buy',
      'Sleep Schedule', 'Insomnia', 'Too Early', 'Too Late', 'Alarm', 'Oversleep',
      'Work', 'Job', 'Boss', 'Coworker', 'Meeting', 'Deadline',
      'Procrastination', 'Last Minute', 'Rushing', 'Stress', 'Panic', 'Anxiety',
      'Doctor Appointment', 'Dentist', 'Eye Doctor', 'Insurance', 'Hospital', 'Sick',
      'Medicine', 'Prescription', 'Over The Counter', 'Symptom', 'Diagnosis', 'Recovery',
      'Car', 'Broken Down', 'Flat Tire', 'Dead Battery', 'Mechanic', 'Repair',
      'Gas', 'Refuel', 'Empty Tank', 'Running Out', 'Stranded', 'AAA',
      'Apartment', 'Roommate', 'Landlord', 'Lease', 'Move Out', 'Deposit',
      'Furniture', 'Ikea', 'Assembly', 'Instructions', 'Extra Parts', 'Wrong Piece',
      'Plants', 'Succulent', 'Dead', 'Neglected', 'Forgetful', 'Care',
      'Responsibility', 'Adulting', 'Growing Up', 'Independence', 'Self Reliant', 'Maturity'
    ],
    'Nights Out Chaos': [
      'Club', 'Bar', 'Nightclub', 'Dance Floor', 'Dancing', 'DJ',
      'Music', 'Bass', 'Loud', 'Volume', 'Can\'t Hear', 'Yelling',
      'Drinks', 'Cocktail', 'Shot', 'Beer', 'Wine', 'Liquor',
      'Bartender', 'Mixologist', 'Drinking', 'Getting Drunk', 'Tipsy', 'Intoxicated',
      'Slurring', 'Stumbling', 'Falling', 'Tripping', 'Dizzy', 'Spinning',
      'Hangover', 'Morning After', 'Headache', 'Nausea', 'Regret', 'Vow Never Again',
      'Sunset', 'Sunrise', 'Night', 'Late Night', 'Early Morning', 'Wee Hours',
      'Friends', 'Squad', 'Crew', 'Crew', 'Group', 'Entourage',
      'Dress Code', 'Outfit', 'Heels', 'Casual', 'Formal', 'Nice',
      'Bouncer', 'ID Check', 'Fake ID', 'Denied', 'Not Old Enough', 'Under Age',
      'Invite', 'Plus One', 'VIP', 'Line', 'Waiting', 'Queue',
      'Bathroom Line', 'Long Wait', 'Impatient', 'Crowded', 'Full', 'Capacity',
      'Karaoke', 'Singing', 'Duet', 'Solo', 'Mic', 'Stage',
      'Photo Booth', 'Selfie', 'Group Pic', 'Drunk Pic', 'Memory', 'Social Media',
      'Games', 'Pool Table', 'Billiards', 'Darts', 'Board Games', 'Trivia',
      'Winner', 'Loser', 'Competition', 'Bet', 'Wager', 'Dare',
      'Food', 'Late Night Food', 'Taco', 'Hot Dog', 'Pizza', 'Fries',
      'Taxi', 'Uber', 'Lyft', 'Designated Driver', 'Ride Home', 'Stranded',
      'Conversation', 'Deep Talk', 'Secrets', 'Confession', 'Heart to Heart', 'Bonding',
      'Making Memories', 'Unforgettable', 'Best Night', 'Disaster', 'Chaos', 'Worth It'
    ],
    'Relationship Chaos': [
      'Date', 'Dating', 'Single', 'Relationship', 'Girlfriend', 'Boyfriend',
      'Crush', 'Love', 'In Love', 'Head Over Heels', 'Infatuated', 'Obsessed',
      'Interested', 'Attracted To', 'Flirting', 'Flirtation', 'Smooth Moves', 'Cheesy Lines',
      'First Kiss', 'Kiss', 'Making Out', 'Tongue', 'Passionate', 'Tender',
      'Butterflies', 'Nervous', 'Excited', 'Anxious', 'Heart Racing', 'Palms Sweaty',
      'Proposal', 'Engagement', 'Ring', 'Marriage', 'Wedding', 'Honeymoon',
      'Anniversary', 'Valentine\'s Day', 'Date Night', 'Romantic', 'Dinner', 'Flowers',
      'Candles', 'Roses', 'Chocolate', 'Gifts', 'Surprise', 'Thoughtful',
      'Communication', 'Talk', 'Discuss', 'Argument', 'Fight', 'Disagree',
      'Compromise', 'Understanding', 'Listen', 'Heard', 'Understood', 'Appreciated',
      'Trust', 'Loyalty', 'Faithful', 'Cheating', 'Betrayal', 'Hurt',
      'Forgiveness', 'Apology', 'Make Up', 'Reconcile', 'Second Chance', 'Moving On',
      'Breakup', 'Broke Up', 'Split', 'Ended', 'Over', 'Done',
      'Heartbreak', 'Heartbroken', 'Devastated', 'Crying', 'Sad', 'Miserable',
      'Getting Over', 'Healing', 'Recovery', 'Moving Forward', 'New Chapter', 'Fresh Start',
      'Friend Zone', 'Friend', 'Unfriend', 'Unblock', 'Reblock', 'Block Again',
      'Long Distance', 'Long Distance Relationship', 'Missing You', 'Video Call', 'FaceTime', 'Texting',
      'Jealousy', 'Insecurity', 'Possessive', 'Controlling', 'Toxic', 'Red Flag',
      'Green Flag', 'Yellow Flag', 'Healthy', 'Unhealthy', 'Supportive', 'Competitive',
      'Growth', 'Development', 'Encouragement', 'Inspiration', 'Motivation', 'Partnership'
    ],
    'Cousin Chaos Dares & Confessions': [
      'I Dare You', 'Dare', 'Accept', 'Refuse', 'Back Out', 'Chicken Out',
      'Confession Time', 'Confess', 'Admit', 'Reveal', 'Tell The Truth', 'Spill The Tea',
      'Secret', 'Hidden', 'Kept From', 'Lied About', 'Deceived', 'Guilty',
      'Most Embarrassing', 'Most Embarrassing Moment', 'Most Humiliating', 'Most Regrettable', 'Worst', 'Best',
      'Weirdest Crush', 'Fictional Character Crush', 'Celebrity Crush', 'Famous Person', 'Crush', 'Attracted To',
      'Never Have I Ever', 'Done This', 'Never Done', 'First Time', 'Experience', 'Inexperienced',
      'Wildest Dream', 'Fantasy', 'Bucket List', 'Aspiration', 'Goal', 'Ambition',
      'Biggest Fear', 'Fear', 'Phobia', 'Scared Of', 'Terrified', 'Anxious About',
      'Biggest Lie', 'Lied', 'Made Up', 'Exaggerated', 'Embellished', 'Fabricated',
      'Most Immature', 'Acted Like A Kid', 'Silly', 'Goofy', 'Stupid', 'Foolish',
      'Worst Decision', 'Made A Mistake', 'Regretted', 'Should Have Known', 'Lessons Learned', 'Hindsight',
      'Oddest Food', 'Weird Food', 'Unusual', 'Strange Combination', 'Gross', 'Disgusting',
      'Tallest Tale', 'Exaggeration', 'Fish Story', 'Urban Legend', 'Myth', 'Fiction',
      'Act Out', 'Perform', 'Impersonate', 'Mimic', 'Imitate', 'Parody',
      'Sing A Song', 'Perform', 'Karaoke', 'Solo', 'Acapella', 'Off Key',
      'Dance Move', 'Do A Dance', 'Choreography', 'Moves', 'Rhythm', 'Coordination',
      'Funny Voice', 'Accent', 'Impression', 'Character', 'Persona', 'Alter Ego',
      'Physical Challenge', 'Stunt', 'Trick', 'Skill', 'Athletic', 'Coordination',
      'Photo Dare', 'Pose', 'Selfie', 'Group Photo', 'Funny Face', 'Expression',
      'Call Someone', 'Text Message', 'Social Media Post', 'Shout Out', 'Declare', 'Announce'
    ],
    'Wild Card Chaos': [
      'Random', 'Unexpected', 'Surprising', 'Shocking', 'Outrageous', 'Ridiculous',
      'Crazy', 'Insane', 'Out of Control', 'Chaotic', 'Hectic', 'Frantic',
      'Wild', 'Untamed', 'Feral', 'Primal', 'Uninhibited', 'Uninhibited',
      'Spontaneous', 'Impulsive', 'Acting Out', 'Reckless', 'Dangerous', 'Risky',
      'Adrenaline Rush', 'Thrill', 'Excitement', 'Adventure', 'Explore', 'Discover',
      'New Experience', 'First Time', 'Unknown', 'Uncharted', 'Unfamiliar', 'Foreign',
      'Mystery', 'Secret', 'Hidden', 'Mysterious', 'Intriguing', 'Puzzling',
      'Conspiracy', 'Plot', 'Scheme', 'Plan', 'Strategy', 'Tactics',
      'Rebellion', 'Rebel', 'Defiance', 'Resist', 'Break The Rules', 'Rule Break',
      'Unconventional', 'Unique', 'Different', 'Individual', 'Distinct', 'Special',
      'Quirky', 'Weird', 'Odd', 'Strange', 'Unusual', 'Peculiar',
      'Eccentric', 'Unconformist', 'Rebel', 'Nonconformist', 'Alternative', 'Counter Culture',
      'Underground', 'Subculture', 'Fringe', 'Alternative Scene', 'Scene', 'Crowd',
      'Artistic', 'Creative', 'Imaginative', 'Inventive', 'Innovative', 'Experimental',
      'Performance Art', 'Installation', 'Immersive', 'Interactive', 'Participatory', 'Collaborative',
      'Surreal', 'Dreamlike', 'Fantasy', 'Imagination', 'Illusion', 'Hallucination',
      'Supernatural', 'Paranormal', 'Ghostly', 'Haunted', 'Eerie', 'Creepy',
      'Dark', 'Shadow', 'Mysterious', 'Enigmatic', 'Puzzling', 'Perplexing',
      'Absurd', 'Ridiculous', 'Nonsensical', 'Illogical', 'Irrational', 'Senseless',
      'Hilarious', 'Hilarious', 'Comical', 'Comic', 'Laughable', 'Funny'
    ],
    'Celebrity & Pop Culture Chaos': [
      'Celebrity', 'Famous', 'Star', 'Icon', 'Legend', 'Superstar',
      'Actor', 'Actress', 'Performer', 'Entertainer', 'Artist', 'Musician',
      'Singer', 'Rapper', 'Dancer', 'Comedian', 'Athlete', 'Model',
      'Social Media Influencer', 'Streamer', 'YouTuber', 'TikToker', 'Instagrammer', 'Blogger',
      'Fan', 'Fanatic', 'Obsessed', 'Devoted', 'Loyal', 'Passionate',
      'Fan Club', 'Fan Page', 'Fan Art', 'Fan Fiction', 'Fanfic', 'Shipping',
      'Red Carpet', 'Awards Show', 'Emmy', 'Oscar', 'Grammy', 'Golden Globe',
      'Concert', 'Tour', 'Performance', 'Show', 'Appearance', 'Meet and Greet',
      'Autograph', 'Signature', 'Signed', 'Merchandise', 'Merch', 'Collectible',
      'Scandal', 'Controversy', 'Drama', 'Beef', 'Feud', 'Rivalry',
      'Call Out', 'Diss', 'Roast', 'Clap Back', 'Response', 'Counter Attack',
      'Apology', 'Statement', 'Official Response', 'Clarification', 'Explanation', 'Excuse',
      'Break Up', 'Divorce', 'Separation', 'Reconciliation', 'Getting Back Together', 'New Relationship',
      'Engagement', 'Wedding', 'Marriage', 'Baby', 'Family', 'Kids',
      'Career', 'New Role', 'New Movie', 'New Album', 'New Project', 'Comeback',
      'Comeback Album', 'Comeback Tour', 'Rebranding', 'New Look', 'Transformation', 'Reinvention',
      'Collaboration', 'Collab', 'Duet', 'Feature', 'Guest Appearance', 'Cameo',
      'Rumor', 'Gossip', 'Speculation', 'Theory', 'Conspiracy', 'Unconfirmed Report',
      'Leak', 'Exclusive', 'Breaking News', 'Update', 'News Flash', 'Alert',
      'Trend', 'Trending', 'Viral', 'Going Viral', 'Viral Moment', 'Meme'
    ],
    'House Chaos': [
      'Home', 'House', 'Apartment', 'Condo', 'Townhouse', 'Villa',
      'Room', 'Bedroom', 'Living Room', 'Kitchen', 'Bathroom', 'Hallway',
      'Basement', 'Attic', 'Garage', 'Patio', 'Balcony', 'Terrace',
      'Furniture', 'Couch', 'Chair', 'Table', 'Desk', 'Bed',
      'Curtain', 'Blinds', 'Drape', 'Shade', 'Window Treatment', 'Door',
      'Paint', 'Color', 'Wallpaper', 'Decor', 'Decoration', 'Art',
      'Plant', 'Flowers', 'Houseplant', 'Garden', 'Potted', 'Succulent',
      'Kitchen', 'Stove', 'Oven', 'Microwave', 'Refrigerator', 'Freezer',
      'Sink', 'Faucet', 'Counter', 'Cabinet', 'Drawer', 'Pantry',
      'Dishes', 'Pots', 'Pans', 'Utensils', 'Cutlery', 'Silverware',
      'Bathroom', 'Toilet', 'Sink', 'Shower', 'Bath', 'Tub',
      'Mirror', 'Towel', 'Bath Mat', 'Rug', 'Shower Curtain', 'Soap',
      'Lighting', 'Light Bulb', 'Lamp', 'Chandelier', 'Ceiling Fan', 'Switch',
      'Temperature', 'Heat', 'AC', 'Air Conditioning', 'Thermostat', 'Furnace',
      'Cleaning', 'Vacuum', 'Mop', 'Broom', 'Duster', 'Cleaning Supply',
      'Laundry', 'Washing Machine', 'Dryer', 'Clothesline', 'Hamper', 'Detergent',
      'Clutter', 'Mess', 'Organized', 'Disorganized', 'Tidy', 'Neat',
      'Storage', 'Closet', 'Shelf', 'Cabinet', 'Organizer', 'Container',
      'Pest', 'Cockroach', 'Ant', 'Mouse', 'Spider', 'Dust Mite',
      'Repair', 'Maintenance', 'Fix', 'Broken', 'Leaking', 'Damaged'
    ]
  };

  static List<String> getCategory(String categoryName) {
    return categories[categoryName] ?? [];
  }

  static List<String> getAllCategories() {
    return categories.keys.toList();
  }

  static String getRandomWord(String categoryName) {
    final words = categories[categoryName];
    if (words == null || words.isEmpty) return '';
    return words[(words.length * 0.5).toInt() + DateTime.now().microsecond % (words.length ~/ 2)];
  }
}
