/// Impostor Mode word database
class ImpostorData {
  static const Map<String, List<String>> categories = {
    'GAMING': [
      'Respawn',
      'Headshot',
      'Loot Box',
      'Noob',
      'Final Boss',
      'Health Bar',
      'Speedrun',
      'Controller',
      'Camp (camping a spot)',
      'Rage Quit',
      'Skin (cosmetic)',
      'Patch Update',
      'Glitch',
      'Open World',
      'Side Quest',
      'NPC',
      'Easter Egg',
      'Ranked Mode',
      'Lag',
      'Aim Assist',
      'Battle Pass',
      'Grenade',
      'Sniper',
      'Respawn Point',
      'Kill Streak',
      'Inventory',
      'Crafting',
      'Spawn Trap',
      'Modded Controller',
      'Co-op Mode',
      'Achievements',
      'Cutscene',
      'Game Over',
      'Checkpoint',
      'Loading Screen',
      'Hitbox',
      'Combo Move',
      'Unlockable Character',
      'Season Pass',
      'Prestige',
      'One-Shot Kill',
      'Stealth Mode',
      'Quick Scope',
      'Ping (connection)',
      'Clan Tag',
      'Map Rotation',
      'Endgame',
      'Lore',
      'DLC',
      'Server Crash',
    ],
    'TIKTOK & MEMES': [
      'Ratio',
      'Shadowban',
      'Caught in 4K',
      'No Cap',
      'Rizz',
      'Slay',
      'Touch Grass',
      'Main Character',
      'Understood the Assignment',
      'It\'s Giving',
      'Lowkey',
      'Highkey',
      'NPC Trend',
      'POV',
      'Simp',
      'Based',
      'Red Flag',
      'Green Flag',
      'Beige Flag',
      'Delulu',
      'Rent Free',
      'Ate and Left No Crumbs',
      'Era (e.g. villain era)',
      'Lore',
      'Side Eye',
      'Chefs Kiss',
      'That Girl',
      'Roman Empire',
      'Situationship',
      'Hot Take',
      'Brain Rot',
      'Unhinged',
      'Vibe Check',
      'Period (emphasis)',
      'Say Less',
      'Ick',
      'W Rizz',
      'Glazing',
      'Real One',
      'Core (e.g. cottagecore)',
      'Mid',
      'Bussin',
      'Snatched',
      'Feral',
      'Clout',
      'Ratio\'d',
      'Stan',
      'Chronically Online',
      'Gaslight',
      'Main Character Energy',
    ],
    'FOODS': [
      'Pepperoni Pizza',
      'Sushi Roll',
      'Ramen',
      'Fried Chicken',
      'Burger',
      'Tacos',
      'Shawarma',
      'Jollof Rice',
      'Pancakes',
      'Instant Noodles',
      'Hot Dog',
      'Nachos',
      'Dumplings',
      'Waffle',
      'Grilled Cheese',
      'Cheesecake',
      'Mochi',
      'Boba Tea',
      'Spring Rolls',
      'Mac and Cheese',
      'Fried Rice',
      'Croissant',
      'Curry',
      'Popcorn',
      'Cotton Candy',
      'Samosa',
      'Churros',
      'Donut',
      'Pho',
      'Bibimbap',
      'Katsu',
      'Jerk Chicken',
      'Empanada',
      'Pita Bread',
      'Hummus',
      'Gyoza',
      'Baklava',
      'Chili Dog',
      'Loaded Fries',
      'Mango Sticky Rice',
      'Birria Tacos',
      'Smash Burger',
      'Omurice',
      'Takoyaki',
      'Poke Bowl',
      'Açaí Bowl',
      'Flatbread',
      'Dim Sum',
      'Falafel',
      'Ice Cream Sandwich',
    ],
    'BRANDS & SNEAKERS': [
      'Air Force 1',
      'Jordan 1',
      'Yeezy',
      'New Balance 550',
      'Dunk Low',
      'Adidas Samba',
      'Vans Old Skool',
      'Converse Chuck Taylor',
      'Reebok Classic',
      'Travis Scott Collab',
      'Supreme Drop',
      'Off-White',
      'Balenciaga',
      'Palace',
      'Stüssy',
      'BAPE',
      'Fear of God',
      'Essentials Hoodie',
      'Champion',
      'Carhartt',
      'Stone Island',
      'Corteiz',
      'Gallery Dept',
      'Trapstar',
      'Anti Social Social Club',
      'Kith',
      'Noah',
      'Aime Leon Dore',
      'Human Made',
      'A Bathing Ape',
      'Nike Tech Fleece',
      'Puffer Jacket (North Face)',
      'Levi\'s 501',
      'Ralph Lauren',
      'Tommy Hilfiger',
      'Lacoste',
      'Burberry Check',
      'Louis Vuitton Monogram',
      'Gucci Belt',
      'Dior Oblique',
      'OVO (October\'s Very Own)',
      'Sp5der',
      'Hellstar',
      'Eric Emanuel Shorts',
      'Madhappy',
      'Broken Planet',
      'Represent',
      'Weekend Offender',
      'Hoka Bondi',
      'On Running Cloud',
    ],
    'MOVIES & SHOWS': [
      'Squid Game',
      'Money Heist',
      'Breaking Bad',
      'The Office',
      'Stranger Things',
      'Avatar (blue people)',
      'The Dark Knight',
      'Spider-Man',
      'Black Panther',
      'Interstellar',
      'Parasite',
      'Get Out',
      'Avengers Endgame',
      'Titanic',
      'The Lion King',
      'Shrek',
      'Fast & Furious',
      'John Wick',
      'Inception',
      'The Matrix',
      'Harry Potter',
      'Game of Thrones',
      'Euphoria',
      'Peaky Blinders',
      'Narcos',
      'Prison Break',
      'Wednesday (Netflix)',
      'Outer Banks',
      'One Piece (live action)',
      'Attack on Titan',
      'Demon Slayer',
      'Jujutsu Kaisen',
      'My Hero Academia',
      'Death Note',
      'Fullmetal Alchemist',
      'Naruto Shippuden',
      'Dragon Ball Z',
      'Hunter x Hunter',
      'Sword Art Online',
      'Tokyo Ghoul',
      'Your Name (Kimi no Na wa)',
      'Spirited Away',
      'Princess Mononoke',
      'Cowboy Bebop',
      'Vinland Saga',
      'Blue Lock',
      'Chainsaw Man',
      'Solo Leveling',
      'Dandadan',
      'Frieren',
    ],
    'SCHOOL LIFE': [
      'Detention',
      'Supply Teacher',
      'Fire Drill',
      'Lunch Queue',
      'Group Project',
      'Exam Week',
      'Report Card',
      'Hall Pass',
      'School Trip',
      'Locker',
      'Canteen Food',
      'Morning Assembly',
      'Late Slip',
      'Cheat Sheet',
      'Revision Notes',
      'Study Group',
      'Teacher\'s Pet',
      'Class Clown',
      'Back Row',
      'Seating Plan',
      'Homework Due',
      'Pop Quiz',
      'Science Lab',
      'Sports Day',
      'Uniform Check',
      'Parent Evening',
      'Timetable',
      'Free Period',
      'School Play',
      'Prom Night',
      'Yearbook Photo',
      'Graduation',
      'Cafeteria Tray',
      'School Bus',
      'Library Silence',
      'Art Class',
      'PE Lesson',
      'Music Room',
      'Projector Screen',
      'Whiteboard Marker',
      'Pencil Case',
      'Textbook',
      'Desk Scratch (graffiti)',
      'End of Year Party',
      'Class Register',
      'Essay Deadline',
      'School Gate',
      'Nap in Class',
      'Copied Homework',
      'Substitute Teacher Chaos',
    ],
    'COUNTRIES & CITIES': [
      'Japan',
      'Nigeria',
      'Brazil',
      'South Korea',
      'France',
      'Mexico',
      'India',
      'Jamaica',
      'Italy',
      'USA',
      'UK',
      'Ghana',
      'Turkey',
      'Egypt',
      'China',
      'Australia',
      'Spain',
      'Canada',
      'Saudi Arabia',
      'Argentina',
      'New York City',
      'Tokyo',
      'London',
      'Lagos',
      'Paris',
      'Dubai',
      'Seoul',
      'Mumbai',
      'Rio de Janeiro',
      'Cape Town',
      'Toronto',
      'Sydney',
      'Istanbul',
      'Cairo',
      'Mexico City',
      'Bangkok',
      'Singapore',
      'Amsterdam',
      'Nairobi',
      'Accra',
      'Jakarta',
      'Karachi',
      'Johannesburg',
      'Miami',
      'Los Angeles',
      'Chicago',
      'Berlin',
      'Rome',
      'Madrid',
      'Kuala Lumpur',
    ],
    'FAMILY SCENARIOS': [
      'Sunday Dinner',
      'Family Reunion',
      'The Favourite Child',
      'Nosy Auntie',
      'Strict Parent',
      'Curfew',
      'Chores Argument',
      'Road Trip Fight',
      'Sleeping Over',
      'Sibling Rivalry',
      'Family Group Chat',
      'Parents Fighting Over TV',
      'The Golden Child',
      'Embarrassing Baby Photos',
      'Dad Jokes',
      'Mum\'s Cooking',
      'The Loud Uncle',
      'Family BBQ',
      'Sharing a Room',
      'Borrowing Money (and not returning it)',
      'Getting Grounded',
      'Sneaking Out',
      'Being Compared to a Cousin',
      'School Report Drama',
      'Phone Confiscated',
      'Family Prayer Time',
      'Overstaying Guests',
      'Wedding Drama',
      'Christmas Morning',
      'Birthday Forgotten',
      'House Rules',
      'Family Secret',
      'The Dramatic Cousin',
      'Youngest Gets Away With Everything',
      'Old Family Photos',
      'The Relative Nobody Likes',
      'Family Holiday Disaster',
      'Grandma\'s House Rules',
      'Cousins vs Parents Debate',
      'Who Gets the Last Piece',
      'Family Talent Show',
      'Neighbourhood Gossip',
      'Trying to Be Quiet at Night',
      'Parents Reading Your Messages',
      'Aunties Pinching Cheeks',
      'Being Put on Speakerphone',
      'Family Zoom Call Chaos',
      'Baby Cousin Breaking Everything',
      'Older Sibling Bossing You',
      'Family Friend You Call "Uncle"',
    ],
    'MUSIC': [
      'Drake',
      'Kendrick Lamar',
      'Travis Scott',
      'SZA',
      'Bad Bunny',
      'Burna Boy',
      'Wizkid',
      'Rema',
      'Stormzy',
      'Central Cee',
      'Lil Baby',
      'Gunna',
      'Playboi Carti',
      'Frank Ocean',
      'Tyler the Creator',
      'Billie Eilish',
      'The Weeknd',
      'Doja Cat',
      'Nicki Minaj',
      'Cardi B',
      'Metro Boomin',
      'Future',
      'Lil Uzi Vert',
      'Yeat',
      'Sexyy Red',
      'Ice Spice',
      'Asake',
      'Davido',
      'Afrobeats',
      'Drill Music',
      'Trap',
      'R&B',
      'K-Pop',
      'Amapiano',
      'Dancehall',
      'Lo-Fi',
      'Hyperpop',
      'UK Rap',
      'Grime',
      'Music Festival',
      'Album Drop',
      'Feature (collab)',
      'Diss Track',
      'Freestyle',
      'Verse',
      'Chorus',
      'Music Video',
      'Spotify Wrapped',
      'Concert Pit',
    ],
    'SUPERHEROES & VILLAINS': [
      'Spider-Man',
      'Batman',
      'Iron Man',
      'Superman',
      'Black Panther',
      'Thor',
      'Captain America',
      'Wonder Woman',
      'The Flash',
      'Green Lantern',
      'Thanos',
      'Joker',
      'Loki',
      'Magneto',
      'Venom',
      'Doctor Strange',
      'Black Widow',
      'Hawkeye',
      'Ant-Man',
      'Shazam',
      'Aquaman',
      'Deadpool',
      'Wolverine',
      'Storm',
      'Cyclops',
      'Professor X',
      'Mystique',
      'Lex Luthor',
      'Bane',
      'Riddler',
      'Harley Quinn',
      'Poison Ivy',
      'Two-Face',
      'Scarlet Witch',
      'Vision',
      'War Machine',
      'Falcon',
      'Winter Soldier',
      'Nick Fury',
      'Hawkeye (Kate Bishop)',
      'Moon Knight',
      'She-Hulk',
      'Ms. Marvel',
      'Blue Beetle',
      'Homelander (The Boys)',
      'Omni-Man (Invincible)',
      'Goku (DBZ)',
      'Naruto',
      'Saitama (One Punch Man)',
      'Izuku Midoriya (MHA)',
    ],
    'SPORTS': [
      'Slam Dunk',
      'Hat Trick',
      'Penalty Kick',
      'Free Throw',
      'Grand Slam',
      'Knockout',
      'Marathon',
      'Relay Race',
      'Offside',
      'Red Card',
      'Yellow Card',
      'Corner Kick',
      'Own Goal',
      'Overtime',
      'Sudden Death',
      'Dribble',
      'Tackle',
      'Serve (tennis)',
      'Ace (tennis)',
      'Birdie (golf)',
      'Hole in One',
      'Sprinting',
      'High Jump',
      'Long Jump',
      'Javelin',
      'Bench Press',
      'Deadlift',
      'Squat',
      'Swimming Lap',
      'Diving Board',
      'Cricket Wicket',
      'Rugby Scrum',
      'American Football Touchdown',
      'Baseball Home Run',
      'Hockey Puck',
      'Volleyball Spike',
      'Boxing Jab',
      'MMA Takedown',
      'Wrestling Pin',
      'F1 Pit Stop',
      'Cycling Sprint',
      'Skateboard Kickflip',
      'Surfing Wave',
      'Snowboard Trick',
      'Basketball Crossover',
      'Football Bicycle Kick',
      'Basketball Alley-Oop',
      'Football Nutmeg',
      'Basketball Triple-Double',
      'Football Golden Boot',
    ],
    'SOCIAL MEDIA': [
      'Instagram Story',
      'Twitter/X Ratio',
      'YouTube Short',
      'TikTok FYP',
      'Snapchat Streak',
      'Discord Server',
      'Reddit Thread',
      'Twitch Stream',
      'Facebook Marketplace',
      'LinkedIn Post',
      'Pinterest Board',
      'BeReal Notification',
      'WhatsApp Status',
      'Telegram Channel',
      'Substack Newsletter',
      'Podcast Episode',
      'Viral Post',
      'Cancel Culture',
      'Comment Section War',
      'Going Live',
      'Shadowbanned',
      'Verified Tick',
      'Algorithm',
      'Content Creator',
      'Subscriber Count',
      'Unboxing Video',
      'Reaction Video',
      'Collab Video',
      'Sponsored Post',
      'Brand Deal',
      'Merch Drop',
      'Pinned Comment',
      'DM Slide',
      'Story Poll',
      'Close Friends List',
      'Finsta',
      'Fake Account (Catfish)',
      'Chronological Feed',
      'Explore Page',
      'Hashtag',
      'Repost',
      'Quote Tweet',
      'Thread (Twitter)',
      'Going Viral',
      '1 Million Views',
      'Deactivated Account',
      'Screen Time Warning',
      'Notification Spam',
      'Group Chat Drama',
      'Read Receipt (left on read)',
    ],
    'SCIENCE & SCHOOL SUBJECTS': [
      'Photosynthesis',
      'Black Hole',
      'DNA',
      'Atom',
      'Gravity',
      'Evolution',
      'Periodic Table',
      'Chemical Reaction',
      'Ecosystem',
      'Cell Division',
      'Electromagnetic Wave',
      'Newton\'s Law',
      'Pythagorean Theorem',
      'Pi (3.14)',
      'Prime Number',
      'Equation',
      'Hypothesis',
      'Experiment',
      'Control Variable',
      'Scientific Method',
      'Climate Change',
      'Carbon Dioxide',
      'Oxygen Cycle',
      'Food Chain',
      'Predator',
      'Prey',
      'Fossil',
      'Tectonic Plates',
      'Volcano',
      'Earthquake',
      'Solar System',
      'Galaxy',
      'Nebula',
      'Big Bang',
      'Wormhole',
      'Quantum Physics',
      'Relativity',
      'Velocity',
      'Acceleration',
      'Force',
      'Friction',
      'Momentum',
      'Energy Transfer',
      'Magnetism',
      'Circuit',
      'Resistance (Ohm\'s Law)',
      'Refraction',
      'Diffraction',
      'Osmosis',
      'Mitosis',
    ],
    'RANDOM OBJECTS': [
      'Stapler',
      'Bubble Wrap',
      'Paper Clip',
      'Rubber Duck',
      'Toothbrush',
      'Alarm Clock',
      'Umbrella',
      'Sticky Note',
      'Highlighter',
      'Tape Measure',
      'Flashlight',
      'Extension Cord',
      'Laundry Basket',
      'Door Hinge',
      'Shower Curtain',
      'TV Remote',
      'Couch Cushion',
      'Cereal Box',
      'Trash Can',
      'Doorbell',
      'Key Ring',
      'Sunglasses',
      'Baseball Cap',
      'Wristwatch',
      'Wallet',
      'Backpack',
      'Water Bottle',
      'Gym Bag',
      'Notebook',
      'Pencil Sharpener',
      'Scissors',
      'Glue Stick',
      'Ruler',
      'Calculator',
      'Eraser',
      'Marker',
      'Index Card',
      'Binder',
      'Folder',
      'Desk Lamp',
      'Phone Charger',
      'Earphones',
      'Keyboard',
      'Mouse Pad',
      'USB Drive',
      'Monitor',
      'Webcam',
      'Power Bank',
      'Laptop Stand',
      'Cable Ties',
    ],
    'REACTIONS & EMOTIONS': [
      'Cringe',
      'Embarrassment',
      'Jealousy',
      'FOMO',
      'Anxiety',
      'Hyped',
      'Dead Inside',
      'Unbothered',
      'Stressed Out',
      'Triggered',
      'Satisfied',
      'Confused',
      'Disappointed',
      'Shocked',
      'Bored',
      'Excited',
      'Nervous',
      'Relieved',
      'Offended',
      'Proud',
      'Overwhelmed',
      'Nostalgic',
      'Hopeful',
      'Betrayed',
      'Suspicious',
      'Obsessed',
      'Overthinking',
      'In Denial',
      'Unbothered',
      'Exhausted',
      'Delulu',
      'Soft-Launched',
      'Caught Off Guard',
      'Gaslighted',
      'Validated',
      'Misunderstood',
      'Petty',
      'Salty',
      'Pressed',
      'Shook',
      'Gassed Up',
      'Lowkey Scared',
      'Highkey Annoyed',
      'Deadpan',
      'Passive Aggressive',
      'Oversharing',
      'Social Battery Dead',
      'Main Character Feeling',
      'Villain Arc Starting',
      'Caught in 4K Feeling',
    ],
    'LATE NIGHT / VIBE': [
      '3AM Thoughts',
      'Midnight Snack',
      'Sleep Paralysis',
      'Insomnia',
      'Alarm Snoozed',
      'Netflix Autoplay',
      'Phone Brightness at Max',
      'Falling Asleep on Call',
      'Lights Off Conversation',
      'Group Chat at 2AM',
      'Sneaking Downstairs',
      'Horror Movie Night',
      'Ghost Stories',
      'Dare at Midnight',
      'Sleeping Bag',
      'Pillow Fight',
      'Whispering So Parents Don\'t Hear',
      'Morning Breath',
      'Forgetting to Sleep',
      'Sleepover Drama',
      'Charging Phone Overnight',
      'Dreams That Feel Real',
      'Waking Up Confused',
      'Sleep Talking',
      'Doomscrolling',
      '4AM Hunger',
      'Blanket Stolen',
      'Cold Room',
      'Neighbourhood Dog Barking',
      'Random Loud Car Outside',
      'Stars Through the Window',
      'Late Night Walk',
      'Dark Hallway',
      'Bathroom at Night (terrifying)',
      'Night Shift Worker',
      'Owl',
      'Moonlight',
      'Streetlight',
      'Empty Street',
      'Quiet Neighbourhood',
      'Night Sky',
      'Campfire',
      'Fireflies',
      'Late Night Drive',
      'Radio at Night',
      'Neon Lights',
      'City at Night',
      'Rooftop Hangout',
      'Balcony at Midnight',
      'Stargazing',
      'Current player says **3 statements** about themselves out loud',
      'Two must be TRUE. One must be a LIE',
      'Group discusses for 30 seconds',
      'Everyone votes simultaneously — which statement is the lie?',
      'Reveal — whoever guessed right gets +1 point',
      'Player who fooled the most people gets +2 points',
      'Screen goes BLACK immediately when player taps DONE',
      '"Everyone look away" message shown BEFORE each player taps',
      'Auto-hide after 5 seconds',
      'No going back',
      'Tap-to-reveal (not swipe)',
    ],
  };
}
