// Cousin Chaos New Modes Data
// Content for Act It Out, Speed Challenge, and other new modes

final Map<String, dynamic> newModesData = {
  'actItOut': {
    'challenges': [
      'Act like you just found out you failed your exam',
      'Mime eating the spiciest food of your life',
      'Act like a robot trying to moonwalk',
      'Pretend you\'re a cat who just saw a cucumber',
      'Act like you\'re texting your crush but autocorrect keeps ruining it',
      'Mime being sucked into a black hole very slowly',
      'Act like you\'re explaining TikTok to your grandma',
      'Pretend you\'re a Sims character with the free will turned off',
      'Act out falling in love with a vending machine',
      'Mime being an NPC in an open-world game',
      'Act like you\'re speed-running getting ready for school',
      'Pretend you\'re a villain giving a monologue but keep forgetting your lines',
      'Act like you\'re trying to quietly sneak snacks at 3AM',
      'Mime battling a final boss with zero HP left',
      'Act like your WiFi keeps cutting out mid-sentence',
      'Pretend you\'re a fashion model but the runway is slippery',
      'Act like you\'re opening a mystery loot box',
      'Mime being attacked by an invisible swarm of bees',
      'Act like you\'re the main character in a dramatic anime opening',
      'Pretend you\'re buffering at 1% for 10 seconds then crash',
      'Act like you sat on something cold and wet',
      'Mime losing a rap battle to a toddler',
      'Act like you\'re trying to flex but you tripped',
      'Pretend your hands are made of noodles for 30 seconds',
      'Act out discovering your food has been eaten by someone else',
      'Mime trying to parallel park for the first time',
      'Act like you\'re a news anchor reporting that school got cancelled',
      'Pretend you\'re a Pokémon trying to evolve but it keeps failing',
      'Act out getting jump-scared playing a horror game',
      'Mime being an influencer whose ring light just died',
      'Act like you\'re the last survivor in a zombie apocalypse but you\'re also hungry',
      'Pretend you\'re a DJ but the crowd is just one person who doesn\'t care',
      'Act like you\'re explaining a meme to your teacher',
      'Mime doing a speedrun of your morning routine in 15 seconds',
      'Act like you\'re in a silent film but dramatic af',
      'Pretend you\'re a knight who just lost their sword down a drain',
      'Act like you\'re switching between different WiFi personalities',
      'Mime getting caught slacking in class',
      'Act out rage-quitting a game then immediately coming back',
      'Pretend you\'re trying to whisper a secret but you\'re too loud',
      'Act like you\'re a GPS giving wrong directions confidently',
      'Mime being dramatically blown away by a tiny fan',
      'Act like you\'re in a K-drama and your enemy just walked in',
      'Pretend you\'re a superhero whose power is sneezing',
      'Act out winning a trophy for most average person',
      'Mime reading a text message that gets increasingly chaotic',
      'Act like your chair is slowly spinning out of control',
      'Pretend you\'re a chef presenting cereal like it\'s fine dining',
      'Act out the entire lifecycle of a viral tweet in 30 seconds',
      'Mime being a statue that\'s slowly coming to life',
    ],
    'everyoneChallenges': [
      'Everyone acts out their spirit animal at the same time',
      'Everyone mimes being stuck in quicksand simultaneously',
      'Everyone acts out waking up late for school at the same time',
      'Everyone pretends they\'re on a sinking ship — GO',
      'Everyone does their best villain laugh together',
      'Everyone mimes riding a rollercoaster — no sounds allowed',
      'Everyone acts like they\'re in a slow-motion action scene',
      'Everyone pretends to be a different nationality\'s stereotype NPC for 20 seconds',
      'Everyone acts out opening the world\'s most disappointing gift',
      'Everyone mimes being a robot malfunctioning at the same time',
    ],
  },
  'speedChallenge': {
    'challenges': [
      'Name 10 Pokémon in 15 seconds',
      'Say the alphabet backwards — you have 20 seconds',
      'List 7 anime shows in 10 seconds',
      'Name 5 capital cities in 8 seconds',
      'Say 10 tongue twisters words fast — "red lorry yellow lorry" x5',
      'Name every player in this room in under 5 seconds',
      'Spell your full name backwards out loud — 10 seconds',
      'List 10 school subjects in 8 seconds',
      'Name 8 Marvel heroes in 10 seconds',
      'Count backwards from 30 to 1 in under 15 seconds',
      'List 5 things in this room that are blue — 7 seconds',
      'Name 6 snacks you\'d eat at a party — 8 seconds',
      'Say 3 different accents in 10 seconds',
      'Name 10 emojis by description only — 15 seconds',
      'Recite a 4-line rap in 10 seconds (make it up)',
      'List 5 famous YouTubers in 6 seconds',
      'Name every Fast & Furious movie you know — 12 seconds',
      'Spell "Constantinople" out loud — 8 seconds',
      'List 10 countries in 12 seconds',
      'Name 8 songs without saying the title — hum them — others must guess — 20 seconds',
      'Name 6 video game characters in 8 seconds',
      'Say a full tongue twister 3 times fast — 15 seconds',
    ],
  },
  // Add more modes here as needed
};