/// Never Have I Ever statement database
class NhieData {
  static const List<Map<String, dynamic>> statements = [
    {'text': 'Never have I ever eaten an entire pizza completely by myself in one sitting.', 'category': 'party_starter'},
    {'text': 'Never have I ever fallen asleep during a movie at the cinema.', 'category': 'party_starter'},
    {'text': 'Never have I ever pretended to be sick just to avoid going somewhere.', 'category': 'party_starter'},
    {'text': 'Never have I ever accidentally liked an old photo while stalking someone\'s profile.', 'category': 'party_starter'},
    {'text': 'Never have I ever called someone the wrong name to their face.', 'category': 'party_starter'},
    {'text': 'Never have I ever sent a text to the completely wrong person.', 'category': 'party_starter'},
    {'text': 'Never have I ever gotten genuinely lost somewhere I knew well.', 'category': 'party_starter'},
    {'text': 'Never have I ever stayed up for more than 30 consecutive hours.', 'category': 'party_starter'},
    {'text': 'Never have I ever eaten food directly off the floor.', 'category': 'party_starter'},
    {'text': 'Never have I ever cried during a commercial or advertisement.', 'category': 'party_starter'},
    {'text': 'Never have I ever binge-watched an entire series in one single day.', 'category': 'party_starter'},
    {'text': 'Never have I ever talked to myself out loud in a public place.', 'category': 'party_starter'},
    {'text': 'Never have I ever laughed so hard I actually cried real tears.', 'category': 'party_starter'},
    {'text': 'Never have I ever pretended not to see someone I knew in public.', 'category': 'party_starter'},
    {'text': 'Never have I ever gone a full week without properly showering.', 'category': 'party_starter'},
    {'text': 'Never have I ever read someone else\'s diary or personal journal.', 'category': 'party_starter'},
    {'text': 'Never have I ever worn the same outfit for 3 days in a row.', 'category': 'party_starter'},
    {'text': 'Never have I ever eaten cereal for dinner as an adult.', 'category': 'party_starter'},
    {'text': 'Never have I ever skipped a workout by making up a fake excuse.', 'category': 'party_starter'},
    {'text': 'Never have I ever returned something I had already used.', 'category': 'party_starter'},
    {'text': 'Never have I ever blamed a bad smell on someone else.', 'category': 'party_starter'},
    {'text': 'Never have I ever Googled myself and found something interesting.', 'category': 'party_starter'},
    {'text': 'Never have I ever snuck food into a cinema.', 'category': 'party_starter'},
    {'text': 'Never have I ever pretended to be on the phone to avoid talking to someone.', 'category': 'party_starter'},
    {'text': 'Never have I ever fallen asleep during a work meeting.', 'category': 'party_starter'},
    {'text': 'Never have I ever forgotten a birthday I was supposed to remember.', 'category': 'party_starter'},
    {'text': 'Never have I ever deleted a message I regretted sending immediately after.', 'category': 'party_starter'},
    {'text': 'Never have I ever rehearsed a difficult conversation in the mirror.', 'category': 'party_starter'},
    {'text': 'Never have I ever eaten someone else\'s food in the fridge and said nothing.', 'category': 'party_starter'},
    {'text': 'Never have I ever deliberately avoided calling someone back for days.', 'category': 'party_starter'},
    {'text': 'Never have I ever cried over a fictional character\'s death.', 'category': 'party_starter'},
    {'text': 'Never have I ever skipped the gym for more than 3 weeks straight.', 'category': 'party_starter'},
    {'text': 'Never have I ever bought something expensive and hidden it from my family.', 'category': 'party_starter'},
    {'text': 'Never have I ever taken a selfie that took more than 20 attempts to get right.', 'category': 'party_starter'},
    {'text': 'Never have I ever been caught singing alone in the car.', 'category': 'party_starter'},
    {'text': 'Never have I ever stayed in a relationship too long knowing it was over.', 'category': 'party_starter'},
    {'text': 'Never have I ever pretended to understand a joke I completely didn\'t get.', 'category': 'party_starter'},
    {'text': 'Never have I ever eaten something that fell on the kitchen floor.', 'category': 'party_starter'},
    {'text': 'Never have I ever told someone their outfit looked nice when it didn\'t.', 'category': 'party_starter'},
    {'text': 'Never have I ever woken up and immediately checked my phone before anything else.', 'category': 'party_starter'},
    {'text': 'Never have I ever given someone a fake phone number.', 'category': 'party_starter'},
    {'text': 'Never have I ever had a full conversation while sleepwalking.', 'category': 'party_starter'},
    {'text': 'Never have I ever copy-pasted a message to multiple people pretending it was personal.', 'category': 'party_starter'},
    {'text': 'Never have I ever used my phone while sitting on the toilet.', 'category': 'party_starter'},
    {'text': 'Never have I ever run away from a conversation I didn\'t want to have.', 'category': 'party_starter'},
    {'text': 'Never have I ever gone to bed without brushing my teeth and told no one.', 'category': 'party_starter'},
    {'text': 'Never have I ever pretended to be busier than I actually was.', 'category': 'party_starter'},
    {'text': 'Never have I ever secretly eaten snacks I was meant to share.', 'category': 'party_starter'},
    {'text': 'Never have I ever hit send and immediately wished I could take it back.', 'category': 'party_starter'},
    {'text': 'Never have I ever said I\'m 5 minutes away when I hadn\'t left yet.', 'category': 'party_starter'},
    {'text': 'Never have I ever forgotten someone\'s name and spent the whole time avoiding using it.', 'category': 'party_starter'},
    {'text': 'Never have I ever bought something I didn\'t need just because it was on sale.', 'category': 'party_starter'},
    {'text': 'Never have I ever fallen asleep on public transport and missed my stop.', 'category': 'party_starter'},
    {'text': 'Never have I ever told a joke that completely bombed in silence.', 'category': 'party_starter'},
    {'text': 'Never have I ever made up an excuse to leave a party early.', 'category': 'party_starter'},
    {'text': 'Never have I ever sent an audio message completely by accident.', 'category': 'party_starter'},
    {'text': 'Never have I ever had a whole argument in my head and felt emotionally drained afterward.', 'category': 'party_starter'},
    {'text': 'Never have I ever walked into the wrong bathroom and had to walk out.', 'category': 'party_starter'},
    {'text': 'Never have I ever put my clothes on inside out and only noticed hours later.', 'category': 'party_starter'},
    {'text': 'Never have I ever pretended to know a celebrity others were talking about.', 'category': 'party_starter'},
    {'text': 'Never have I ever started watching a show just because everyone else was.', 'category': 'party_starter'},
    {'text': 'Never have I ever taken credit for something someone else did.', 'category': 'party_starter'},
    {'text': 'Never have I ever stayed on my phone during a meal and felt bad about it.', 'category': 'party_starter'},
    {'text': 'Never have I ever faked laughing at a joke that wasn\'t funny at all.', 'category': 'party_starter'},
    {'text': 'Never have I ever overcooked a meal and served it anyway without saying anything.', 'category': 'party_starter'},
    {'text': 'Never have I ever walked out of a shop without paying completely by accident.', 'category': 'party_starter'},
    {'text': 'Never have I ever forgotten something important at the absolute worst possible time.', 'category': 'party_starter'},
    {'text': 'Never have I ever typed a whole paragraph and then deleted it without sending.', 'category': 'party_starter'},
    {'text': 'Never have I ever snuck a peek at someone else\'s test answer.', 'category': 'party_starter'},
    {'text': 'Never have I ever pretended to be interested in a topic I found completely boring.', 'category': 'party_starter'},
    {'text': 'Never have I ever hit the snooze button more than 5 times in one single morning.', 'category': 'party_starter'},
    {'text': 'Never have I ever been caught talking about someone who was right behind me.', 'category': 'party_starter'},
    {'text': 'Never have I ever tripped over something I put there myself.', 'category': 'party_starter'},
    {'text': 'Never have I ever avoided replying to a message for so long it became really weird.', 'category': 'party_starter'},
    {'text': 'Never have I ever started a task I never actually finished.', 'category': 'party_starter'},
    {'text': 'Never have I ever pretended not to hear someone calling my name.', 'category': 'party_starter'},
    {'text': 'Never have I ever tried to look smart in front of someone and completely failed.', 'category': 'party_starter'},
    {'text': 'Never have I ever made a decision by flipping a coin.', 'category': 'party_starter'},
    {'text': 'Never have I ever panicked about something I had already resolved.', 'category': 'party_starter'},
    {'text': 'Never have I ever read the end of a book before actually finishing it.', 'category': 'party_starter'},
    {'text': 'Never have I ever rewatched a movie and pretended it was my first time.', 'category': 'party_starter'},
    {'text': 'Never have I ever bought a book I never actually read.', 'category': 'party_starter'},
    {'text': 'Never have I ever messed up a recipe and served it without mentioning it.', 'category': 'party_starter'},
    {'text': 'Never have I ever told a story slightly differently each time I told it.', 'category': 'party_starter'},
    {'text': 'Never have I ever invented an excuse to avoid being in a photo.', 'category': 'party_starter'},
    {'text': 'Never have I ever started a diet on Monday and ended it by Tuesday.', 'category': 'party_starter'},
    {'text': 'Never have I ever spoken to a machine as if it could completely understand me.', 'category': 'party_starter'},
    {'text': 'Never have I ever rehearsed what I was going to say before a phone call.', 'category': 'party_starter'},
    {'text': 'Never have I ever panicked about an email I sent because of a typo.', 'category': 'party_starter'},
    {'text': 'Never have I ever eaten a snack I convinced myself was healthy when it wasn\'t.', 'category': 'party_starter'},
    {'text': 'Never have I ever moved something just to avoid tidying it properly.', 'category': 'party_starter'},
    {'text': 'Never have I ever called something I lost when it was in my hand the whole time.', 'category': 'party_starter'},
    {'text': 'Never have I ever tried something on in a shop and then put it back.', 'category': 'party_starter'},
    {'text': 'Never have I ever planned a surprise that accidentally became completely obvious.', 'category': 'party_starter'},
    {'text': 'Never have I ever stood in a shop for so long I left without buying anything.', 'category': 'party_starter'},
    {'text': 'Never have I ever been late and blamed it on traffic when I just left too late.', 'category': 'party_starter'},
    {'text': 'Never have I ever reread my own old messages just to cringe at myself.', 'category': 'party_starter'},
    {'text': 'Never have I ever pretended my phone was dead to avoid someone calling.', 'category': 'party_starter'},
    {'text': 'Never have I ever eaten someone\'s birthday cake before it was time to cut it.', 'category': 'party_starter'},
    {'text': 'Never have I ever done something embarrassing and immediately looked around to see if anyone noticed.', 'category': 'party_starter'},
    {'text': 'Never have I ever texted someone I liked and immediately regretted it.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever stalked someone\'s profile for more than 30 minutes straight.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever liked someone\'s social media post from 3 years ago by accident.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever gone back to an ex I swore I was done with forever.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been on a date and faked having a good time.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever sent a flirty message to the completely wrong person.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever ghosted someone I actually genuinely liked.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever cancelled plans because I was nervous about seeing someone.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever checked if someone was online right after I texted them.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever looked up someone\'s profile immediately after meeting them.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever had feelings for someone I would publicly deny.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever invented a fake reason to text someone I liked.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been jealous of a friend\'s relationship and said nothing.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever cried after looking at old photos from a relationship.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever saved someone\'s number under a code name.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever rehearsed what I would say to my crush.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever turned down someone I liked because I was scared.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever stayed up past midnight thinking about someone specific.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever sent a voice note I completely should not have.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever checked my phone hoping a specific person would text.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever made up a fake plan to seem less available.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been in a situationship I couldn\'t explain to anyone.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever pretended not to care about someone I was crazy about.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever looked at someone else while in a relationship.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever taken a screenshot of a conversation to show someone else.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever changed my outfit 3 or more times before seeing someone.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever planned what I would say if they called out of nowhere.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been the person who texts first every single time.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever had a crush on someone I\'d never admit out loud.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever dated someone I knew wasn\'t right for me.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever compared myself to someone my ex was with after me.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever overthought a one-word reply for 20 minutes.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever typed a long message and deleted it before sending.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been upset about something I saw on someone\'s social media.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever asked a mutual friend about someone I was interested in.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever matched with someone online and been too nervous to message.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever forgotten to reply to someone I actually liked.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever confessed feelings I wasn\'t totally ready to confess.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever broken up with someone and regretted it almost immediately.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever had feelings develop for my best friend.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever downloaded a dating app and deleted it the same day.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever put someone\'s name in my phone as something other than their name.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been in two situationships at once without planning it.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been told I was too much for someone and actually felt hurt.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever blocked someone and then unblocked them within 24 hours.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever made a decision about someone based entirely on their music taste.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been interested in someone just because they seemed uninterested.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever told someone a relationship was over when it wasn\'t.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever checked someone\'s location and said nothing about it.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever made my life sound more interesting than it was to impress someone.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever had a full fight via text message.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been jealous of my own best friend.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever lost a good thing because I was scared of commitment.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever flirted just to get something I wanted.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever pretended a relationship was going better than it was.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever caught feelings for someone who made it very clear they weren\'t interested.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever acted confident around someone I was absolutely terrified by.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever cried over someone who didn\'t know I existed romantically.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been broken up with over text and replied okay cool.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever left a party because someone I didn\'t want to see showed up.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever liked someone more after they did something slightly terrible.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever had a crush on a complete stranger and made up a whole life for them.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been the last to know something everyone else already knew.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever caught myself smiling at my phone and tried to hide it.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever found out someone liked me and not done anything about it.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been on a talking stage for more than 3 months.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever fallen for someone\'s potential rather than who they actually were.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been on a date where I genuinely lost track of time.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever made up an excuse not to meet someone I actually wanted to see.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever felt genuine butterflies when someone walked into a room.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever overthought a compliment someone gave me for days afterward.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been told I come on too strong and thought maybe they\'re right.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever made a playlist for someone I never told about it.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been emotionally unavailable and known it the whole time.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever ended something good because I was scared it would go bad.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever fallen in love with a stranger on public transport.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been in a completely undefined relationship for longer than a year.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever sent a risky text at midnight that got no reply until morning.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever cancelled a date because I panicked at the last minute.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever had a dream about someone that changed how I felt about them.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever met someone and immediately thought that could be something.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever given someone a second chance they 100 percent did not deserve.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever stayed friends with an ex just to keep them close.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever told someone I missed them even though I\'d only just seen them.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been in a relationship with someone I was never really into.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever apologized just to end an argument I knew I\'d won.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever reread an old conversation just to feel something.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever told a complete lie about why a relationship ended.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever fallen for someone who was completely unavailable.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever saved a photo of someone I was into and never told them.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever written a message to someone and never sent it.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever pretended not to be home because someone I liked called.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever been so distracted by someone I walked into something.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever re-read someone\'s old messages just to hear their voice in my head.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever convinced myself the timing was wrong when really I was just scared.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever liked someone so much I started acting completely unlike myself.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever looked at my phone every 5 minutes waiting for one specific person.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever felt more heartbroken after a situationship than a real relationship.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever felt completely invisible to someone I genuinely cared about.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever kept feelings inside for so long they became something I had to grieve.', 'category': 'mild_but_wild'},
    {'text': 'Never have I ever blamed a sibling for something I actually did.', 'category': 'family_night'},
    {'text': 'Never have I ever eaten the last of something and put the empty box back.', 'category': 'family_night'},
    {'text': 'Never have I ever secretly agreed with a parent when I pretended I didn\'t.', 'category': 'family_night'},
    {'text': 'Never have I ever hidden food in my room to eat later.', 'category': 'family_night'},
    {'text': 'Never have I ever lied about how much something cost to a parent.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended to be asleep when a parent checked on me.', 'category': 'family_night'},
    {'text': 'Never have I ever gotten away with something at home and never told anyone.', 'category': 'family_night'},
    {'text': 'Never have I ever borrowed something from a family member and not returned it.', 'category': 'family_night'},
    {'text': 'Never have I ever overheard a family conversation I wasn\'t meant to hear.', 'category': 'family_night'},
    {'text': 'Never have I ever played sick to stay home from school.', 'category': 'family_night'},
    {'text': 'Never have I ever accidentally broken something at home and said nothing.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended to finish my homework when I hadn\'t.', 'category': 'family_night'},
    {'text': 'Never have I ever promised to help with something and then conveniently forgotten.', 'category': 'family_night'},
    {'text': 'Never have I ever eaten someone\'s leftovers without asking first.', 'category': 'family_night'},
    {'text': 'Never have I ever used up all the hot water and not mentioned it to anyone.', 'category': 'family_night'},
    {'text': 'Never have I ever watched the next episode of a show we were watching together.', 'category': 'family_night'},
    {'text': 'Never have I ever made a promise to a family member I knew I probably wouldn\'t keep.', 'category': 'family_night'},
    {'text': 'Never have I ever sneaked a snack before dinner and said I wasn\'t hungry.', 'category': 'family_night'},
    {'text': 'Never have I ever told a parent I wasn\'t on my phone when I clearly was.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended I couldn\'t hear someone calling me from another room.', 'category': 'family_night'},
    {'text': 'Never have I ever used someone else\'s charger without asking.', 'category': 'family_night'},
    {'text': 'Never have I ever borrowed clothes from a family member without telling them.', 'category': 'family_night'},
    {'text': 'Never have I ever read a family member\'s message on their phone while they weren\'t looking.', 'category': 'family_night'},
    {'text': 'Never have I ever given a family member bad advice on purpose just to be funny.', 'category': 'family_night'},
    {'text': 'Never have I ever taken the larger slice and pretended it was an accident.', 'category': 'family_night'},
    {'text': 'Never have I ever told a family member they looked great when they honestly didn\'t.', 'category': 'family_night'},
    {'text': 'Never have I ever thrown away someone else\'s food thinking it was mine.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended I didn\'t see the mess hoping someone else would clean it.', 'category': 'family_night'},
    {'text': 'Never have I ever taken the blame for something just to end an argument faster.', 'category': 'family_night'},
    {'text': 'Never have I ever eaten the last biscuit or snack and said absolutely nothing.', 'category': 'family_night'},
    {'text': 'Never have I ever changed the TV channel when someone else was clearly watching.', 'category': 'family_night'},
    {'text': 'Never have I ever finished someone else\'s leftovers without asking.', 'category': 'family_night'},
    {'text': 'Never have I ever told a family member I was nearly there when I hadn\'t even left yet.', 'category': 'family_night'},
    {'text': 'Never have I ever nodded along to a family story I\'d heard at least 10 times already.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended to like a family member\'s cooking when I didn\'t enjoy it.', 'category': 'family_night'},
    {'text': 'Never have I ever lost something that belonged to a family member and said nothing.', 'category': 'family_night'},
    {'text': 'Never have I ever made up a stomach ache to avoid doing chores.', 'category': 'family_night'},
    {'text': 'Never have I ever stayed up way past my bedtime and pretended I\'d been asleep.', 'category': 'family_night'},
    {'text': 'Never have I ever complained about a family member to another family member.', 'category': 'family_night'},
    {'text': 'Never have I ever gotten a gift completely wrong and pretended I knew what I was buying.', 'category': 'family_night'},
    {'text': 'Never have I ever given a family member the exact same gift twice.', 'category': 'family_night'},
    {'text': 'Never have I ever claimed I was about to do a chore I hadn\'t even started yet.', 'category': 'family_night'},
    {'text': 'Never have I ever forgotten a family member\'s birthday and improvised on the day.', 'category': 'family_night'},
    {'text': 'Never have I ever taken a photo at a family event and never shared it with anyone.', 'category': 'family_night'},
    {'text': 'Never have I ever laughed at a family story and had absolutely no idea what it was about.', 'category': 'family_night'},
    {'text': 'Never have I ever agreed to attend a family event and only decided what to wear that morning.', 'category': 'family_night'},
    {'text': 'Never have I ever finished the last of the milk and put the empty carton back in the fridge.', 'category': 'family_night'},
    {'text': 'Never have I ever gotten a family member involved in an argument they had nothing to do with.', 'category': 'family_night'},
    {'text': 'Never have I ever purposely missed a family call and called back pretending I didn\'t see it.', 'category': 'family_night'},
    {'text': 'Never have I ever enjoyed a family gathering more than I expected and refused to admit it.', 'category': 'family_night'},
    {'text': 'Never have I ever eaten cake before it was officially time to cut it.', 'category': 'family_night'},
    {'text': 'Never have I ever gotten on the wrong side of a family member\'s pet.', 'category': 'family_night'},
    {'text': 'Never have I ever gotten a younger family member to do a task I didn\'t want to do.', 'category': 'family_night'},
    {'text': 'Never have I ever been completely lost at a family event and just followed others around.', 'category': 'family_night'},
    {'text': 'Never have I ever started a family tradition by complete accident and had to keep it going.', 'category': 'family_night'},
    {'text': 'Never have I ever mispronounced something for years before a family member corrected me.', 'category': 'family_night'},
    {'text': 'Never have I ever spent more money on a family gift than I originally planned to.', 'category': 'family_night'},
    {'text': 'Never have I ever given parental advice to a sibling and then done the opposite myself.', 'category': 'family_night'},
    {'text': 'Never have I ever told a younger family member something would hurt more than it did.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended to feel better at a family gathering just to seem okay.', 'category': 'family_night'},
    {'text': 'Never have I ever taken the longest shower in the house during a busy morning.', 'category': 'family_night'},
    {'text': 'Never have I ever forgotten to pass on an important family message.', 'category': 'family_night'},
    {'text': 'Never have I ever eaten something special someone had saved specifically for themselves.', 'category': 'family_night'},
    {'text': 'Never have I ever let a family member win an argument just to end it faster.', 'category': 'family_night'},
    {'text': 'Never have I ever made a family inside joke that I had already told to other people.', 'category': 'family_night'},
    {'text': 'Never have I ever been completely wrong in a family disagreement and still not admitted it.', 'category': 'family_night'},
    {'text': 'Never have I ever refused to admit a family member was right about something.', 'category': 'family_night'},
    {'text': 'Never have I ever sat through a family movie I hated without saying a single thing.', 'category': 'family_night'},
    {'text': 'Never have I ever been early to a family event but pretended I was still nearly there.', 'category': 'family_night'},
    {'text': 'Never have I ever asked for something that had already been offered and I\'d said no to.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended a new family recipe tasted better than it actually did.', 'category': 'family_night'},
    {'text': 'Never have I ever mixed up family members\' names in a conversation.', 'category': 'family_night'},
    {'text': 'Never have I ever walked into a family event confident and immediately wished I\'d stayed home.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended to be interested in a family member\'s hobby when I wasn\'t.', 'category': 'family_night'},
    {'text': 'Never have I ever started a family argument by sharing something I probably should have kept quiet.', 'category': 'family_night'},
    {'text': 'Never have I ever claimed I was fine after a family disagreement when I absolutely wasn\'t.', 'category': 'family_night'},
    {'text': 'Never have I ever laughed at a family story and then realized it wasn\'t meant to be funny.', 'category': 'family_night'},
    {'text': 'Never have I ever been the last to hear something the whole family already knew about.', 'category': 'family_night'},
    {'text': 'Never have I ever had a moment where I sounded exactly like a parent and it genuinely scared me.', 'category': 'family_night'},
    {'text': 'Never have I ever made the exact same mistake a family member warned me about.', 'category': 'family_night'},
    {'text': 'Never have I ever apologized to a family member only after realizing I had been caught.', 'category': 'family_night'},
    {'text': 'Never have I ever introduced someone to the family before they were ready for it.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended a family photo was a good one when it absolutely wasn\'t.', 'category': 'family_night'},
    {'text': 'Never have I ever told a family secret to someone and then made them promise not to tell.', 'category': 'family_night'},
    {'text': 'Never have I ever told the same funny family story twice in one sitting.', 'category': 'family_night'},
    {'text': 'Never have I ever called a family member by the wrong name and tried to cover it up.', 'category': 'family_night'},
    {'text': 'Never have I ever gotten completely lost driving somewhere a family member knew well.', 'category': 'family_night'},
    {'text': 'Never have I ever nodded through a family conversation I had absolutely no context for.', 'category': 'family_night'},
    {'text': 'Never have I ever had a family moment so embarrassing I still think about it now.', 'category': 'family_night'},
    {'text': 'Never have I ever taken something from a shared snack without telling anyone else.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended I cooked something when I actually just heated it up.', 'category': 'family_night'},
    {'text': 'Never have I ever hidden in my room to avoid a family conversation I didn\'t want.', 'category': 'family_night'},
    {'text': 'Never have I ever let someone else get in trouble for something I was involved in.', 'category': 'family_night'},
    {'text': 'Never have I ever told a family member I was almost ready when I hadn\'t even started.', 'category': 'family_night'},
    {'text': 'Never have I ever conveniently disappeared when it was time to wash up or tidy.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended I\'d already eaten to avoid sitting through a meal I didn\'t want.', 'category': 'family_night'},
    {'text': 'Never have I ever forgotten to tell a family member something important until it was too late.', 'category': 'family_night'},
    {'text': 'Never have I ever pretended I didn\'t hear a request hoping someone else would take it.', 'category': 'family_night'},
    {'text': 'Never have I ever eaten the last piece of something someone else was clearly saving.', 'category': 'family_night'},
    {'text': 'Never have I ever sneaked back into the house hoping nobody would notice I\'d been out.', 'category': 'family_night'},
    {'text': 'Never have I ever kissed someone I met that same day.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever told someone I loved them purely to keep them around.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever gone home with someone I\'d only just met at a party.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been in a relationship with more than one person at the same time.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been caught sending an inappropriate message at the wrong time.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever sent a very personal photo to someone.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever done something intimate somewhere I absolutely shouldn\'t have.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever pretended a relationship was exclusive when it wasn\'t.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been attracted to someone at a family event.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever kissed my friend\'s ex without telling them.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been the reason someone else\'s relationship ended.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever done something in the heat of the moment I completely regret.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been in a friends-with-benefits situation that got complicated.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever faked how I felt to keep someone\'s interest in me.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had someone confess their feelings and been completely blindsided.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever done something daring just to impress someone I was attracted to.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever kissed someone to make a third person jealous.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been attracted to someone I absolutely knew was wrong for me.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever told someone what they wanted to hear instead of the truth.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been on a date with someone while still talking to someone else.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been involved in something I told absolutely no one about.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever caught someone checking me out in a very obvious way.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever worn something specific knowing it would get a particular reaction.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever deleted a conversation history before someone could see it.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever sneaked out at night to meet someone.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been in a relationship that existed only in private.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever said something was a one-time thing and then done it again.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever gone back to someone after saying I never would.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been so attracted to someone it made me act completely differently than usual.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever stayed in something I knew was bad because the chemistry was too good.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been someone\'s secret for longer than I should have accepted.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever told a version of events about a relationship that left out important parts.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had a falling-out with a friend over someone we both liked.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever acted on a drunk feeling I should have kept completely to myself.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever kissed someone at a party and not learned their name.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever found out something about a previous partner I wish I hadn\'t.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been in a situationship that everyone else could see but me.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever started something I had absolutely no intention of finishing.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been told something in confidence about someone I was interested in.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever made a decision at 2am that I deeply questioned at 8am the next day.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever developed feelings for someone I was only meant to be casually seeing.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been on the receiving end of feelings I couldn\'t return.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been in a situation where I didn\'t know who to choose.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever acted on attraction knowing it would make everything complicated.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever told someone a relationship was over and then kept seeing them.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever done something specifically to make someone want me more.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had to pretend something casual didn\'t actually mean something.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had chemistry with someone that I genuinely could not explain.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever told a partial lie about my past to someone I was interested in.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever ended something good because the timing was wrong.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever kissed someone and immediately known it was a mistake.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been more emotionally invested than the other person and said nothing.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had an ex reach out at the absolute worst possible timing.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been the person someone went to when their actual relationship was struggling.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever made someone fall for me when I already knew I wasn\'t ready.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had an almost that I still think about more than I should.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been in love and completely terrified of it at the same time.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been with someone who was completely wrong but made everything feel right.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever met someone and immediately known something was different about them.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been in a relationship that nobody in my life knew existed.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever started something knowing it was going to end badly.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever let something physical get in the way of something emotional.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been in a love triangle where I was genuinely unsure what to do.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever liked someone so much it made me want to run in the opposite direction.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever acted cool in front of someone while internally completely falling apart.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever kept seeing someone out of habit rather than genuine feeling.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had feelings so strong they genuinely scared me.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever ignored every red flag because the green flags felt so good.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been so completely blindsided by feelings I didn\'t see coming.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever stayed in something unhealthy because leaving felt impossible.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been attracted to someone I had every reason to stay away from.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had a conversation with someone that changed the course of things.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever wanted something so badly I talked myself into thinking it was okay.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever realized I had feelings for someone at the absolute worst moment.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been the one to ruin something that could have been great.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been told I was too emotionally unavailable and known they were right.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever thought about someone I haven\'t spoken to in years.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever convinced myself I was over someone when a single song proved I wasn\'t.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever lost someone I really cared about and still wonder what if.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had the best conversation of my life with someone I never saw again.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had my whole perspective on love changed by one person.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever realized something about a past relationship years after it ended.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever known something was going to hurt and done it anyway.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever carried feelings for longer than I\'ve admitted to anyone.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been completely sure about someone and still let them go.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had a chapter of my life I\'ve never fully told anyone about.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever fallen in love and had absolutely no idea what to do with it.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been someone\'s backup person and only realized it much later.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever kept a photo of someone I used to like and never deleted it.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever pretended to be more okay with something than I actually was.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever found myself attracted to someone I had specifically told myself I wouldn\'t be.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been the person who cared more and tried to care less.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever stayed up all night thinking about something that was said to me.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had a moment that I knew at the time would change everything.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever let someone go knowing I might regret it.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever been someone\'s first choice and not fully appreciated it until it was over.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever chosen my pride over something that actually mattered.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had a relationship that changed the entire way I saw myself.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever realized what someone meant to me right when I was losing them.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever had my heart broken by someone who didn\'t even know they were doing it.', 'category': 'spice_it_up'},
    {'text': 'Never have I ever pretended to agree with a friend\'s terrible decision just to avoid drama.', 'category': 'girls_night'},
    {'text': 'Never have I ever read a friend\'s messages when they left their phone unattended.', 'category': 'girls_night'},
    {'text': 'Never have I ever talked about a friend to another friend in a way I wouldn\'t if they were there.', 'category': 'girls_night'},
    {'text': 'Never have I ever been jealous of a friend\'s relationship and never admitted it.', 'category': 'girls_night'},
    {'text': 'Never have I ever given advice I knew the person probably wouldn\'t take.', 'category': 'girls_night'},
    {'text': 'Never have I ever taken credit for an idea that someone else actually had.', 'category': 'girls_night'},
    {'text': 'Never have I ever screenshotted a conversation to send to the group chat.', 'category': 'girls_night'},
    {'text': 'Never have I ever pretended to be over someone I was absolutely not over.', 'category': 'girls_night'},
    {'text': 'Never have I ever cancelled plans with a friend because I simply didn\'t feel like going.', 'category': 'girls_night'},
    {'text': 'Never have I ever told a guy exactly what he wanted to hear when I knew it wasn\'t true.', 'category': 'girls_night'},
    {'text': 'Never have I ever liked someone\'s boyfriend privately and kept it completely to myself.', 'category': 'girls_night'},
    {'text': 'Never have I ever unfollowed and then refollowed someone on social media the same day.', 'category': 'girls_night'},
    {'text': 'Never have I ever pretended I wasn\'t home when someone came to the door.', 'category': 'girls_night'},
    {'text': 'Never have I ever cried in a public toilet because of something a boy said.', 'category': 'girls_night'},
    {'text': 'Never have I ever invented a full plan just to have a convincing excuse.', 'category': 'girls_night'},
    {'text': 'Never have I ever done something embarrassing for attention and pretended it was accidental.', 'category': 'girls_night'},
    {'text': 'Never have I ever posted something specifically hoping one person would see it.', 'category': 'girls_night'},
    {'text': 'Never have I ever deleted a photo from my story after checking who had viewed it.', 'category': 'girls_night'},
    {'text': 'Never have I ever been the one who told the group something told to me in confidence.', 'category': 'girls_night'},
    {'text': 'Never have I ever acted confident in front of someone I was absolutely terrified of.', 'category': 'girls_night'},
    {'text': 'Never have I ever pretended to be busy because I didn\'t know how to say no.', 'category': 'girls_night'},
    {'text': 'Never have I ever looked up someone\'s new partner immediately after a breakup.', 'category': 'girls_night'},
    {'text': 'Never have I ever had a complete breakdown in private and pretended to be absolutely fine.', 'category': 'girls_night'},
    {'text': 'Never have I ever compared myself to someone else for hours straight and said nothing.', 'category': 'girls_night'},
    {'text': 'Never have I ever left someone on read intentionally to seem less desperate.', 'category': 'girls_night'},
    {'text': 'Never have I ever liked someone who was completely wrong for me and known it the whole time.', 'category': 'girls_night'},
    {'text': 'Never have I ever posted a picture solely to make an ex jealous.', 'category': 'girls_night'},
    {'text': 'Never have I ever invented a whole story about what I\'d say in a confrontation that never happened.', 'category': 'girls_night'},
    {'text': 'Never have I ever had a girls night where we talked about the same person the entire time.', 'category': 'girls_night'},
    {'text': 'Never have I ever been the messy one in a friendship group for a period of time.', 'category': 'girls_night'},
    {'text': 'Never have I ever cried getting ready to go out and then went out anyway.', 'category': 'girls_night'},
    {'text': 'Never have I ever been petty in a way I would fully deny if asked.', 'category': 'girls_night'},
    {'text': 'Never have I ever felt validated by someone showing interest I didn\'t even want.', 'category': 'girls_night'},
    {'text': 'Never have I ever given a friend a compliment that wasn\'t completely sincere.', 'category': 'girls_night'},
    {'text': 'Never have I ever romanticized someone based almost entirely on their aesthetic.', 'category': 'girls_night'},
    {'text': 'Never have I ever been in a friendship that felt more exhausting than supportive.', 'category': 'girls_night'},
    {'text': 'Never have I ever cancelled on a friend and felt genuinely relieved about it.', 'category': 'girls_night'},
    {'text': 'Never have I ever had a friend group implosion I definitely had some part in.', 'category': 'girls_night'},
    {'text': 'Never have I ever kept a friendship going longer than I should have out of habit.', 'category': 'girls_night'},
    {'text': 'Never have I ever changed how I acted completely because of who was in the room.', 'category': 'girls_night'},
    {'text': 'Never have I ever had a situationship I couldn\'t explain to my own best friend.', 'category': 'girls_night'},
    {'text': 'Never have I ever bought something just because I knew it would look good on my story.', 'category': 'girls_night'},
    {'text': 'Never have I ever pretended not to notice something that was blatantly obvious.', 'category': 'girls_night'},
    {'text': 'Never have I ever been completely emotionally destroyed by something tiny.', 'category': 'girls_night'},
    {'text': 'Never have I ever said I\'m fine and cried about it 20 minutes later alone.', 'category': 'girls_night'},
    {'text': 'Never have I ever helped a friend with something they never once thanked me for.', 'category': 'girls_night'},
    {'text': 'Never have I ever felt like the only one making effort in a friendship.', 'category': 'girls_night'},
    {'text': 'Never have I ever moved differently when someone attractive was in the room.', 'category': 'girls_night'},
    {'text': 'Never have I ever told someone I\'d be there in 5 minutes from my bed.', 'category': 'girls_night'},
    {'text': 'Never have I ever felt more connected to a playlist than a person.', 'category': 'girls_night'},
    {'text': 'Never have I ever been the one giving advice while my own life was complete chaos.', 'category': 'girls_night'},
    {'text': 'Never have I ever thought I was unbothered until the other person actually moved on.', 'category': 'girls_night'},
    {'text': 'Never have I ever stared at my own reflection for too long before a night out.', 'category': 'girls_night'},
    {'text': 'Never have I ever turned down a perfectly good person for a completely illogical reason.', 'category': 'girls_night'},
    {'text': 'Never have I ever spent a full evening analyzing one person\'s social media activity.', 'category': 'girls_night'},
    {'text': 'Never have I ever acted unbothered while genuinely spiraling inside.', 'category': 'girls_night'},
    {'text': 'Never have I ever felt beautiful and not known what to do with that feeling.', 'category': 'girls_night'},
    {'text': 'Never have I ever hidden how much something affected me because I didn\'t want to seem weak.', 'category': 'girls_night'},
    {'text': 'Never have I ever felt invisible in a room full of people who supposedly knew me.', 'category': 'girls_night'},
    {'text': 'Never have I ever chosen the wrong person and known it from the very beginning.', 'category': 'girls_night'},
    {'text': 'Never have I ever convinced myself I was okay with something I absolutely was not.', 'category': 'girls_night'},
    {'text': 'Never have I ever wanted to say something and chosen silence instead.', 'category': 'girls_night'},
    {'text': 'Never have I ever chosen my image over my own honest feelings.', 'category': 'girls_night'},
    {'text': 'Never have I ever found it easier to support everyone else than to ask for support myself.', 'category': 'girls_night'},
    {'text': 'Never have I ever been completely honest with a friend and immediately regretted it.', 'category': 'girls_night'},
    {'text': 'Never have I ever let someone treat me a certain way because I didn\'t think I deserved better.', 'category': 'girls_night'},
    {'text': 'Never have I ever had a falling out with a girlfriend that genuinely broke my heart.', 'category': 'girls_night'},
    {'text': 'Never have I ever felt pressure from my own friend group to be someone I wasn\'t.', 'category': 'girls_night'},
    {'text': 'Never have I ever watched someone else get something I deserved and smiled through it.', 'category': 'girls_night'},
    {'text': 'Never have I ever outgrown a friend and grieved it privately.', 'category': 'girls_night'},
    {'text': 'Never have I ever found myself changing to fit someone else\'s idea of who I should be.', 'category': 'girls_night'},
    {'text': 'Never have I ever had a best friendship that ended and never fully understood why.', 'category': 'girls_night'},
    {'text': 'Never have I ever felt genuinely at peace and then immediately got in my own way.', 'category': 'girls_night'},
    {'text': 'Never have I ever looked around at a night out and thought I\'d rather be at home.', 'category': 'girls_night'},
    {'text': 'Never have I ever seen a younger version of myself in someone and wanted to tell them something.', 'category': 'girls_night'},
    {'text': 'Never have I ever felt completely seen by someone I barely knew.', 'category': 'girls_night'},
    {'text': 'Never have I ever prioritized someone else\'s comfort over my own truth.', 'category': 'girls_night'},
    {'text': 'Never have I ever had a moment with a friend that I would relive if I could.', 'category': 'girls_night'},
    {'text': 'Never have I ever been the strongest person in the room while feeling the most fragile.', 'category': 'girls_night'},
    {'text': 'Never have I ever helped someone carry something I was struggling with myself.', 'category': 'girls_night'},
    {'text': 'Never have I ever received kindness I didn\'t ask for and been completely undone by it.', 'category': 'girls_night'},
    {'text': 'Never have I ever heard a song and thought that person wrote it about me.', 'category': 'girls_night'},
    {'text': 'Never have I ever done something quietly kind that I never told anyone about.', 'category': 'girls_night'},
    {'text': 'Never have I ever realized my worth right after letting someone prove I\'d forgotten it.', 'category': 'girls_night'},
    {'text': 'Never have I ever found home in a conversation with someone I\'d just met.', 'category': 'girls_night'},
    {'text': 'Never have I ever stayed in a friendship long after I knew it had already ended.', 'category': 'girls_night'},
    {'text': 'Never have I ever wanted to be chosen by someone and never told them.', 'category': 'girls_night'},
    {'text': 'Never have I ever kept quiet in a situation where I absolutely should have spoken up.', 'category': 'girls_night'},
    {'text': 'Never have I ever felt like the most unknown version of myself in a group of people who knew me.', 'category': 'girls_night'},
    {'text': 'Never have I ever been the most together person in the room while secretly falling apart.', 'category': 'girls_night'},
    {'text': 'Never have I ever wanted to apologize for taking up space.', 'category': 'girls_night'},
    {'text': 'Never have I ever had a moment in a friendship that changed how I saw myself.', 'category': 'girls_night'},
    {'text': 'Never have I ever let someone go because I didn\'t think I was worth staying for.', 'category': 'girls_night'},
    {'text': 'Never have I ever met someone and thought this is what it\'s supposed to feel like.', 'category': 'girls_night'},
    {'text': 'Never have I ever done something brave that nobody ever saw or knew about.', 'category': 'girls_night'},
    {'text': 'Never have I ever cried on the way home from something that looked fine to everyone else.', 'category': 'girls_night'},
    {'text': 'Never have I ever been around people all night and still felt completely alone.', 'category': 'girls_night'},
    {'text': 'Never have I ever realized a friendship was already over before either person said it.', 'category': 'girls_night'},
    {'text': 'Never have I ever loved a version of a friendship I\'ll never have back.', 'category': 'girls_night'},
    {'text': 'Never have I ever been exactly who someone needed me to be at the right moment.', 'category': 'girls_night'},
    {'text': 'Never have I ever pretended to understand something another guy explained just to avoid looking lost.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever given a mate terrible advice and then watched it go wrong.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever said I\'m fine when I was absolutely not fine.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever avoided calling someone back for days and then acted completely normal.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever pretended to be more confident than I actually was.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever chickened out of something I told everyone I was going to do.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever blamed a bad mood on being tired when there was actually a real reason.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever bought something expensive to impress someone.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever exaggerated a story to make myself look better.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been completely lost but refused to ask for help.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever told a girl I was fine with something I absolutely was not fine with.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever stayed in something too long because I didn\'t want to be the one to end it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever acted unbothered after being rejected when I was completely bothered.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever kept feelings to myself for so long they became a problem.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever competed with a mate over the same person.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever taken a backseat in an argument I knew I was winning.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever done something I didn\'t want to do just because the group expected it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever pretended to like a sport just to fit in with someone.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever gotten into something without thinking it through at all.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever felt insecure about something and never mentioned it to anyone.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been jealous of a mate\'s success and said absolutely nothing.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever made a decision based on ego that I later completely regretted.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever cried alone over something and told absolutely no one.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever felt pressure from mates to act a certain way I wasn\'t comfortable with.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever backed down from something because I was scared even though I pretended otherwise.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever had a falling out with a mate over a girl.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever known I was wrong and kept arguing anyway.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever pretended something didn\'t affect me when it absolutely did.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever made an important decision and immediately second-guessed it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been too proud to apologize when I should have.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been the last in a group to realize something everyone else already knew.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever avoided a conversation that I really needed to have.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever felt more competitive about something trivial than I\'d ever admit.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever let a mate down and not dealt with it properly.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever done something risky just to prove something to someone.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever had an injury I made sound much less serious than it was.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever asked for help with something I pretended I could handle alone.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been completely starstruck and acted like it was nothing.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever gotten advice from someone younger and had to admit it was actually good.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever felt genuinely scared about something and acted completely cool.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever avoided gym for so long I had to completely restart.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever said something confident in a group and had absolutely no idea if it was true.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever broken the bro code and hoped no one would find out.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been more affected by a loss than I showed anyone.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever given unsolicited advice and immediately realized I shouldn\'t have.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever looked up to someone I\'d never admit to looking up to.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever panicked about something and told everyone I was relaxed about it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever lost something important and searched for it before admitting it was gone.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been the loudest person in a room while feeling the most out of place.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever needed someone to check in on me and not been able to ask for it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever felt completely disconnected from the version of myself everyone else sees.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever hidden how much something meant to me because I didn\'t want to seem soft.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been proud of something and had no one to share it with.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever put someone else\'s comfort ahead of saying what I actually meant.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been genuinely grateful for a friendship and never told that person.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever achieved something significant and immediately started worrying about the next thing.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever wished I could take back something I said because it came out completely wrong.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been completely honest in a moment that asked for it and felt better for it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever made someone laugh genuinely and carried that feeling all day.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been the reason something worked out even though I got none of the credit.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever had a conversation with a mate that I didn\'t know I needed until I was in it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever helped someone through something while going through the same thing myself.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever stayed quiet when speaking up would have made all the difference.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever had a moment where I surprised myself with how I handled something.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever let someone go who I genuinely think about more than I show.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever had a friendship that made hard things feel manageable.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been exactly the person someone needed me to be.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever done something difficult with no reward and been completely at peace with it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever reached a goal I worked hard for and felt nothing but grateful.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been moved by something and not had the words for it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever stood up for someone quietly and walked away without needing them to know.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever had a moment in sport or competition where everything completely clicked.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever had a conversation that changed my perspective on something important.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever felt fully understood by someone without having to explain myself.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever shown up for someone when it mattered and asked for nothing back.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever done something brave that nobody will ever hear about.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever rebuilt trust with someone and had it be stronger than before.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever had a moment of silence with someone that meant more than any conversation.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been so focused on something that hours passed without me noticing.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever heard someone say exactly the right thing at exactly the right moment.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever changed genuinely for myself and not for anyone else.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever done the right thing when no one was watching.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever received loyalty from someone that I had done nothing specific to earn.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been the person someone else said changed things for them.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever finished something I nearly gave up on.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been at a low point and had someone show up who had no way of knowing.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever built something with someone that meant more than the result.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever realized what I had right at the moment I was about to lose it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever said what I meant completely and been completely understood.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever known something was going to be a defining moment and been right.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever pretended not to care about something I cared deeply about.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever let pride stop me from saying something I should have said.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been the version of someone\'s story that helped them move forward.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever done something consistently for long enough to see it actually change things.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever had a friendship that required nothing and gave everything.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been someone\'s first call and known exactly what that meant.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever had a period of my life where everything clicked and I didn\'t fully appreciate it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever walked away from something that wasn\'t serving me and felt completely right about it.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever been the reason a group of people had a better time.', 'category': 'guys_unleashed'},
    {'text': 'Never have I ever known exactly what I wanted and had the courage to go for it.', 'category': 'guys_unleashed'},
  ];
}
