/// Random challenges database
class RandomData {
  static const List<String> challenges = [
    'Hold a full plank position for 45 seconds — everyone judges your form.',
    'Toss a coin in the air and catch it on your nose — 3 successful attempts required.',
    'Say toy boat 5 times fast without making a single mistake.',
    'Stay in complete silence for a full 2 minutes — anyone who laughs loses.',
    'Name 10 different animals in under 10 seconds.',
    'High five every single person in the room in under 5 seconds.',
    'Spin around exactly 5 times then walk in a perfectly straight line.',
    'Read any paragraph completely backwards letter by letter.',
    'Do a freeze-dance: everyone dances until someone says stop.',
    'Hold an ice cube as long as possible — last one holding wins.',
    'Do 20 situps while someone holds your feet and counts.',
    'Stare at someone without blinking for 30 seconds — first to blink loses.',
    'Balance on one foot for 60 seconds without touching anything.',
    'Do 15 pushups while someone counts down from 15.',
    'Sing any song for 30 seconds while someone tries to make you laugh.',
    'Say the months of the year backwards in under 10 seconds.',
    'Hold a smile for 1 minute while others try to make you frown.',
    'Do 10 burpees as fast as humanly possible.',
    'Balance a full book on your head while doing 10 squats.',
    'Try to snap your fingers 20 times in under 5 seconds.',
    'Clap your hands behind your back 10 times in a row.',
    'Try to walk backwards in a straight line across the room blindfolded.',
    'Name 5 countries beginning with the letter S in under 10 seconds.',
    'Do 30 jumping jacks while counting backwards from 30.',
    'Hold your breath for as long as possible — time yourself.',
    'Touch every wall in the room and return to your spot in under 10 seconds.',
    'Name 10 celebrities in under 8 seconds.',
    'Do the most pushups in 30 seconds — group counts.',
    'Balance 3 different objects on different body parts at the same time.',
    'Recite your phone number backwards correctly in one try.',
    'Do 5 proper cartwheels in a row.',
    'Walk heel to toe in a perfectly straight line across the room.',
    'Name 15 things in a supermarket in under 15 seconds.',
    'Try to whistle a full recognizable song without stopping.',
    'Do a wall sit for a full 60 seconds.',
    'Name all 50 US states in under 2 minutes.',
    'Juggle 3 items for at least 10 full seconds.',
    'Do 25 calf raises as fast as possible.',
    'Name a movie for every letter of the alphabet — you have 3 minutes.',
    'Attempt 5 perfect star jumps in complete slow motion.',
    'Hold your hands completely still for 1 minute — no movement at all.',
    'Do 10 pushups 10 squats and 10 jumping jacks in under 60 seconds.',
    'Name 10 fruits starting with a different letter each time in 15 seconds.',
    'Keep a balloon in the air for 60 seconds without using your hands.',
    'Attempt to pat your head and rub your stomach simultaneously for 30 seconds.',
    'Name a famous person for every letter from A to Z — 3 minutes.',
    'Do 20 mountain climbers as fast as possible.',
    'Stand in the squat position for a full 45 seconds.',
    'Name 12 world capitals in under 20 seconds.',
    'Balance on your hands for as long as you can — best attempt wins.',
    'Name every James Bond film you know in under 60 seconds.',
    'Do 30 seconds of sprint on the spot — maximum speed.',
    'Name 10 things in your bedroom in under 10 seconds.',
    'Complete 20 tricep dips using a chair without stopping.',
    'Name 5 things in 5 different colors in under 10 seconds.',
    'Do a 60-second wall sit while answering trivia questions.',
    'Balance a pencil on your upper lip for 20 seconds.',
    'Name 20 animals in 20 seconds — no repeating.',
    'Try to touch all 4 corners of the room in under 5 seconds.',
    'Do the most situps in 30 seconds — group times and counts.',
    'Keep a straight face while someone tells the funniest joke they know.',
    'Name a sport for every letter of the alphabet — you have 3 minutes.',
    'Complete 15 push-ups with perfect form — group judges the form.',
    'Attempt to say red lorry yellow lorry 5 times fast perfectly.',
    'Do 45 seconds of high knees at maximum speed.',
    'Name 10 musicals in 10 seconds.',
    'Try to fold a piece of paper more than 7 times.',
    'Do 20 seconds of the fastest running on the spot you can manage.',
    'Name every Disney movie you can think of in 60 seconds.',
    'Complete 10 lunges while saying the alphabet at the same time.',
    'Try to do the worm across the room — judged on effort.',
    'Balance a spoon on the end of your nose for 20 seconds.',
    'Name 10 world leaders in 15 seconds.',
    'Do 40 jumping jacks while saying every country you know.',
    'Hold a handstand for as long as you can against the wall.',
    'Name 10 pizza toppings in 8 seconds.',
    'Complete a 30-second plank on your fingertips instead of your palms.',
    'Name all 7 continents and their capital cities — you have 2 minutes.',
    'Attempt to walk backwards in a full circle without stopping.',
    'Do 15 correct diamond pushups in a row without stopping.',
    'Name 10 musicians in 10 seconds.',
    'Try to drink a full glass of water in one continuous go.',
    'Name 5 words that rhyme with each of: blue, star, run.',
    'Complete 20 squat jumps as quickly as possible.',
    'Name 10 things in the room that are white in under 10 seconds.',
    'Do 5 one-armed pushups on your stronger side if possible.',
    'Name 15 countries in Europe in under 15 seconds.',
    'Hold a side plank on each side for 30 seconds.',
    'Do a 45-second plank while answering trivia questions from the group.',
    'Name 10 sports played with a ball in 8 seconds.',
    'Complete 25 rapid-fire pushups while someone counts aloud.',
    'Name every person in the room with one unique fact about them.',
    'Attempt 10 seconds of the fastest invisible jump rope possible.',
    'Do 60 seconds of alternating lunges without stopping.',
    'Name 5 things red, 5 that are blue, 5 that are green — 15 seconds total.',
    'Attempt your personal best in a 30-second pushup contest.',
    'Name every person in the room without looking at them — eyes closed.',
    'Do a plank while the group asks you 5 rapid fire trivia questions.',
    'Name 10 board games in under 10 seconds.',
    'Hold a squat while reciting the alphabet — if you stand up you start over.',
  ];
}
