/// Trivia question database
class TriviaData {
  static const List<Map<String, dynamic>> questions = [
    {'q': 'What planet is closest to the Sun?', 'a': 'Mercury', 'category': 'party_starter'},
    {'q': 'How many sides does a hexagon have?', 'a': '6', 'category': 'party_starter'},
    {'q': 'What is the largest ocean on Earth?', 'a': 'Pacific', 'category': 'party_starter'},
    {'q': 'Who painted the Mona Lisa?', 'a': 'Leonardo da Vinci', 'category': 'party_starter'},
    {'q': 'What gas do plants absorb from the atmosphere?', 'a': 'Carbon Dioxide', 'category': 'party_starter'},
    {'q': 'How many bones are in the adult human body?', 'a': '206', 'category': 'party_starter'},
    {'q': 'What is the capital city of Japan?', 'a': 'Tokyo', 'category': 'party_starter'},
    {'q': 'Which animal is the fastest on land?', 'a': 'Cheetah', 'category': 'party_starter'},
    {'q': 'How many strings does a standard guitar have?', 'a': '6', 'category': 'party_starter'},
    {'q': 'What is 12 multiplied by 12?', 'a': '144', 'category': 'party_starter'},
    {'q': 'What color do you get when you mix red and blue?', 'a': 'Purple', 'category': 'party_starter'},
    {'q': 'How many continents are there on Earth?', 'a': '7', 'category': 'party_starter'},
    {'q': 'What is the chemical symbol for Gold?', 'a': 'Au', 'category': 'party_starter'},
    {'q': 'Which country is the largest by total area?', 'a': 'Russia', 'category': 'party_starter'},
    {'q': 'How many hours are in one full week?', 'a': '168', 'category': 'party_starter'},
    {'q': 'What is the longest river in the world?', 'a': 'Nile', 'category': 'party_starter'},
    {'q': 'Who wrote the play Romeo and Juliet?', 'a': 'William Shakespeare', 'category': 'party_starter'},
    {'q': 'What is the hardest natural substance on Earth?', 'a': 'Diamond', 'category': 'party_starter'},
    {'q': 'How many planets are in our Solar System?', 'a': '8', 'category': 'party_starter'},
    {'q': 'What is the capital of Australia?', 'a': 'Canberra', 'category': 'party_starter'},
    {'q': 'How many sides does a triangle have?', 'a': '3', 'category': 'party_starter'},
    {'q': 'What is the approximate speed of light?', 'a': '300,000 km/s', 'category': 'party_starter'},
    {'q': 'Which element has the symbol O?', 'a': 'Oxygen', 'category': 'party_starter'},
    {'q': 'What year did World War II end?', 'a': '1945', 'category': 'party_starter'},
    {'q': 'How many players are on a standard football (soccer) team?', 'a': '11', 'category': 'party_starter'},
    {'q': 'What is the smallest country in the world?', 'a': 'Vatican City', 'category': 'party_starter'},
    {'q': 'Which planet is known as the Red Planet?', 'a': 'Mars', 'category': 'party_starter'},
    {'q': 'What language is spoken in Brazil?', 'a': 'Portuguese', 'category': 'party_starter'},
    {'q': 'How many teeth does a healthy adult have?', 'a': '32', 'category': 'party_starter'},
    {'q': 'What is the currency of Japan?', 'a': 'Yen', 'category': 'party_starter'},
    {'q': 'Which organ pumps blood through the human body?', 'a': 'Heart', 'category': 'party_starter'},
    {'q': 'What is 2 to the power of 10?', 'a': '1024', 'category': 'party_starter'},
    {'q': 'How many colors are in a standard rainbow?', 'a': '7', 'category': 'party_starter'},
    {'q': 'What is the tallest mountain in the world?', 'a': 'Mount Everest', 'category': 'party_starter'},
    {'q': 'What metal is liquid at room temperature?', 'a': 'Mercury', 'category': 'party_starter'},
    {'q': 'How many seconds are there in one hour?', 'a': '3600', 'category': 'party_starter'},
    {'q': 'Who was the first person to walk on the Moon?', 'a': 'Neil Armstrong', 'category': 'party_starter'},
    {'q': 'What is the national animal of Australia?', 'a': 'Kangaroo', 'category': 'party_starter'},
    {'q': 'What vitamin does sunlight help produce in the body?', 'a': 'Vitamin D', 'category': 'party_starter'},
    {'q': 'How many degrees are in a full circle?', 'a': '360', 'category': 'party_starter'},
    {'q': 'What is the world\'s most spoken language by native speakers?', 'a': 'Mandarin Chinese', 'category': 'party_starter'},
    {'q': 'How many chambers does the human heart have?', 'a': '4', 'category': 'party_starter'},
    {'q': 'What gas makes up most of Earth\'s atmosphere?', 'a': 'Nitrogen', 'category': 'party_starter'},
    {'q': 'What is the chemical formula for water?', 'a': 'H2O', 'category': 'party_starter'},
    {'q': 'Which country invented pizza?', 'a': 'Italy', 'category': 'party_starter'},
    {'q': 'How many bones are in the human hand?', 'a': '27', 'category': 'party_starter'},
    {'q': 'What is the most abundant metal in Earth\'s crust?', 'a': 'Aluminium', 'category': 'party_starter'},
    {'q': 'What year was the first iPhone released?', 'a': '2007', 'category': 'party_starter'},
    {'q': 'How many letters are in the English alphabet?', 'a': '26', 'category': 'party_starter'},
    {'q': 'Which country has the most natural lakes?', 'a': 'Canada', 'category': 'party_starter'},
    {'q': 'How many days are in a leap year?', 'a': '366', 'category': 'party_starter'},
    {'q': 'What is the longest bone in the human body?', 'a': 'Femur', 'category': 'party_starter'},
    {'q': 'Which instrument has 88 keys?', 'a': 'Piano', 'category': 'party_starter'},
    {'q': 'What does HTTP stand for?', 'a': 'HyperText Transfer Protocol', 'category': 'party_starter'},
    {'q': 'How many sides does a pentagon have?', 'a': '5', 'category': 'party_starter'},
    {'q': 'What is the fastest bird on Earth?', 'a': 'Peregrine Falcon', 'category': 'party_starter'},
    {'q': 'Which planet has the most moons?', 'a': 'Saturn', 'category': 'party_starter'},
    {'q': 'How many zeros are in one million?', 'a': '6', 'category': 'party_starter'},
    {'q': 'What is the square root of 144?', 'a': '12', 'category': 'party_starter'},
    {'q': 'Which gas is known as laughing gas?', 'a': 'Nitrous Oxide', 'category': 'party_starter'},
    {'q': 'What is the smallest planet in our solar system?', 'a': 'Mercury', 'category': 'party_starter'},
    {'q': 'Who invented the telephone?', 'a': 'Alexander Graham Bell', 'category': 'party_starter'},
    {'q': 'How many players are on a basketball team?', 'a': '5', 'category': 'party_starter'},
    {'q': 'What is the capital of France?', 'a': 'Paris', 'category': 'party_starter'},
    {'q': 'Which ocean is the smallest?', 'a': 'Arctic Ocean', 'category': 'party_starter'},
    {'q': 'What year did the Titanic sink?', 'a': '1912', 'category': 'party_starter'},
    {'q': 'How many strings on a violin?', 'a': '4', 'category': 'party_starter'},
    {'q': 'What is the largest organ in the human body?', 'a': 'Skin', 'category': 'party_starter'},
    {'q': 'What is the rarest blood type?', 'a': 'AB negative', 'category': 'party_starter'},
    {'q': 'Which country is known as the Land of the Rising Sun?', 'a': 'Japan', 'category': 'party_starter'},
    {'q': 'What does NASA stand for?', 'a': 'National Aeronautics and Space Administration', 'category': 'party_starter'},
    {'q': 'How many holes are in a standard game of golf?', 'a': '18', 'category': 'party_starter'},
    {'q': 'What is the world\'s largest desert?', 'a': 'Antarctic Desert', 'category': 'party_starter'},
    {'q': 'What is the atomic number of hydrogen?', 'a': '1', 'category': 'party_starter'},
    {'q': 'Which element is a diamond made of?', 'a': 'Carbon', 'category': 'party_starter'},
    {'q': 'How many humps does a Bactrian camel have?', 'a': '2', 'category': 'party_starter'},
    {'q': 'What is the main ingredient in guacamole?', 'a': 'Avocado', 'category': 'party_starter'},
    {'q': 'How many Olympic rings are there?', 'a': '5', 'category': 'party_starter'},
    {'q': 'Which country gave the Statue of Liberty to the USA?', 'a': 'France', 'category': 'party_starter'},
    {'q': 'What is the currency of the United Kingdom?', 'a': 'Pound Sterling', 'category': 'party_starter'},
    {'q': 'What is the boiling point of water in Celsius?', 'a': '100°C', 'category': 'party_starter'},
    {'q': 'What country is home to the Great Barrier Reef?', 'a': 'Australia', 'category': 'party_starter'},
    {'q': 'How long does it take light to travel from the Sun to Earth?', 'a': 'About 8 minutes', 'category': 'party_starter'},
    {'q': 'Which is the only mammal capable of true flight?', 'a': 'Bat', 'category': 'party_starter'},
    {'q': 'How many hearts does an octopus have?', 'a': '3', 'category': 'party_starter'},
    {'q': 'What is the name of the galaxy we live in?', 'a': 'Milky Way', 'category': 'party_starter'},
    {'q': 'Which country has the longest coastline in the world?', 'a': 'Canada', 'category': 'party_starter'},
    {'q': 'What is the tallest type of grass?', 'a': 'Bamboo', 'category': 'party_starter'},
    {'q': 'How many sides does a dodecagon have?', 'a': '12', 'category': 'party_starter'},
    {'q': 'Which fruit is known as the king of fruits?', 'a': 'Mango', 'category': 'party_starter'},
    {'q': 'How many teeth does an adult dog have?', 'a': '42', 'category': 'party_starter'},
    {'q': 'What is the largest internal organ in the human body?', 'a': 'Liver', 'category': 'party_starter'},
    {'q': 'How many players are in a standard rugby union team?', 'a': '15', 'category': 'party_starter'},
    {'q': 'What is the capital of Canada?', 'a': 'Ottawa', 'category': 'party_starter'},
    {'q': 'What does DNA stand for?', 'a': 'Deoxyribonucleic Acid', 'category': 'party_starter'},
    {'q': 'How many faces does a cube have?', 'a': '6', 'category': 'party_starter'},
    {'q': 'What is the most widely spoken language in Africa?', 'a': 'Swahili', 'category': 'party_starter'},
    {'q': 'Which country has won the most FIFA World Cups?', 'a': 'Brazil', 'category': 'party_starter'},
    {'q': 'How many minutes are there in a full day?', 'a': '1440', 'category': 'party_starter'},
    {'q': 'What is the chemical symbol for Silver?', 'a': 'Ag', 'category': 'party_starter'},
    {'q': 'What does DM stand for in social media?', 'a': 'Direct Message', 'category': 'mild_but_wild'},
    {'q': 'Which app first introduced the swipe right concept for dating?', 'a': 'Tinder', 'category': 'mild_but_wild'},
    {'q': 'What does FOMO stand for?', 'a': 'Fear Of Missing Out', 'category': 'mild_but_wild'},
    {'q': 'Which city is known as the City of Love?', 'a': 'Paris', 'category': 'mild_but_wild'},
    {'q': 'What is the most popular dating app in the world?', 'a': 'Tinder', 'category': 'mild_but_wild'},
    {'q': 'What does LOL mean?', 'a': 'Laughing Out Loud', 'category': 'mild_but_wild'},
    {'q': 'Which month has the most weddings globally?', 'a': 'June', 'category': 'mild_but_wild'},
    {'q': 'In astrology what is the first sign of the zodiac?', 'a': 'Aries', 'category': 'mild_but_wild'},
    {'q': 'What colour roses traditionally represent romance?', 'a': 'Red', 'category': 'mild_but_wild'},
    {'q': 'What does PDF stand for?', 'a': 'Portable Document Format', 'category': 'mild_but_wild'},
    {'q': 'What app uses the ghost as its logo?', 'a': 'Snapchat', 'category': 'mild_but_wild'},
    {'q': 'What does OTP mean in fan culture?', 'a': 'One True Pairing', 'category': 'mild_but_wild'},
    {'q': 'What is the most used emoji globally?', 'a': '😂', 'category': 'mild_but_wild'},
    {'q': 'What is a love language according to Gary Chapman?', 'a': 'Words of Affirmation', 'category': 'mild_but_wild'},
    {'q': 'What does ghosting mean in dating?', 'a': 'Disappearing without explanation', 'category': 'mild_but_wild'},
    {'q': 'In which country did Valentine\'s Day originate?', 'a': 'England', 'category': 'mild_but_wild'},
    {'q': 'What app is known for its Reels feature?', 'a': 'Instagram', 'category': 'mild_but_wild'},
    {'q': 'What does breadcrumbing mean in dating?', 'a': 'Giving minimal attention to keep someone interested', 'category': 'mild_but_wild'},
    {'q': 'What was the first major social media platform?', 'a': 'MySpace', 'category': 'mild_but_wild'},
    {'q': 'What does NGL stand for in texting?', 'a': 'Not Gonna Lie', 'category': 'mild_but_wild'},
    {'q': 'In which film does the line You had me at hello appear?', 'a': 'Jerry Maguire', 'category': 'mild_but_wild'},
    {'q': 'What is the term for keeping someone as a backup option in dating?', 'a': 'Benching', 'category': 'mild_but_wild'},
    {'q': 'How many love languages did Gary Chapman identify?', 'a': '5', 'category': 'mild_but_wild'},
    {'q': 'What does it mean when someone orbits you?', 'a': 'They watch your stories but don\'t text', 'category': 'mild_but_wild'},
    {'q': 'Which zodiac sign is known as the most romantic?', 'a': 'Pisces', 'category': 'mild_but_wild'},
    {'q': 'What is the term for dating someone new very soon after a breakup?', 'a': 'Rebound', 'category': 'mild_but_wild'},
    {'q': 'What does soft launching someone mean?', 'a': 'Subtly showing someone on social media', 'category': 'mild_but_wild'},
    {'q': 'Which platform is known for short videos?', 'a': 'TikTok', 'category': 'mild_but_wild'},
    {'q': 'What does IRL mean?', 'a': 'In Real Life', 'category': 'mild_but_wild'},
    {'q': 'What does situationship mean?', 'a': 'An undefined romantic situation', 'category': 'mild_but_wild'},
    {'q': 'Which year was Instagram launched?', 'a': '2010', 'category': 'mild_but_wild'},
    {'q': 'What does IYKYK mean?', 'a': 'If You Know You Know', 'category': 'mild_but_wild'},
    {'q': 'What is the term for posting vague updates after a breakup?', 'a': 'Subtweeting', 'category': 'mild_but_wild'},
    {'q': 'What does catching flights not feelings mean?', 'a': 'Preferring travel to commitment', 'category': 'mild_but_wild'},
    {'q': 'Which film popularised the phrase He\'s just not that into you?', 'a': 'He\'s Just Not That Into You', 'category': 'mild_but_wild'},
    {'q': 'What does low-key mean in modern slang?', 'a': 'Quietly or secretly', 'category': 'mild_but_wild'},
    {'q': 'What does main character energy mean?', 'a': 'Acting as if your life is a movie', 'category': 'mild_but_wild'},
    {'q': 'What does rizz mean in modern slang?', 'a': 'Natural charm and charisma', 'category': 'mild_but_wild'},
    {'q': 'What does delulu mean in internet slang?', 'a': 'Delusional beliefs about a situation', 'category': 'mild_but_wild'},
    {'q': 'What does GNO stand for?', 'a': 'Girls Night Out', 'category': 'mild_but_wild'},
    {'q': 'What does he\'s giving mean in modern slang?', 'a': 'Giving off a vibe or energy', 'category': 'mild_but_wild'},
    {'q': 'What year was TikTok launched internationally?', 'a': '2018', 'category': 'mild_but_wild'},
    {'q': 'Which love language involves doing tasks for someone?', 'a': 'Acts of Service', 'category': 'mild_but_wild'},
    {'q': 'What does talking stage refer to?', 'a': 'Early phase before dating officially', 'category': 'mild_but_wild'},
    {'q': 'What does no cap mean?', 'a': 'No lie, for real', 'category': 'mild_but_wild'},
    {'q': 'What does slay mean in modern context?', 'a': 'To do something impressively well', 'category': 'mild_but_wild'},
    {'q': 'What does vibe check mean?', 'a': 'Assessing someone\'s energy or attitude', 'category': 'mild_but_wild'},
    {'q': 'What does understood the assignment mean?', 'a': 'Did exactly what was expected perfectly', 'category': 'mild_but_wild'},
    {'q': 'What does GRWM stand for in content?', 'a': 'Get Ready With Me', 'category': 'mild_but_wild'},
    {'q': 'What does hot girl summer mean?', 'a': 'Being unapologetically confident and free', 'category': 'mild_but_wild'},
    {'q': 'What does shoot your shot mean?', 'a': 'Make a move on someone', 'category': 'mild_but_wild'},
    {'q': 'What is a red flag in a relationship context?', 'a': 'A warning sign in someone\'s behavior', 'category': 'mild_but_wild'},
    {'q': 'What does green flag mean in dating?', 'a': 'A positive and healthy trait', 'category': 'mild_but_wild'},
    {'q': 'What is love bombing?', 'a': 'Overwhelming someone with affection to manipulate them', 'category': 'mild_but_wild'},
    {'q': 'What does gaslighting mean?', 'a': 'Making someone question their own reality', 'category': 'mild_but_wild'},
    {'q': 'What does toxic trait typically refer to?', 'a': 'A harmful behavioral pattern', 'category': 'mild_but_wild'},
    {'q': 'What does era mean in modern social media context?', 'a': 'A phase or chapter someone is in', 'category': 'mild_but_wild'},
    {'q': 'What does energy vampire mean in slang?', 'a': 'Someone who drains your positivity', 'category': 'mild_but_wild'},
    {'q': 'What is manifesting in popular culture?', 'a': 'Believing and visualizing something to attract it', 'category': 'mild_but_wild'},
    {'q': 'What does it\'s giving typically complete to?', 'a': 'A certain vibe or feeling', 'category': 'mild_but_wild'},
    {'q': 'What does FWB mean?', 'a': 'Friends With Benefits', 'category': 'mild_but_wild'},
    {'q': 'What does obsessed mean in positive internet slang?', 'a': 'Extremely loving or admiring something', 'category': 'mild_but_wild'},
    {'q': 'What does WYD mean in text?', 'a': 'What You Doing', 'category': 'mild_but_wild'},
    {'q': 'What does HMU mean?', 'a': 'Hit Me Up', 'category': 'mild_but_wild'},
    {'q': 'What does SMH mean?', 'a': 'Shaking My Head', 'category': 'mild_but_wild'},
    {'q': 'What does OOTD stand for?', 'a': 'Outfit Of The Day', 'category': 'mild_but_wild'},
    {'q': 'What does rent free mean in living rent free in my head?', 'a': 'Thinking about someone constantly', 'category': 'mild_but_wild'},
    {'q': 'What does glow up mean?', 'a': 'A significant positive transformation', 'category': 'mild_but_wild'},
    {'q': 'What is a bare minimum partner?', 'a': 'Someone who does the least acceptable amount', 'category': 'mild_but_wild'},
    {'q': 'What does normalize mean in social media captions?', 'a': 'Remove a stigma by discussing it openly', 'category': 'mild_but_wild'},
    {'q': 'What does periodt mean in internet slang?', 'a': 'End of sentence for emphasis', 'category': 'mild_but_wild'},
    {'q': 'What does catch feelings mean?', 'a': 'Developing romantic feelings unexpectedly', 'category': 'mild_but_wild'},
    {'q': 'What does lowkey obsessed mean?', 'a': 'Slightly obsessed in a casual way', 'category': 'mild_but_wild'},
    {'q': 'What does that\'s so real mean in response to something?', 'a': 'Strongly agreeing with someone', 'category': 'mild_but_wild'},
    {'q': 'What does in my feelings mean?', 'a': 'Being emotionally affected', 'category': 'mild_but_wild'},
    {'q': 'What does woke up and chose violence mean?', 'a': 'Deciding to be provocative or chaotic that day', 'category': 'mild_but_wild'},
    {'q': 'What does core memory mean in social media?', 'a': 'A deeply memorable formative experience', 'category': 'mild_but_wild'},
    {'q': 'What does that gave me serotonin mean?', 'a': 'Something that made you genuinely happy', 'category': 'mild_but_wild'},
    {'q': 'What does unhinged mean in a positive internet context?', 'a': 'Wildly chaotic or funny in an entertaining way', 'category': 'mild_but_wild'},
    {'q': 'What does this is so you mean as a compliment?', 'a': 'Something perfectly matches someone\'s personality', 'category': 'mild_but_wild'},
    {'q': 'What does villain era mean?', 'a': 'Prioritizing yourself unapologetically', 'category': 'mild_but_wild'},
    {'q': 'What does bestie energy mean?', 'a': 'Acting with warm supportive best-friend behavior', 'category': 'mild_but_wild'},
    {'q': 'What does normalize mean when used online?', 'a': 'Make something acceptable or remove its stigma', 'category': 'mild_but_wild'},
    {'q': 'What does chronically online mean?', 'a': 'Spending excessive time online', 'category': 'mild_but_wild'},
    {'q': 'What does we don\'t talk about Bruno reference?', 'a': 'The Encanto film song', 'category': 'mild_but_wild'},
    {'q': 'What does this is not for me mean in modern review culture?', 'a': 'A polite way of saying you disliked something', 'category': 'mild_but_wild'},
    {'q': 'What does living your best life mean?', 'a': 'Fully enjoying and embracing your happiness', 'category': 'mild_but_wild'},
    {'q': 'What does it\'s giving main character energy mean?', 'a': 'Acting as if you\'re the central figure of your narrative', 'category': 'mild_but_wild'},
    {'q': 'What does era is over mean in a personal context?', 'a': 'Moving on from a previous phase of your life', 'category': 'mild_but_wild'},
    {'q': 'What is soft life?', 'a': 'Living comfortably without unnecessary stress', 'category': 'mild_but_wild'},
    {'q': 'What does the ick mean in modern dating?', 'a': 'Sudden loss of attraction triggered by a minor thing', 'category': 'mild_but_wild'},
    {'q': 'What does dry texting mean?', 'a': 'Short one-word boring replies in conversation', 'category': 'mild_but_wild'},
    {'q': 'What does zombie-ing mean in dating?', 'a': 'When someone who ghosted you suddenly reappears', 'category': 'mild_but_wild'},
    {'q': 'What is cushioning in dating?', 'a': 'Keeping backup options while in a relationship', 'category': 'mild_but_wild'},
    {'q': 'What does micro-cheating refer to?', 'a': 'Small acts of emotional infidelity', 'category': 'mild_but_wild'},
    {'q': 'What is paperclipping in dating?', 'a': 'Randomly checking in after going quiet', 'category': 'mild_but_wild'},
    {'q': 'What does cuffing season mean?', 'a': 'Autumn/winter period when people seek relationships', 'category': 'mild_but_wild'},
    {'q': 'What does slow fade mean in dating?', 'a': 'Gradually reducing contact without formally ending things', 'category': 'mild_but_wild'},
    {'q': 'What does stashing mean in relationships?', 'a': 'Hiding a partner from friends and family', 'category': 'mild_but_wild'},
    {'q': 'What does negging mean?', 'a': 'Giving backhanded compliments to create insecurity', 'category': 'mild_but_wild'},
    {'q': 'What is the longest running animated family TV show?', 'a': 'The Simpsons', 'category': 'family_night'},
    {'q': 'What game involves moving colored pegs on a board to guess a code?', 'a': 'Mastermind', 'category': 'family_night'},
    {'q': 'How many players do you need minimum to play Monopoly?', 'a': '2', 'category': 'family_night'},
    {'q': 'In chess which piece can only move diagonally?', 'a': 'Bishop', 'category': 'family_night'},
    {'q': 'What is the name of Simba\'s father in The Lion King?', 'a': 'Mufasa', 'category': 'family_night'},
    {'q': 'How many cards are in a standard deck?', 'a': '52', 'category': 'family_night'},
    {'q': 'What color is Shrek?', 'a': 'Green', 'category': 'family_night'},
    {'q': 'What does a thermometer measure?', 'a': 'Temperature', 'category': 'family_night'},
    {'q': 'Which vegetable is associated with Popeye?', 'a': 'Spinach', 'category': 'family_night'},
    {'q': 'What board game involves buying properties?', 'a': 'Monopoly', 'category': 'family_night'},
    {'q': 'Which Disney princess has the longest hair?', 'a': 'Rapunzel', 'category': 'family_night'},
    {'q': 'How many colors are on a standard Rubik\'s Cube?', 'a': '6', 'category': 'family_night'},
    {'q': 'What is the name of Peppa Pig\'s best friend?', 'a': 'Suzy Sheep', 'category': 'family_night'},
    {'q': 'What fruit is said to keep the doctor away?', 'a': 'Apple', 'category': 'family_night'},
    {'q': 'How many squares are on a standard chess board?', 'a': '64', 'category': 'family_night'},
    {'q': 'Which country is famous for the Eiffel Tower?', 'a': 'France', 'category': 'family_night'},
    {'q': 'What animal is known for its hump?', 'a': 'Camel', 'category': 'family_night'},
    {'q': 'What is the opposite of north?', 'a': 'South', 'category': 'family_night'},
    {'q': 'Which color has the longest wavelength in visible light?', 'a': 'Red', 'category': 'family_night'},
    {'q': 'How many players are on a netball team?', 'a': '7', 'category': 'family_night'},
    {'q': 'What does a caterpillar turn into?', 'a': 'Butterfly', 'category': 'family_night'},
    {'q': 'What is the name of the fairy in Peter Pan?', 'a': 'Tinker Bell', 'category': 'family_night'},
    {'q': 'How many days are in a non-leap year?', 'a': '365', 'category': 'family_night'},
    {'q': 'What type of fish is Nemo?', 'a': 'Clownfish', 'category': 'family_night'},
    {'q': 'How many legs does a spider have?', 'a': '8', 'category': 'family_night'},
    {'q': 'Which planet is famous for its rings?', 'a': 'Saturn', 'category': 'family_night'},
    {'q': 'What is the largest land animal?', 'a': 'Elephant', 'category': 'family_night'},
    {'q': 'What do bees produce?', 'a': 'Honey', 'category': 'family_night'},
    {'q': 'What is the name of the toy cowboy in Toy Story?', 'a': 'Woody', 'category': 'family_night'},
    {'q': 'What is the capital of Italy?', 'a': 'Rome', 'category': 'family_night'},
    {'q': 'How many primary colors are there?', 'a': '3', 'category': 'family_night'},
    {'q': 'What animal is known as man\'s best friend?', 'a': 'Dog', 'category': 'family_night'},
    {'q': 'How many seasons are in a year?', 'a': '4', 'category': 'family_night'},
    {'q': 'What do you call a baby cat?', 'a': 'Kitten', 'category': 'family_night'},
    {'q': 'In Frozen what are Elsa\'s powers?', 'a': 'Ice and snow', 'category': 'family_night'},
    {'q': 'What is the fastest land animal?', 'a': 'Cheetah', 'category': 'family_night'},
    {'q': 'What color is the sky on a clear day?', 'a': 'Blue', 'category': 'family_night'},
    {'q': 'What do plants need to grow?', 'a': 'Sunlight water and soil', 'category': 'family_night'},
    {'q': 'How many letters are in the word FAMILY?', 'a': '6', 'category': 'family_night'},
    {'q': 'What is the name of Harry Potter\'s pet owl?', 'a': 'Hedwig', 'category': 'family_night'},
    {'q': 'How many colors are in a Rainbow?', 'a': '7', 'category': 'family_night'},
    {'q': 'What do you call a group of fish?', 'a': 'School', 'category': 'family_night'},
    {'q': 'What instrument has black and white keys?', 'a': 'Piano', 'category': 'family_night'},
    {'q': 'How many fingers does a human have in total?', 'a': '10', 'category': 'family_night'},
    {'q': 'What does the sun give us?', 'a': 'Light and heat', 'category': 'family_night'},
    {'q': 'What is the biggest planet in our solar system?', 'a': 'Jupiter', 'category': 'family_night'},
    {'q': 'How many letters are in the alphabet?', 'a': '26', 'category': 'family_night'},
    {'q': 'What noise does a cow make?', 'a': 'Moo', 'category': 'family_night'},
    {'q': 'What is 10 plus 10?', 'a': '20', 'category': 'family_night'},
    {'q': 'What shape has 4 equal sides?', 'a': 'Square', 'category': 'family_night'},
    {'q': 'What do butterflies come from?', 'a': 'Cocoons', 'category': 'family_night'},
    {'q': 'What is water made of?', 'a': 'Hydrogen and oxygen', 'category': 'family_night'},
    {'q': 'What is the name of the bear in Jungle Book?', 'a': 'Baloo', 'category': 'family_night'},
    {'q': 'What do you use to write on a blackboard?', 'a': 'Chalk', 'category': 'family_night'},
    {'q': 'Which bird cannot fly but can swim?', 'a': 'Penguin', 'category': 'family_night'},
    {'q': 'How many minutes are in an hour?', 'a': '60', 'category': 'family_night'},
    {'q': 'What game requires you to not get caught moving?', 'a': 'Grandma\'s footsteps', 'category': 'family_night'},
    {'q': 'What is the capital of Spain?', 'a': 'Madrid', 'category': 'family_night'},
    {'q': 'What animal has a very long neck?', 'a': 'Giraffe', 'category': 'family_night'},
    {'q': 'How many eyes does a bee have?', 'a': '5', 'category': 'family_night'},
    {'q': 'What do you call a group of lions?', 'a': 'Pride', 'category': 'family_night'},
    {'q': 'What shape is a wheel?', 'a': 'Circle', 'category': 'family_night'},
    {'q': 'What does 2 times 5 equal?', 'a': '10', 'category': 'family_night'},
    {'q': 'What is the color of grass?', 'a': 'Green', 'category': 'family_night'},
    {'q': 'What do you call a baby dog?', 'a': 'Puppy', 'category': 'family_night'},
    {'q': 'How many wheels does a bicycle have?', 'a': '2', 'category': 'family_night'},
    {'q': 'What comes after Tuesday?', 'a': 'Wednesday', 'category': 'family_night'},
    {'q': 'What is the name of the villain in The Little Mermaid?', 'a': 'Ursula', 'category': 'family_night'},
    {'q': 'How many wheels does a car have?', 'a': '4', 'category': 'family_night'},
    {'q': 'What animal says Oink?', 'a': 'Pig', 'category': 'family_night'},
    {'q': 'What is the name of the game where you pull sticks without moving others?', 'a': 'Kerplunk', 'category': 'family_night'},
    {'q': 'What does a clock measure?', 'a': 'Time', 'category': 'family_night'},
    {'q': 'What is the name of the snowman in Frozen?', 'a': 'Olaf', 'category': 'family_night'},
    {'q': 'What is 5 times 5?', 'a': '25', 'category': 'family_night'},
    {'q': 'Which color is the sky at sunset?', 'a': 'Orange and pink', 'category': 'family_night'},
    {'q': 'What language is most widely spoken in South America?', 'a': 'Spanish', 'category': 'family_night'},
    {'q': 'What do you call a person who fixes teeth?', 'a': 'Dentist', 'category': 'family_night'},
    {'q': 'How many sides does a star shape typically have?', 'a': '5', 'category': 'family_night'},
    {'q': 'What do you call a group of wolves?', 'a': 'Pack', 'category': 'family_night'},
    {'q': 'What is the most popular sport in the world?', 'a': 'Football/Soccer', 'category': 'family_night'},
    {'q': 'What is 100 divided by 10?', 'a': '10', 'category': 'family_night'},
    {'q': 'What is the name of Winnie the Pooh\'s donkey friend?', 'a': 'Eeyore', 'category': 'family_night'},
    {'q': 'What is the name of the cat in Tom and Jerry?', 'a': 'Tom', 'category': 'family_night'},
    {'q': 'How many sides does a cube have?', 'a': '6', 'category': 'family_night'},
    {'q': 'What animal is Dumbo?', 'a': 'Elephant', 'category': 'family_night'},
    {'q': 'What do you call a person who teaches children?', 'a': 'Teacher', 'category': 'family_night'},
    {'q': 'What is the name of Snow White\'s seven companions?', 'a': 'The Seven Dwarfs', 'category': 'family_night'},
    {'q': 'What comes after winter?', 'a': 'Spring', 'category': 'family_night'},
    {'q': 'What animal says Baa?', 'a': 'Sheep', 'category': 'family_night'},
    {'q': 'How many letters are in the word RAINBOW?', 'a': '7', 'category': 'family_night'},
    {'q': 'What do you put on bread to make toast?', 'a': 'Heat or a toaster', 'category': 'family_night'},
    {'q': 'What color is a banana?', 'a': 'Yellow', 'category': 'family_night'},
    {'q': 'What is the capital of Germany?', 'a': 'Berlin', 'category': 'family_night'},
    {'q': 'How many sides does an octagon have?', 'a': '8', 'category': 'family_night'},
    {'q': 'What does a sunflower follow during the day?', 'a': 'The sun', 'category': 'family_night'},
    {'q': 'What is the name of the pirate in Peter Pan?', 'a': 'Captain Hook', 'category': 'family_night'},
    {'q': 'How many legs does a horse have?', 'a': '4', 'category': 'family_night'},
    {'q': 'What instrument do you blow into to make sound?', 'a': 'Trumpet', 'category': 'family_night'},
    {'q': 'What is the capital of Brazil?', 'a': 'Brasilia', 'category': 'family_night'},
    {'q': 'How many wheels does a tricycle have?', 'a': '3', 'category': 'family_night'},
    {'q': 'What does FWB mean in a dating context?', 'a': 'Friends With Benefits', 'category': 'spice_it_up'},
    {'q': 'What is a situationship?', 'a': 'An undefined romantic situation', 'category': 'spice_it_up'},
    {'q': 'What does DTR mean?', 'a': 'Define The Relationship', 'category': 'spice_it_up'},
    {'q': 'What does ONS stand for?', 'a': 'One Night Stand', 'category': 'spice_it_up'},
    {'q': 'What is orbiting in dating?', 'a': 'Watching someone\'s stories without texting', 'category': 'spice_it_up'},
    {'q': 'What does catching feelings mean?', 'a': 'Developing unexpected romantic feelings', 'category': 'spice_it_up'},
    {'q': 'What is love bombing?', 'a': 'Overwhelming someone with affection to manipulate', 'category': 'spice_it_up'},
    {'q': 'What is the term for an undefined romantic relationship?', 'a': 'Situationship', 'category': 'spice_it_up'},
    {'q': 'What does benching mean in dating?', 'a': 'Keeping someone as a backup option', 'category': 'spice_it_up'},
    {'q': 'What does attachment style refer to in psychology?', 'a': 'How someone relates emotionally in relationships', 'category': 'spice_it_up'},
    {'q': 'What is an anxious attachment style?', 'a': 'Needing constant reassurance in relationships', 'category': 'spice_it_up'},
    {'q': 'What does avoidant attachment mean?', 'a': 'Pulling away from closeness in relationships', 'category': 'spice_it_up'},
    {'q': 'What is gaslighting in relationships?', 'a': 'Making someone question their perception of reality', 'category': 'spice_it_up'},
    {'q': 'What does NSA mean in a relationship context?', 'a': 'No Strings Attached', 'category': 'spice_it_up'},
    {'q': 'What is the slow fade in dating?', 'a': 'Gradually reducing contact without formally ending things', 'category': 'spice_it_up'},
    {'q': 'What does keeping it casual typically mean?', 'a': 'Not committing to a relationship', 'category': 'spice_it_up'},
    {'q': 'What is cushioning in dating?', 'a': 'Keeping backup options while in a relationship', 'category': 'spice_it_up'},
    {'q': 'What does exclusive mean in a dating context?', 'a': 'Only dating each other', 'category': 'spice_it_up'},
    {'q': 'What is the talking stage?', 'a': 'The phase before officially dating', 'category': 'spice_it_up'},
    {'q': 'What does body count refer to in casual conversation?', 'a': 'Number of romantic or sexual partners', 'category': 'spice_it_up'},
    {'q': 'What is paperclipping in modern dating?', 'a': 'Randomly checking in on someone after going quiet', 'category': 'spice_it_up'},
    {'q': 'What does she\'s out of my league mean?', 'a': 'Someone considered too impressive for someone else', 'category': 'spice_it_up'},
    {'q': 'What is the three day rule in dating?', 'a': 'Waiting 3 days before texting after a first date', 'category': 'spice_it_up'},
    {'q': 'What does wifey material mean?', 'a': 'Someone seen as ideal long-term partner', 'category': 'spice_it_up'},
    {'q': 'What is JOMO as an alternative to FOMO?', 'a': 'Joy Of Missing Out', 'category': 'spice_it_up'},
    {'q': 'What is mirroring in attraction?', 'a': 'Subconsciously copying someone\'s behavior to build connection', 'category': 'spice_it_up'},
    {'q': 'What does sexual tension mean?', 'a': 'Unspoken physical attraction between people', 'category': 'spice_it_up'},
    {'q': 'What is stashing in relationships?', 'a': 'Hiding a partner from friends and family', 'category': 'spice_it_up'},
    {'q': 'What does dry texting mean?', 'a': 'Short one-word boring replies in conversation', 'category': 'spice_it_up'},
    {'q': 'What is negging?', 'a': 'Giving backhanded compliments to create insecurity', 'category': 'spice_it_up'},
    {'q': 'What does the ick mean in modern dating?', 'a': 'Sudden loss of attraction triggered by something minor', 'category': 'spice_it_up'},
    {'q': 'What is zombie-ing in dating?', 'a': 'When someone who ghosted you suddenly reappears', 'category': 'spice_it_up'},
    {'q': 'What does they came on too strong mean?', 'a': 'Moving too fast or intensely early in a situation', 'category': 'spice_it_up'},
    {'q': 'What is a player in a dating context?', 'a': 'Someone who dates multiple people without being honest', 'category': 'spice_it_up'},
    {'q': 'What does leading someone on mean?', 'a': 'Letting someone think you have feelings when you don\'t', 'category': 'spice_it_up'},
    {'q': 'What does closure mean after a breakup?', 'a': 'A final conversation that helps someone move on', 'category': 'spice_it_up'},
    {'q': 'What is toxic positivity?', 'a': 'Dismissing negative feelings with forced positivity', 'category': 'spice_it_up'},
    {'q': 'What does playing games mean in a relationship?', 'a': 'Being manipulative or inconsistent on purpose', 'category': 'spice_it_up'},
    {'q': 'What is emotional unavailability?', 'a': 'Being unable or unwilling to open up emotionally', 'category': 'spice_it_up'},
    {'q': 'What does we\'re just talking usually imply?', 'a': 'Early romantic interest without a commitment label', 'category': 'spice_it_up'},
    {'q': 'What is the difference between lust and love?', 'a': 'Lust is primarily physical, love is emotional and deeper', 'category': 'spice_it_up'},
    {'q': 'What is cuffing season?', 'a': 'Autumn/winter period when people seek relationships', 'category': 'spice_it_up'},
    {'q': 'What does I\'m not ready for a relationship typically mean?', 'a': 'Not ready with that specific person or in general', 'category': 'spice_it_up'},
    {'q': 'What is micro-cheating?', 'a': 'Small acts of emotional infidelity short of full cheating', 'category': 'spice_it_up'},
    {'q': 'What does hot and cold behavior in relationships refer to?', 'a': 'Alternating between warm interest and cold distance', 'category': 'spice_it_up'},
    {'q': 'What is vulnerability in a relationship?', 'a': 'Openness and emotional honesty with another person', 'category': 'spice_it_up'},
    {'q': 'What is commitment issues?', 'a': 'Fear or inability to commit to a long-term relationship', 'category': 'spice_it_up'},
    {'q': 'What does she\'s my person mean?', 'a': 'Deep emotional bond beyond just romantic partnership', 'category': 'spice_it_up'},
    {'q': 'What is gazing into each other\'s eyes linked to in attraction research?', 'a': 'Increased feelings of intimacy and connection', 'category': 'spice_it_up'},
    {'q': 'What does unresolved feelings mean?', 'a': 'Lingering emotions from a past relationship not yet processed', 'category': 'spice_it_up'},
    {'q': 'What is attachment trauma?', 'a': 'Emotional wounds from past relationship experiences', 'category': 'spice_it_up'},
    {'q': 'What does unrequited love mean?', 'a': 'Love that is not returned by the other person', 'category': 'spice_it_up'},
    {'q': 'What is infatuation versus love?', 'a': 'Infatuation is intense but short-lived; love is deeper and more enduring', 'category': 'spice_it_up'},
    {'q': 'What does they know exactly how to push my buttons mean?', 'a': 'They know how to get a strong emotional reaction', 'category': 'spice_it_up'},
    {'q': 'What is the honeymoon phase?', 'a': 'The early exciting stage of a relationship', 'category': 'spice_it_up'},
    {'q': 'What is emotional intimacy?', 'a': 'Deep emotional sharing and trust between two people', 'category': 'spice_it_up'},
    {'q': 'What is codependency in a relationship?', 'a': 'Excessive emotional reliance on a partner in an unhealthy way', 'category': 'spice_it_up'},
    {'q': 'What does giving someone space mean?', 'a': 'Allowing someone time or distance to process their feelings', 'category': 'spice_it_up'},
    {'q': 'What is emotional baggage?', 'a': 'Unresolved issues from the past affecting current relationships', 'category': 'spice_it_up'},
    {'q': 'What does making someone feel seen mean?', 'a': 'Acknowledging and truly understanding someone\'s feelings', 'category': 'spice_it_up'},
    {'q': 'What is a gut feeling in a relationship context?', 'a': 'A strong instinctive sense about a person or situation', 'category': 'spice_it_up'},
    {'q': 'What does they wear their heart on their sleeve mean?', 'a': 'Showing emotions openly and honestly', 'category': 'spice_it_up'},
    {'q': 'What is jealousy typically rooted in?', 'a': 'Insecurity and fear of loss', 'category': 'spice_it_up'},
    {'q': 'What does getting under someone\'s skin mean?', 'a': 'Affecting someone deeply and being in their thoughts', 'category': 'spice_it_up'},
    {'q': 'What is an on-again off-again relationship?', 'a': 'A relationship that repeatedly ends and restarts', 'category': 'spice_it_up'},
    {'q': 'What does they bring out the best in me mean?', 'a': 'Someone who inspires you to be a better version of yourself', 'category': 'spice_it_up'},
    {'q': 'What is consent in a relationship context?', 'a': 'Freely given enthusiastic agreement to any intimate interaction', 'category': 'spice_it_up'},
    {'q': 'What does they complete me mean?', 'a': 'Someone who fulfills you emotionally and makes you feel whole', 'category': 'spice_it_up'},
    {'q': 'What is heartbreak?', 'a': 'Deep emotional pain after losing a love or relationship', 'category': 'spice_it_up'},
    {'q': 'What does I carry you with me typically mean emotionally?', 'a': 'Holding someone\'s memory or presence in your heart', 'category': 'spice_it_up'},
    {'q': 'What is the concept of a soulmate?', 'a': 'Someone believed to be a perfect emotional and spiritual match', 'category': 'spice_it_up'},
    {'q': 'What does they made me feel less alone mean?', 'a': 'Providing deep emotional connection and understanding', 'category': 'spice_it_up'},
    {'q': 'What is falling in love slowly?', 'a': 'Gradually developing deep feelings over time', 'category': 'spice_it_up'},
    {'q': 'What does love is not enough mean in relationship advice?', 'a': 'Healthy relationships also need respect, communication, and effort', 'category': 'spice_it_up'},
    {'q': 'What is passionate love characterized by?', 'a': 'Intense emotion, physical attraction, and obsessive thinking', 'category': 'spice_it_up'},
    {'q': 'What does swept off your feet mean?', 'a': 'Being overwhelmed by romantic feelings for someone', 'category': 'spice_it_up'},
    {'q': 'What is the difference between loving someone and being in love?', 'a': 'Loving is general; being in love is romantic and deep', 'category': 'spice_it_up'},
    {'q': 'What does the spark was there refer to?', 'a': 'An instant and undeniable romantic chemistry', 'category': 'spice_it_up'},
    {'q': 'What does we have history typically mean?', 'a': 'A past romantic or emotionally significant connection', 'category': 'spice_it_up'},
    {'q': 'What is the right person at the wrong time?', 'a': 'A profound connection that circumstances prevent from working', 'category': 'spice_it_up'},
    {'q': 'What does loving from a distance mean?', 'a': 'Caring deeply while staying emotionally or physically apart', 'category': 'spice_it_up'},
    {'q': 'What is an emotional connection?', 'a': 'A deep sense of understanding and feeling seen by another person', 'category': 'spice_it_up'},
    {'q': 'What does they\'re my person mean beyond romance?', 'a': 'Someone who is your anchor and greatest emotional supporter', 'category': 'spice_it_up'},
    {'q': 'What is a genuine connection in psychology?', 'a': 'A mutual feeling of being understood and accepted fully', 'category': 'spice_it_up'},
    {'q': 'What does falling apart over someone mean?', 'a': 'Being deeply emotionally affected by someone leaving', 'category': 'spice_it_up'},
    {'q': 'What is emotional availability?', 'a': 'Being open willing and able to engage emotionally', 'category': 'spice_it_up'},
    {'q': 'What does chemistry between two people refer to?', 'a': 'Natural effortless attraction and connection', 'category': 'spice_it_up'},
    {'q': 'What is a soft launch of a relationship?', 'a': 'Subtly introducing someone on social media without announcement', 'category': 'spice_it_up'},
    {'q': 'What does it mean to have feelings for someone?', 'a': 'Experiencing romantic or emotional attraction toward them', 'category': 'spice_it_up'},
    {'q': 'What is a talking phase?', 'a': 'The period of getting to know someone before dating officially', 'category': 'spice_it_up'},
    {'q': 'What does I see a future with you mean?', 'a': 'Envisioning long-term romantic partnership', 'category': 'spice_it_up'},
    {'q': 'What is a non-negotiable in a relationship?', 'a': 'A requirement that cannot be compromised on', 'category': 'spice_it_up'},
    {'q': 'What does reciprocate feelings mean?', 'a': 'Return the same level of romantic feeling', 'category': 'spice_it_up'},
    {'q': 'What is a healthy relationship boundary?', 'a': 'A limit set to protect your emotional wellbeing', 'category': 'spice_it_up'},
    {'q': 'What does putting someone on a pedestal mean romantically?', 'a': 'Idealizing someone beyond their reality', 'category': 'spice_it_up'},
    {'q': 'What is the talking stage typically followed by?', 'a': 'Dating exclusively or defining the relationship', 'category': 'spice_it_up'},
    {'q': 'What does falling out of love mean?', 'a': 'Losing romantic feelings for someone over time', 'category': 'spice_it_up'},
    {'q': 'What is a red flag in a new relationship?', 'a': 'A warning sign indicating potential future problems', 'category': 'spice_it_up'},
    {'q': 'What does they\'re my safe place mean?', 'a': 'Someone who makes you feel completely secure and accepted', 'category': 'spice_it_up'},
    {'q': 'What is unconditional love?', 'a': 'Love that remains regardless of circumstances or flaws', 'category': 'spice_it_up'},
    {'q': 'Who sang Thank U Next?', 'a': 'Ariana Grande', 'category': 'girls_night'},
    {'q': 'What does GRWM stand for?', 'a': 'Get Ready With Me', 'category': 'girls_night'},
    {'q': 'Who is known for the red lip era and Fearless album?', 'a': 'Taylor Swift', 'category': 'girls_night'},
    {'q': 'What is the most used emoji globally by women according to studies?', 'a': '😭', 'category': 'girls_night'},
    {'q': 'Which TV show features the character Lorelai Gilmore?', 'a': 'Gilmore Girls', 'category': 'girls_night'},
    {'q': 'Who plays Mindy Lahiri in The Mindy Project?', 'a': 'Mindy Kaling', 'category': 'girls_night'},
    {'q': 'What is the first name of Sex and the City\'s main character?', 'a': 'Carrie', 'category': 'girls_night'},
    {'q': 'Which artist sang Bad Guy?', 'a': 'Billie Eilish', 'category': 'girls_night'},
    {'q': 'What does BFF stand for?', 'a': 'Best Friend Forever', 'category': 'girls_night'},
    {'q': 'In Legally Blonde what is Elle Woods\' iconic color?', 'a': 'Pink', 'category': 'girls_night'},
    {'q': 'What does the term hot girl summer originate from?', 'a': 'A song and phrase by Megan Thee Stallion', 'category': 'girls_night'},
    {'q': 'Who is Queen Bey?', 'a': 'Beyoncé', 'category': 'girls_night'},
    {'q': 'What beauty brand is known for its Almost Lipstick?', 'a': 'Clinique', 'category': 'girls_night'},
    {'q': 'What is SPF in skincare?', 'a': 'Sun Protection Factor', 'category': 'girls_night'},
    {'q': 'Which show popularised the phrase That\'s so fetch?', 'a': 'Mean Girls', 'category': 'girls_night'},
    {'q': 'Who directed the Barbie movie?', 'a': 'Greta Gerwig', 'category': 'girls_night'},
    {'q': 'Which city is known as the fashion capital of the world?', 'a': 'Paris', 'category': 'girls_night'},
    {'q': 'What skin care ingredient is most commonly used for anti-aging?', 'a': 'Retinol', 'category': 'girls_night'},
    {'q': 'Who is known as the Queen of Pop?', 'a': 'Madonna', 'category': 'girls_night'},
    {'q': 'What movie features the song Let It Go?', 'a': 'Frozen', 'category': 'girls_night'},
    {'q': 'Which actress plays Hermione in Harry Potter?', 'a': 'Emma Watson', 'category': 'girls_night'},
    {'q': 'What does the phrase soft life mean?', 'a': 'Living comfortably without unnecessary stress', 'category': 'girls_night'},
    {'q': 'Which platform is most associated with beauty tutorials?', 'a': 'YouTube', 'category': 'girls_night'},
    {'q': 'What is clean girl aesthetic?', 'a': 'A minimalist natural makeup and wellness look', 'category': 'girls_night'},
    {'q': 'Who sang Woman Like Me?', 'a': 'Little Mix', 'category': 'girls_night'},
    {'q': 'What does this is your villain era mean?', 'a': 'Unapologetically putting yourself first', 'category': 'girls_night'},
    {'q': 'Which skincare ingredient is known for hydration?', 'a': 'Hyaluronic acid', 'category': 'girls_night'},
    {'q': 'What does girl math typically mean in social media?', 'a': 'Justifying spending decisions with clever logic', 'category': 'girls_night'},
    {'q': 'What does aesthetic mean when used as a noun online?', 'a': 'A particular visual style or vibe', 'category': 'girls_night'},
    {'q': 'Which Spice Girl was known as Scary Spice?', 'a': 'Mel B', 'category': 'girls_night'},
    {'q': 'What show features Carrie Bradshaw and her iconic shoe obsession?', 'a': 'Sex and the City', 'category': 'girls_night'},
    {'q': 'What is body neutrality?', 'a': 'Accepting your body without needing to love it', 'category': 'girls_night'},
    {'q': 'What does manifest mean in popular culture?', 'a': 'Visualizing and believing in what you want to attract it', 'category': 'girls_night'},
    {'q': 'What does boss babe typically mean?', 'a': 'An ambitious woman who runs her own thing', 'category': 'girls_night'},
    {'q': 'Who sang Superwoman?', 'a': 'Alicia Keys', 'category': 'girls_night'},
    {'q': 'What does girlboss mean in its original positive context?', 'a': 'An ambitious woman who builds success on her own terms', 'category': 'girls_night'},
    {'q': 'What does serotonin boost refer to informally?', 'a': 'Something that gives you a happiness hit', 'category': 'girls_night'},
    {'q': 'Which actress is known for her role as Elle Woods?', 'a': 'Reese Witherspoon', 'category': 'girls_night'},
    {'q': 'What does bestie behavior typically describe?', 'a': 'Supportive warm best-friend energy', 'category': 'girls_night'},
    {'q': 'What is the most followed woman on Instagram?', 'a': 'Selena Gomez', 'category': 'girls_night'},
    {'q': 'What does she understood the assignment mean?', 'a': 'She delivered exactly what was expected perfectly', 'category': 'girls_night'},
    {'q': 'What is a power move in a social context?', 'a': 'A confident action that asserts status', 'category': 'girls_night'},
    {'q': 'Who is known for her Eras Tour?', 'a': 'Taylor Swift', 'category': 'girls_night'},
    {'q': 'What does she ate and left no crumbs mean?', 'a': 'Performed something flawlessly', 'category': 'girls_night'},
    {'q': 'What is dopamine dressing?', 'a': 'Dressing in bright joyful colors to boost mood', 'category': 'girls_night'},
    {'q': 'What does I\'m in my healing era mean?', 'a': 'Actively working through emotional growth and self development', 'category': 'girls_night'},
    {'q': 'What is a Pinterest board?', 'a': 'A curated collection of images and ideas on Pinterest', 'category': 'girls_night'},
    {'q': 'What does empowered women empower women mean?', 'a': 'Confident women lift others up rather than compete', 'category': 'girls_night'},
    {'q': 'What is a red carpet moment?', 'a': 'A moment that is glamorous impressive or standout', 'category': 'girls_night'},
    {'q': 'Who sings Good as Hell?', 'a': 'Lizzo', 'category': 'girls_night'},
    {'q': 'What does choose yourself mean in self-help context?', 'a': 'Prioritizing your own needs wellbeing and happiness', 'category': 'girls_night'},
    {'q': 'What is healing your inner child?', 'a': 'Working through childhood emotional wounds in adulthood', 'category': 'girls_night'},
    {'q': 'What does she gives main character energy mean?', 'a': 'She carries herself as if she\'s the central figure of her narrative', 'category': 'girls_night'},
    {'q': 'What is luxury girl aesthetic?', 'a': 'An aspirational aesthetic of refinement quiet confidence and quality', 'category': 'girls_night'},
    {'q': 'What does doing it for the plot mean?', 'a': 'Making bold choices in your life as if living an interesting story', 'category': 'girls_night'},
    {'q': 'What is romanticizing your life on social media?', 'a': 'Finding beauty and meaning in everyday ordinary moments', 'category': 'girls_night'},
    {'q': 'What does alignment mean when people say they\'re in it?', 'a': 'Being in sync with your values purpose and authentic self', 'category': 'girls_night'},
    {'q': 'What does soft girl era mean?', 'a': 'Embracing femininity softness and emotional openness', 'category': 'girls_night'},
    {'q': 'What does unbothered mean in modern usage?', 'a': 'Completely unaffected by criticism or outside opinions', 'category': 'girls_night'},
    {'q': 'What is a glow era?', 'a': 'A transformative period of personal growth and development', 'category': 'girls_night'},
    {'q': 'What does protect your peace mean?', 'a': 'Actively maintaining your emotional wellbeing by removing stress', 'category': 'girls_night'},
    {'q': 'Who plays Moana in the Disney film?', 'a': 'Auli\'i Cravalho', 'category': 'girls_night'},
    {'q': 'What does pilates girl aesthetic mean?', 'a': 'A wellness-focused healthy and balanced lifestyle', 'category': 'girls_night'},
    {'q': 'What is girl dinner?', 'a': 'A small random assortment of foods eaten alone with no cooking', 'category': 'girls_night'},
    {'q': 'What does glazed donut skin refer to as a beauty trend?', 'a': 'A glowy dewy luminous complexion', 'category': 'girls_night'},
    {'q': 'Who coined I\'m that girl as an anthem?', 'a': 'Lizzo', 'category': 'girls_night'},
    {'q': 'What does iconic mean in modern slang?', 'a': 'Impressively memorable and legendary in some way', 'category': 'girls_night'},
    {'q': 'What does that era is over mean in a personal context?', 'a': 'Moving on from a previous phase of your life', 'category': 'girls_night'},
    {'q': 'What does she\'s in her feelings mean?', 'a': 'She is emotionally affected by something', 'category': 'girls_night'},
    {'q': 'What does slay queen mean?', 'a': 'A woman who is confidently impressive and unstoppable', 'category': 'girls_night'},
    {'q': 'What does main character mean on social media?', 'a': 'Acting as if you\'re the central figure of your own narrative', 'category': 'girls_night'},
    {'q': 'What is a glow up?', 'a': 'A significant positive transformation', 'category': 'girls_night'},
    {'q': 'What does living your best life mean?', 'a': 'Fully enjoying and embracing your own happiness', 'category': 'girls_night'},
    {'q': 'What does she\'s that girl mean as a compliment?', 'a': 'Being impressive aspirational and admirable', 'category': 'girls_night'},
    {'q': 'What does toxic trait mean when someone says it about themselves?', 'a': 'A behavioral flaw they acknowledge about themselves', 'category': 'girls_night'},
    {'q': 'What is self care Sunday?', 'a': 'Skincare relaxation and restorative activities', 'category': 'girls_night'},
    {'q': 'What is the most followed account on Instagram?', 'a': 'Instagram itself', 'category': 'girls_night'},
    {'q': 'What does hot girl behavior typically involve?', 'a': 'Being confident unapologetic and carefree', 'category': 'girls_night'},
    {'q': 'What does it take main character energy mean?', 'a': 'Moving through life with confidence and ownership', 'category': 'girls_night'},
    {'q': 'What does bestie culture refer to online?', 'a': 'A supportive encouraging friendship dynamic', 'category': 'girls_night'},
    {'q': 'What does the phrase this hits different mean?', 'a': 'Something feels uniquely powerful in a specific context', 'category': 'girls_night'},
    {'q': 'What does she said what she said mean?', 'a': 'Standing by a bold or honest statement', 'category': 'girls_night'},
    {'q': 'What does her loss mean?', 'a': 'Someone missed out on something valuable by their own choice', 'category': 'girls_night'},
    {'q': 'What does unbothered queen mean?', 'a': 'A woman who is completely unaffected by negativity', 'category': 'girls_night'},
    {'q': 'What does I woke up like this reference?', 'a': 'A Beyoncé lyric about natural effortless beauty', 'category': 'girls_night'},
    {'q': 'What does chosen girl era mean?', 'a': 'A phase of being selective and knowing your value', 'category': 'girls_night'},
    {'q': 'What does she\'s going through it mean?', 'a': 'She\'s dealing with something emotionally difficult', 'category': 'girls_night'},
    {'q': 'What does the girl dinner trend celebrate?', 'a': 'The freedom of eating whatever you want with no judgment', 'category': 'girls_night'},
    {'q': 'What does cozy girl era mean?', 'a': 'Embracing comfort softness and peaceful living', 'category': 'girls_night'},
    {'q': 'What does I\'m built for this mean in a motivation context?', 'a': 'Feeling equipped and ready to handle challenges', 'category': 'girls_night'},
    {'q': 'What does she\'s eating mean as praise?', 'a': 'She is performing or doing something exceptionally well', 'category': 'girls_night'},
    {'q': 'What does feminine energy mean in popular wellness culture?', 'a': 'Embracing softness intuition and flow over force', 'category': 'girls_night'},
    {'q': 'What does a glow down refer to?', 'a': 'The opposite of a glow up; a decline in appearance or energy', 'category': 'girls_night'},
    {'q': 'What does she stayed winning mean?', 'a': 'She consistently comes out on top regardless of circumstances', 'category': 'girls_night'},
    {'q': 'What does red table talk reference?', 'a': 'Jada Pinkett Smith\'s Facebook Watch show', 'category': 'girls_night'},
    {'q': 'What does big sister energy mean?', 'a': 'Wise protective and supportive vibes', 'category': 'girls_night'},
    {'q': 'What does feminine rage mean in modern feminist context?', 'a': 'The collective and righteous anger felt by women', 'category': 'girls_night'},
    {'q': 'What does body of work mean in a personal development context?', 'a': 'Everything you\'ve created built or achieved over time', 'category': 'girls_night'},
    {'q': 'What does her chapter is just beginning mean?', 'a': 'Someone is at the start of an exciting new phase', 'category': 'girls_night'},
    {'q': 'What does the phrase that girl summer mean?', 'a': 'A period of thriving self-improvement and confidence', 'category': 'girls_night'},
    {'q': 'What sport uses the term hat-trick?', 'a': 'Football/Soccer', 'category': 'guys_unleashed'},
    {'q': 'In boxing what does TKO stand for?', 'a': 'Technical Knockout', 'category': 'guys_unleashed'},
    {'q': 'What does MVP stand for in sport?', 'a': 'Most Valuable Player', 'category': 'guys_unleashed'},
    {'q': 'In football how many points is a touchdown worth?', 'a': '6', 'category': 'guys_unleashed'},
    {'q': 'What brand makes the Air Jordan trainer?', 'a': 'Nike', 'category': 'guys_unleashed'},
    {'q': 'What is rizz in modern slang?', 'a': 'Natural charm and ability to attract others', 'category': 'guys_unleashed'},
    {'q': 'What does GG mean in gaming?', 'a': 'Good Game', 'category': 'guys_unleashed'},
    {'q': 'What is the highest rank in traditional martial arts?', 'a': 'Black belt', 'category': 'guys_unleashed'},
    {'q': 'Who holds the record for most Premier League goals?', 'a': 'Alan Shearer', 'category': 'guys_unleashed'},
    {'q': 'What does L in taking the L mean?', 'a': 'Loss', 'category': 'guys_unleashed'},
    {'q': 'In gym terms what does PR stand for?', 'a': 'Personal Record', 'category': 'guys_unleashed'},
    {'q': 'What does no cap mean?', 'a': 'No lie for real', 'category': 'guys_unleashed'},
    {'q': 'How many Formula 1 World Championships did Michael Schumacher win?', 'a': '7', 'category': 'guys_unleashed'},
    {'q': 'What does GOAT stand for?', 'a': 'Greatest Of All Time', 'category': 'guys_unleashed'},
    {'q': 'What body part does a bicep curl primarily train?', 'a': 'Biceps', 'category': 'guys_unleashed'},
    {'q': 'What does on sight mean in modern slang?', 'a': 'Immediately upon seeing someone', 'category': 'guys_unleashed'},
    {'q': 'In basketball what is a triple double?', 'a': 'Getting double figures in 3 statistical categories', 'category': 'guys_unleashed'},
    {'q': 'What does sauce mean in modern slang?', 'a': 'Confidence and style', 'category': 'guys_unleashed'},
    {'q': 'What does 1v1 me typically mean?', 'a': 'Challenge me to a head-to-head competition', 'category': 'guys_unleashed'},
    {'q': 'What is the purpose of a spotter in weightlifting?', 'a': 'Assisting safety during a lift', 'category': 'guys_unleashed'},
    {'q': 'What does clutch mean in a sporting or gaming context?', 'a': 'Performing brilliantly under pressure in a key moment', 'category': 'guys_unleashed'},
    {'q': 'In cricket what does LBW stand for?', 'a': 'Leg Before Wicket', 'category': 'guys_unleashed'},
    {'q': 'What does grind mean in a goals context?', 'a': 'Working hard consistently toward a goal', 'category': 'guys_unleashed'},
    {'q': 'What year was the first FIFA World Cup held?', 'a': '1930', 'category': 'guys_unleashed'},
    {'q': 'What does built different mean in slang?', 'a': 'Being uniquely exceptional or mentally strong', 'category': 'guys_unleashed'},
    {'q': 'In gaming what does respawn mean?', 'a': 'Coming back to life after dying in a game', 'category': 'guys_unleashed'},
    {'q': 'What does keeping it 100 mean?', 'a': 'Being completely honest and authentic', 'category': 'guys_unleashed'},
    {'q': 'What sport features the terms birdies and bogeys?', 'a': 'Golf', 'category': 'guys_unleashed'},
    {'q': 'What does W mean in internet slang?', 'a': 'Win', 'category': 'guys_unleashed'},
    {'q': 'Which muscle group does a deadlift primarily target?', 'a': 'Hamstrings glutes and back', 'category': 'guys_unleashed'},
    {'q': 'What does drip mean in fashion slang?', 'a': 'Excellent and stylish clothing and accessories', 'category': 'guys_unleashed'},
    {'q': 'What is a cold shower associated with in wellness culture?', 'a': 'Increased alertness and mental toughness', 'category': 'guys_unleashed'},
    {'q': 'Who is widely considered the greatest basketball player of all time?', 'a': 'Michael Jordan', 'category': 'guys_unleashed'},
    {'q': 'What does lowkey mean in modern slang?', 'a': 'Quietly or slightly without drawing attention', 'category': 'guys_unleashed'},
    {'q': 'What does run it back mean?', 'a': 'To do something again or repeat a situation', 'category': 'guys_unleashed'},
    {'q': 'What is a proper banger in UK slang?', 'a': 'An excellent song or moment', 'category': 'guys_unleashed'},
    {'q': 'What does neck and neck mean in competition?', 'a': 'Extremely close with neither side having a clear advantage', 'category': 'guys_unleashed'},
    {'q': 'What does no days off mean as a mindset?', 'a': 'Consistent dedication and effort without letting up', 'category': 'guys_unleashed'},
    {'q': 'What is a gym rat?', 'a': 'Someone who spends a lot of time at the gym', 'category': 'guys_unleashed'},
    {'q': 'In MMA what does TKO stand for?', 'a': 'Technical Knockout', 'category': 'guys_unleashed'},
    {'q': 'What does big ups mean?', 'a': 'Congratulations or respect', 'category': 'guys_unleashed'},
    {'q': 'What is a clean sheet in football?', 'a': 'Not conceding a single goal in a match', 'category': 'guys_unleashed'},
    {'q': 'What does putting in work mean?', 'a': 'Consistently training hard and making effort', 'category': 'guys_unleashed'},
    {'q': 'What is the bag in modern slang?', 'a': 'Money success or securing your goals', 'category': 'guys_unleashed'},
    {'q': 'What does go hard or go home mean?', 'a': 'Giving maximum effort or not bothering', 'category': 'guys_unleashed'},
    {'q': 'What is a beast mode workout?', 'a': 'Training with extreme intensity and focus', 'category': 'guys_unleashed'},
    {'q': 'What does mad respect mean?', 'a': 'Extremely high respect and acknowledgment', 'category': 'guys_unleashed'},
    {'q': 'Who is considered the greatest boxer of all time by many?', 'a': 'Muhammad Ali', 'category': 'guys_unleashed'},
    {'q': 'What does he\'s a menace mean positively in modern slang?', 'a': 'He\'s an impressive and boldly entertaining person', 'category': 'guys_unleashed'},
    {'q': 'What does touch grass mean in internet slang?', 'a': 'Taking a break from the internet and going outside', 'category': 'guys_unleashed'},
    {'q': 'What is protein synthesis important for in fitness?', 'a': 'Building and repairing muscle tissue', 'category': 'guys_unleashed'},
    {'q': 'What does he\'s the real deal mean?', 'a': 'He is genuinely as impressive as he appears', 'category': 'guys_unleashed'},
    {'q': 'What does putting yourself out there mean?', 'a': 'Taking social risks to meet people or pursue opportunities', 'category': 'guys_unleashed'},
    {'q': 'What does take the W mean?', 'a': 'Take the win or victory', 'category': 'guys_unleashed'},
    {'q': 'What is discipline over motivation as a philosophy?', 'a': 'Relying on consistent habits rather than temporary inspiration', 'category': 'guys_unleashed'},
    {'q': 'What does big dog energy mean?', 'a': 'Confident and authoritative presence', 'category': 'guys_unleashed'},
    {'q': 'What is progressive overload in training?', 'a': 'Gradually increasing weight or difficulty to keep improving', 'category': 'guys_unleashed'},
    {'q': 'What does securing the bag mean?', 'a': 'Successfully achieving financial goals or success', 'category': 'guys_unleashed'},
    {'q': 'What is a form check in weightlifting?', 'a': 'Reviewing technique to ensure safe and effective lifting', 'category': 'guys_unleashed'},
    {'q': 'What does all gas no brakes mean?', 'a': 'Going full speed with no hesitation or slowing down', 'category': 'guys_unleashed'},
    {'q': 'What sport did Usain Bolt dominate?', 'a': '100m and 200m sprinting', 'category': 'guys_unleashed'},
    {'q': 'What does staying in your lane mean?', 'a': 'Focusing on your own business and not comparing with others', 'category': 'guys_unleashed'},
    {'q': 'What is hypertrophy in muscle training?', 'a': 'Increase in muscle size from training', 'category': 'guys_unleashed'},
    {'q': 'What does iron sharpens iron mean as a phrase?', 'a': 'Strong people make each other better through challenge', 'category': 'guys_unleashed'},
    {'q': 'What does lock in mean in a performance context?', 'a': 'Fully focusing and committing to the task at hand', 'category': 'guys_unleashed'},
    {'q': 'What is the bro code?', 'a': 'An unwritten set of rules between male friends', 'category': 'guys_unleashed'},
    {'q': 'What does level up mean beyond gaming?', 'a': 'Improving yourself or your situation significantly', 'category': 'guys_unleashed'},
    {'q': 'What does alpha energy typically refer to?', 'a': 'Confidence dominance and leadership presence', 'category': 'guys_unleashed'},
    {'q': 'What is a spotter bro at the gym?', 'a': 'A gym partner who helps with safety during heavy lifts', 'category': 'guys_unleashed'},
    {'q': 'What does he\'s got composure mean in sport?', 'a': 'He handles pressure calmly and performs with control', 'category': 'guys_unleashed'},
    {'q': 'What does game recognize game mean?', 'a': 'Skilled people recognizing quality in each other', 'category': 'guys_unleashed'},
    {'q': 'What is mental fortitude in sport and life?', 'a': 'The strength to persist through difficulty and pressure', 'category': 'guys_unleashed'},
    {'q': 'What is the zone in athletic performance?', 'a': 'A peak flow state of total focus and effortless performance', 'category': 'guys_unleashed'},
    {'q': 'What does train smart not just hard mean?', 'a': 'Using intelligent programming and recovery not just volume', 'category': 'guys_unleashed'},
    {'q': 'What is an accountability partner in fitness?', 'a': 'Someone who holds you responsible for your goals and progress', 'category': 'guys_unleashed'},
    {'q': 'What does earning your stripes mean?', 'a': 'Proving yourself through effort and experience over time', 'category': 'guys_unleashed'},
    {'q': 'What is sweat equity in business slang?', 'a': 'Value created through hard work and effort rather than capital', 'category': 'guys_unleashed'},
    {'q': 'What does leave it all on the field mean?', 'a': 'Giving every last bit of effort in a competition', 'category': 'guys_unleashed'},
    {'q': 'What does consistency is key mean in self development?', 'a': 'Showing up regularly over time being more important than intensity', 'category': 'guys_unleashed'},
    {'q': 'What is functional fitness?', 'a': 'Training that improves everyday movement and real-life performance', 'category': 'guys_unleashed'},
    {'q': 'What does dog mentality mean as a compliment?', 'a': 'Having relentless work ethic loyalty and toughness', 'category': 'guys_unleashed'},
    {'q': 'What is sparring in boxing?', 'a': 'Practice fighting to improve skills without full competitive intent', 'category': 'guys_unleashed'},
    {'q': 'What does respect the process mean?', 'a': 'Trusting the journey and not rushing results', 'category': 'guys_unleashed'},
    {'q': 'What does move in silence mean as a strategy?', 'a': 'Achieving things without announcing your plans', 'category': 'guys_unleashed'},
    {'q': 'What is a one rep max in weightlifting?', 'a': 'The maximum weight you can lift for one complete repetition', 'category': 'guys_unleashed'},
    {'q': 'What does showing up mean beyond just arriving?', 'a': 'Consistently putting in effort and being mentally present', 'category': 'guys_unleashed'},
    {'q': 'What does accountability mean in a goals context?', 'a': 'Taking ownership of your actions and results', 'category': 'guys_unleashed'},
    {'q': 'What does the grind is real mean?', 'a': 'Acknowledging the hard work required to achieve something', 'category': 'guys_unleashed'},
    {'q': 'What is a comeback story in sport?', 'a': 'Overcoming setbacks to return to peak performance', 'category': 'guys_unleashed'},
    {'q': 'What does putting your head down mean in work context?', 'a': 'Focusing and working hard without distraction', 'category': 'guys_unleashed'},
    {'q': 'What does earned not given mean as a mindset?', 'a': 'Success comes through effort not luck or privilege', 'category': 'guys_unleashed'},
    {'q': 'What does he went crazy mean as praise in modern slang?', 'a': 'He performed at an exceptionally high level', 'category': 'guys_unleashed'},
    {'q': 'What is a highlight reel?', 'a': 'A collection of someone\'s best moments or performances', 'category': 'guys_unleashed'},
    {'q': 'What does proving doubters wrong mean as motivation?', 'a': 'Using criticism as fuel to succeed', 'category': 'guys_unleashed'},
    {'q': 'What does dominate mean in a competition context?', 'a': 'To completely outperform and control an opponent or field', 'category': 'guys_unleashed'},
    {'q': 'What is the underdog narrative in sport?', 'a': 'When an unexpected competitor overcomes the odds to succeed', 'category': 'guys_unleashed'},
    {'q': 'What does he\'s ice cold mean as a compliment?', 'a': 'He is calm composed and unfazed under pressure', 'category': 'guys_unleashed'},
    {'q': 'What does we go again mean after a loss?', 'a': 'Moving forward with resilience despite a setback', 'category': 'guys_unleashed'},
    {'q': 'What does lock in and go mean?', 'a': 'Fully commit to the task and execute without hesitation', 'category': 'guys_unleashed'},
    {'q': 'What does that\'s a different breed mean as high praise?', 'a': 'Someone is exceptionally elite and operates at a higher level', 'category': 'guys_unleashed'},
  ];
}
