/// Would You Rather question database
class WyrData {
  static const List<Map<String, dynamic>> questions = [
    {'optionA': 'only be able to whisper', 'optionB': 'only be able to shout for the rest of your life', 'category': 'party_starter'},
    {'optionA': 'have a personal chef', 'optionB': 'a personal driver for life', 'category': 'party_starter'},
    {'optionA': 'fight 100 duck-sized horses', 'optionB': 'one horse-sized duck', 'category': 'party_starter'},
    {'optionA': 'always be 10 minutes late to everything', 'optionB': '20 minutes early', 'category': 'party_starter'},
    {'optionA': 'only eat sweet food forever', 'optionB': 'only eat savoury food forever', 'category': 'party_starter'},
    {'optionA': 'always have to tell the truth', 'optionB': 'always be able to lie convincingly', 'category': 'party_starter'},
    {'optionA': 'have unlimited pizza forever with only one topping', 'optionB': 'any food that all tastes slightly wrong', 'category': 'party_starter'},
    {'optionA': 'speak every language fluently', 'optionB': 'play every instrument perfectly', 'category': 'party_starter'},
    {'optionA': 'have a pause button for your life', 'optionB': 'a rewind button', 'category': 'party_starter'},
    {'optionA': 'Would you rather live in a world with no music OR a world with no movies or TV?', 'optionB': '', 'category': 'party_starter'},
    {'optionA': 'lose all your photos', 'optionB': 'lose all your contacts and numbers', 'category': 'party_starter'},
    {'optionA': 'have a pet elephant', 'optionB': 'a pet giraffe', 'category': 'party_starter'},
    {'optionA': 'never feel cold', 'optionB': 'never feel too warm', 'category': 'party_starter'},
    {'optionA': 'be able to breathe underwater', 'optionB': 'never need to sleep again', 'category': 'party_starter'},
    {'optionA': 'be the funniest person in every room', 'optionB': 'the most attractive', 'category': 'party_starter'},
    {'optionA': 'win an Olympic gold medal', 'optionB': 'win an Academy Award', 'category': 'party_starter'},
    {'optionA': 'have free food for life', 'optionB': 'free travel for life', 'category': 'party_starter'},
    {'optionA': 'have the ability to run at 50 miles per hour', 'optionB': 'lift 1000 pounds', 'category': 'party_starter'},
    {'optionA': 'always know when someone is lying', 'optionB': 'always know their deepest secret', 'category': 'party_starter'},
    {'optionA': 'be able to fly but only at walking speed', 'optionB': 'be invisible but only when no one is looking', 'category': 'party_starter'},
    {'optionA': 'have your thoughts visible to everyone', 'optionB': 'have everyone see your search history', 'category': 'party_starter'},
    {'optionA': 'be 10 times smarter', 'optionB': '10 times more attractive than you currently are', 'category': 'party_starter'},
    {'optionA': 'live on a boat forever', 'optionB': 'live in a treehouse forever', 'category': 'party_starter'},
    {'optionA': 'have super strength', 'optionB': 'super speed', 'category': 'party_starter'},
    {'optionA': 'only be able to eat hot food', 'optionB': 'only eat cold food', 'category': 'party_starter'},
    {'optionA': 'have no phone for a month', 'optionB': 'no internet for a month', 'category': 'party_starter'},
    {'optionA': 'be able to talk to animals', 'optionB': 'be able to talk to plants', 'category': 'party_starter'},
    {'optionA': 'be famous but completely broke', 'optionB': 'completely unknown but extremely wealthy', 'category': 'party_starter'},
    {'optionA': 'have perfect memory for everything', 'optionB': 'be able to delete any memory you choose', 'category': 'party_starter'},
    {'optionA': 'only be able to see in black and white', 'optionB': 'only be able to hear music', 'category': 'party_starter'},
    {'optionA': 'eat the same meal every day for a year', 'optionB': 'not eat your favourite food for 5 years', 'category': 'party_starter'},
    {'optionA': 'have a rewind on your last 24 hours', 'optionB': 'a sneak preview of your next 24 hours', 'category': 'party_starter'},
    {'optionA': 'always be right but never believe it', 'optionB': 'always be wrong but always confident', 'category': 'party_starter'},
    {'optionA': 'never be bored again', 'optionB': 'never feel stressed again', 'category': 'party_starter'},
    {'optionA': 'have no sense of smell', 'optionB': 'lose your sense of taste completely', 'category': 'party_starter'},
    {'optionA': 'be able to fly but not control the direction', 'optionB': 'teleport but only twice a day', 'category': 'party_starter'},
    {'optionA': 'talk like Yoda for a year', 'optionB': 'breathe loudly like Darth Vader forever', 'category': 'party_starter'},
    {'optionA': 'have hands where your feet are', 'optionB': 'feet where your hands are', 'category': 'party_starter'},
    {'optionA': 'only communicate through interpretive dance', 'optionB': 'only through handwritten notes', 'category': 'party_starter'},
    {'optionA': 'have hair that changes colour with your mood', 'optionB': 'eyes that glow when you\'re happy', 'category': 'party_starter'},
    {'optionA': 'sneeze glitter', 'optionB': 'cry confetti', 'category': 'party_starter'},
    {'optionA': 'be known for your incredible laugh', 'optionB': 'your amazing singing voice', 'category': 'party_starter'},
    {'optionA': 'have ears that pick up radio stations', 'optionB': 'eyes that can zoom in like binoculars', 'category': 'party_starter'},
    {'optionA': 'automatically know the words to every song', 'optionB': 'every dance move to every song', 'category': 'party_starter'},
    {'optionA': 'never need a charger', 'optionB': 'never need WiFi', 'category': 'party_starter'},
    {'optionA': 'be wildly popular with no true friends', 'optionB': 'have 2 friends who know everything about you', 'category': 'party_starter'},
    {'optionA': 'visit a random point in history for a day', 'optionB': 'a random point in the future', 'category': 'party_starter'},
    {'optionA': 'be the best player on a losing team', 'optionB': 'the worst player on a winning team', 'category': 'party_starter'},
    {'optionA': 'only communicate by singing', 'optionB': 'only by doing impressions of others', 'category': 'party_starter'},
    {'optionA': 'always enter a room to dramatic music', 'optionB': 'always exit to applause', 'category': 'party_starter'},
    {'optionA': 'have a personal soundtrack playing as you walk', 'optionB': 'be narrated by a documentary voice', 'category': 'party_starter'},
    {'optionA': 'have a job you love with average pay', 'optionB': 'a job you hate with incredible pay', 'category': 'party_starter'},
    {'optionA': 'never have to queue for anything', 'optionB': 'never have to pay for public transport', 'category': 'party_starter'},
    {'optionA': 'know the exact day you\'ll die', 'optionB': 'know exactly how you\'ll die but not when', 'category': 'party_starter'},
    {'optionA': 'have the ability to stop time for one hour a day', 'optionB': 'go back in time once a year', 'category': 'party_starter'},
    {'optionA': 'wake up in a different country every day', 'optionB': 'never be able to leave your city', 'category': 'party_starter'},
    {'optionA': 'always have perfect hair', 'optionB': 'always have perfectly clear skin', 'category': 'party_starter'},
    {'optionA': 'be the most interesting person nobody invites back', 'optionB': 'the most ordinary person everyone loves', 'category': 'party_starter'},
    {'optionA': 'only be able to communicate through memes', 'optionB': 'only through voice notes', 'category': 'party_starter'},
    {'optionA': 'have a dog that can speak one human phrase', 'optionB': 'a cat that can read your mind', 'category': 'party_starter'},
    {'optionA': 'have a living space that tidies itself', 'optionB': 'a car that drives itself everywhere', 'category': 'party_starter'},
    {'optionA': 'know what someone is about to say', 'optionB': 'remember every conversation you\'ve ever had', 'category': 'party_starter'},
    {'optionA': 'have unlimited battery life on all devices', 'optionB': 'never have signal issues again', 'category': 'party_starter'},
    {'optionA': 'read a book in 5 seconds', 'optionB': 'watch any film in 5 minutes', 'category': 'party_starter'},
    {'optionA': 'have your life turned into a reality TV show without your knowledge', 'optionB': 'narrated by a stranger', 'category': 'party_starter'},
    {'optionA': 'speak every dead language', 'optionB': 'speak to every animal alive today', 'category': 'party_starter'},
    {'optionA': 'always feel the weather of somewhere tropical', 'optionB': 'always have perfect spring weather', 'category': 'party_starter'},
    {'optionA': 'have a photographic memory for faces but not names', 'optionB': 'names but not faces', 'category': 'party_starter'},
    {'optionA': 'always find a parking space immediately', 'optionB': 'always have a seat on public transport', 'category': 'party_starter'},
    {'optionA': 'receive one text a day from a historical figure', 'optionB': 'one voicemail a week from a fictional character', 'category': 'party_starter'},
    {'optionA': 'see 10 minutes into your own future', 'optionB': '10 minutes into anyone else\'s future', 'category': 'party_starter'},
    {'optionA': 'have a closet with exactly the perfect outfit ready', 'optionB': 'a kitchen with exactly what you need', 'category': 'party_starter'},
    {'optionA': 'win every argument but lose every competition', 'optionB': 'win every competition but lose every argument', 'category': 'party_starter'},
    {'optionA': 'have every book ever written in your head', 'optionB': 'every film ever made', 'category': 'party_starter'},
    {'optionA': 'be able to breathe fire', 'optionB': 'shoot lightning from your hands', 'category': 'party_starter'},
    {'optionA': 'have arms that are twice as long', 'optionB': 'legs that are twice as long', 'category': 'party_starter'},
    {'optionA': 'eat food that is always slightly too salty', 'optionB': 'always slightly too sweet', 'category': 'party_starter'},
    {'optionA': 'be an excellent liar everyone trusts', 'optionB': 'a terrible liar no one suspects', 'category': 'party_starter'},
    {'optionA': 'only eat food you\'ve prepared yourself', 'optionB': 'never cook and always eat out', 'category': 'party_starter'},
    {'optionA': 'travel the world alone', 'optionB': 'stay home with people you love', 'category': 'party_starter'},
    {'optionA': 'have an extra hour of daylight every day', 'optionB': 'an extra hour of night every day', 'category': 'party_starter'},
    {'optionA': 'have no last name', 'optionB': 'no first name', 'category': 'party_starter'},
    {'optionA': 'speak to your past self for one minute', 'optionB': 'your future self for one minute', 'category': 'party_starter'},
    {'optionA': 'have skills to be a world-class chef', 'optionB': 'a world-class musician', 'category': 'party_starter'},
    {'optionA': 'always be too hot for the rest of your life', 'optionB': 'always too cold', 'category': 'party_starter'},
    {'optionA': 'have a button that reverses your last decision', 'optionB': 'one that skips to the next best decision', 'category': 'party_starter'},
    {'optionA': 'always smell amazing', 'optionB': 'always feel completely physically comfortable', 'category': 'party_starter'},
    {'optionA': 'wake up with a new skill every day', 'optionB': 'one permanent new language', 'category': 'party_starter'},
    {'optionA': 'see in 360 degrees but not be able to focus', 'optionB': 'have perfect vision but only in one direction', 'category': 'party_starter'},
    {'optionA': 'know every fact about your favourite subject', 'optionB': 'know a little about absolutely everything', 'category': 'party_starter'},
    {'optionA': 'have a memory that replays only your greatest moments', 'optionB': 'only what you need to learn from', 'category': 'party_starter'},
    {'optionA': 'have a laugh that makes everyone else laugh', 'optionB': 'a smile that makes everyone feel calm', 'category': 'party_starter'},
    {'optionA': 'never have to sleep again', 'optionB': 'never have to eat again', 'category': 'party_starter'},
    {'optionA': 'live without music for a year', 'optionB': 'without social media for a year', 'category': 'party_starter'},
    {'optionA': 'be able to remember everything you\'ve ever read', 'optionB': 'everything you\'ve ever heard', 'category': 'party_starter'},
    {'optionA': 'be able to speak to your future children', 'optionB': 'your past grandparents', 'category': 'party_starter'},
    {'optionA': 'always have the perfect response ready', 'optionB': 'always know when to say nothing', 'category': 'party_starter'},
    {'optionA': 'have a house that\'s always perfectly clean', 'optionB': 'a car that\'s always perfectly full of fuel', 'category': 'party_starter'},
    {'optionA': 'have the ability to instantly learn any sport', 'optionB': 'instantly learn any language', 'category': 'party_starter'},
    {'optionA': 'know every secret about every person you\'ve ever met', 'optionB': 'have no one know any secrets about you', 'category': 'party_starter'},
    {'optionA': 'date someone wildly attractive but terrible with money', 'optionB': 'average-looking and financially sorted', 'category': 'mild_but_wild'},
    {'optionA': 'be in a relationship someone your friends don\'t like', 'optionB': 'someone your family doesn\'t approve of', 'category': 'mild_but_wild'},
    {'optionA': 'find out your partner lied about something small for a year', 'optionB': 'told one big truth you weren\'t ready for', 'category': 'mild_but_wild'},
    {'optionA': 'be ghosted after 3 amazing dates', 'optionB': 'go on 10 dates with someone you\'re not into', 'category': 'mild_but_wild'},
    {'optionA': 'be the person who always texts first', 'optionB': 'never text first and wait forever', 'category': 'mild_but_wild'},
    {'optionA': 'date someone emotionally unavailable but incredibly fun', 'optionB': 'emotionally available but slightly boring', 'category': 'mild_but_wild'},
    {'optionA': 'know all your ex\'s private thoughts about you', 'optionB': 'know exactly why every relationship ended', 'category': 'mild_but_wild'},
    {'optionA': 'find out someone you liked had feelings for you years ago', 'optionB': 'find out someone you dated moved on quickly', 'category': 'mild_but_wild'},
    {'optionA': 'always be the dumper', 'optionB': 'always be the dumpee', 'category': 'mild_but_wild'},
    {'optionA': 'be in a relationship that\'s comfortable but has no spark', 'optionB': 'one with incredible chemistry that\'s always complicated', 'category': 'mild_but_wild'},
    {'optionA': 'date someone who is always 30 minutes late', 'optionB': 'someone who shows up 30 minutes early everywhere', 'category': 'mild_but_wild'},
    {'optionA': 'have a partner who overshares everything about you', 'optionB': 'one who never opens up to anyone', 'category': 'mild_but_wild'},
    {'optionA': 'be in a long-distance relationship with someone you love', 'optionB': 'nearby with someone you\'re not sure about', 'category': 'mild_but_wild'},
    {'optionA': 'have your dating history shared with your family', 'optionB': 'your future partner\'s family see all your social media', 'category': 'mild_but_wild'},
    {'optionA': 'fall for someone who doesn\'t know you exist', 'optionB': 'have someone fall for you that you\'re not into', 'category': 'mild_but_wild'},
    {'optionA': 'go on a first date that\'s perfect but they never call back', 'optionB': 'a disastrous date that turns into something real', 'category': 'mild_but_wild'},
    {'optionA': 'be with someone terrible at communication but great in every other way', 'optionB': 'great at communicating but difficult otherwise', 'category': 'mild_but_wild'},
    {'optionA': 'have everyone know who you have a crush on', 'optionB': 'never be allowed to act on a crush', 'category': 'mild_but_wild'},
    {'optionA': 'know your person\'s entire romantic history in detail', 'optionB': 'know nothing and start fresh', 'category': 'mild_but_wild'},
    {'optionA': 'date someone completely honest even when it hurts', 'optionB': 'someone who softens everything to protect your feelings', 'category': 'mild_but_wild'},
    {'optionA': 'have a partner obsessed with you but overwhelming', 'optionB': 'perfectly balanced but slightly indifferent', 'category': 'mild_but_wild'},
    {'optionA': 'confess feelings that aren\'t returned', 'optionB': 'have feelings confessed to you that you can\'t return', 'category': 'mild_but_wild'},
    {'optionA': 'have one deeply connected relationship that ended too soon', 'optionB': 'several long relationships that all ended naturally', 'category': 'mild_but_wild'},
    {'optionA': 'date someone who gets more attractive the more you know them', 'optionB': 'someone who peaks on first impression', 'category': 'mild_but_wild'},
    {'optionA': 'have all your texts to your crush read aloud in front of you', 'optionB': 'have their texts about you read aloud', 'category': 'mild_but_wild'},
    {'optionA': 'be completely open about your feelings immediately', 'optionB': 'play it cool for months', 'category': 'mild_but_wild'},
    {'optionA': 'go back and undo your worst relationship', 'optionB': 'keep the lesson but never speak to them again', 'category': 'mild_but_wild'},
    {'optionA': 'date someone with completely opposite values but incredible energy', 'optionB': 'shares all your values but no chemistry', 'category': 'mild_but_wild'},
    {'optionA': 'be in a relationship where you love them more', 'optionB': 'where they love you more', 'category': 'mild_but_wild'},
    {'optionA': 'know your exact romantic future', 'optionB': 'be completely surprised by everything', 'category': 'mild_but_wild'},
    {'optionA': 'have an ex reach out apologizing years later', 'optionB': 'never hear from them again but be completely at peace', 'category': 'mild_but_wild'},
    {'optionA': 'be embarrassingly obvious when you have a crush', 'optionB': 'completely unreadable to the person you\'re into', 'category': 'mild_but_wild'},
    {'optionA': 'have one conversation with your ex where you both say everything', 'optionB': 'never see them again', 'category': 'mild_but_wild'},
    {'optionA': 'date someone who is intimidatingly confident', 'optionB': 'someone who is endearingly awkward', 'category': 'mild_but_wild'},
    {'optionA': 'always know if someone is interested in you', 'optionB': 'always know if someone you like isn\'t', 'category': 'mild_but_wild'},
    {'optionA': 'spend a year single and completely thriving', 'optionB': 'in a relationship you\'re not sure about', 'category': 'mild_but_wild'},
    {'optionA': 'have someone who gives you butterflies every time but is unpredictable', 'optionB': 'someone who feels like home but never surprises you', 'category': 'mild_but_wild'},
    {'optionA': 'be with someone who challenges you constantly', 'optionB': 'one who completely accepts you as you are', 'category': 'mild_but_wild'},
    {'optionA': 'have the most romantic first date of your life that leads to nothing', 'optionB': 'a deeply average first date that becomes the best relationship', 'category': 'mild_but_wild'},
    {'optionA': 'know exactly when you\'ll fall in love next', 'optionB': 'exactly how the relationship will end', 'category': 'mild_but_wild'},
    {'optionA': 'date someone great with your friends but bad one-on-one', 'optionB': 'great one-on-one but awkward with your friends', 'category': 'mild_but_wild'},
    {'optionA': 'have your partner remember every single thing you ever said', 'optionB': 'completely forget every argument', 'category': 'mild_but_wild'},
    {'optionA': 'be completely over your ex but know they\'re not over you', 'optionB': 'still feel something but know they\'ve fully moved on', 'category': 'mild_but_wild'},
    {'optionA': 'date someone incredibly spontaneous but unreliable', 'optionB': 'incredibly reliable but impossible to surprise', 'category': 'mild_but_wild'},
    {'optionA': 'have a partner who gives amazing advice but doesn\'t always listen', 'optionB': 'one who listens perfectly but gives bad advice', 'category': 'mild_but_wild'},
    {'optionA': 'fall for your best friend and have it go wrong', 'optionB': 'never fall for them and always wonder what if', 'category': 'mild_but_wild'},
    {'optionA': 'date someone very emotionally intelligent but not intellectual', 'optionB': 'very intellectual but emotionally unaware', 'category': 'mild_but_wild'},
    {'optionA': 'be in a relationship that makes you a better person in ways that feel uncomfortable', 'optionB': 'one where you\'re comfortable but not challenged', 'category': 'mild_but_wild'},
    {'optionA': 'know your partner\'s most embarrassing secret', 'optionB': 'have them know yours', 'category': 'mild_but_wild'},
    {'optionA': 'have a relationship everyone supports but you\'re unsure about', 'optionB': 'one everyone questions but feels completely right', 'category': 'mild_but_wild'},
    {'optionA': 'only date people you\'ve been friends with for years', 'optionB': 'only people you\'ve recently met', 'category': 'mild_but_wild'},
    {'optionA': 'have one great love that doesn\'t last', 'optionB': 'several meaningful relationships that all end well', 'category': 'mild_but_wild'},
    {'optionA': 'be with someone who always puts you first but forgets themselves', 'optionB': 'someone with great self-respect but who makes you work for their attention', 'category': 'mild_but_wild'},
    {'optionA': 'have a partner who remembers every special date', 'optionB': 'one who creates new special moments constantly', 'category': 'mild_but_wild'},
    {'optionA': 'find out someone was lying about something small for months', 'optionB': 'they kept something big to protect you', 'category': 'mild_but_wild'},
    {'optionA': 'have a relationship where arguments are intense but the reconnection is deep', 'optionB': 'one where you never fight but never go that deep', 'category': 'mild_but_wild'},
    {'optionA': 'be with someone who loves you the way you want to be loved but can\'t express it', 'optionB': 'someone who expresses love constantly in ways that aren\'t your love language', 'category': 'mild_but_wild'},
    {'optionA': 'end things with someone and know you made the right decision', 'optionB': 'stay and always wonder what would have happened if you left', 'category': 'mild_but_wild'},
    {'optionA': 'be with someone who has amazing stories from their past', 'optionB': 'someone whose best years seem to be ahead', 'category': 'mild_but_wild'},
    {'optionA': 'be told the hard truth by someone who loves you', 'optionB': 'be protected from it by someone who doesn\'t want to upset you', 'category': 'mild_but_wild'},
    {'optionA': 'have a partner who makes every day feel special in small ways', 'optionB': 'one who does incredible things occasionally', 'category': 'mild_but_wild'},
    {'optionA': 'be the person who loves a little more in every relationship', 'optionB': 'the person who always holds back slightly', 'category': 'mild_but_wild'},
    {'optionA': 'have your partner be your absolute best friend', 'optionB': 'your most exciting mystery', 'category': 'mild_but_wild'},
    {'optionA': 'be completely healed before entering your next relationship', 'optionB': 'learn to heal inside it', 'category': 'mild_but_wild'},
    {'optionA': 'have one conversation with the person who got away', 'optionB': 'one day back with the person you lost', 'category': 'mild_but_wild'},
    {'optionA': 'feel completely loved but a little unseen', 'optionB': 'completely seen but a little unloved', 'category': 'mild_but_wild'},
    {'optionA': 'date someone who brings out your most confident self', 'optionB': 'someone who knows your most vulnerable self', 'category': 'mild_but_wild'},
    {'optionA': 'have the most honest relationship of your life that ends', 'optionB': 'the longest relationship that lacks depth', 'category': 'mild_but_wild'},
    {'optionA': 'know with certainty that someone is the right person', 'optionB': 'spend your life believing they could be', 'category': 'mild_but_wild'},
    {'optionA': 'be in a relationship others envy but you know is imperfect', 'optionB': 'one that looks ordinary but is extraordinary within', 'category': 'mild_but_wild'},
    {'optionA': 'love someone who loves you back equally', 'optionB': 'love someone who loves you more than you love them', 'category': 'mild_but_wild'},
    {'optionA': 'always be the first to say I love you', 'optionB': 'always wait', 'category': 'mild_but_wild'},
    {'optionA': 'be with someone who remembers the version of you when you first met', 'optionB': 'someone who only knows who you are now', 'category': 'mild_but_wild'},
    {'optionA': 'have a partner who is deeply romantic in private but reserved in public', 'optionB': 'the complete opposite', 'category': 'mild_but_wild'},
    {'optionA': 'have one year of the most intense love you\'ve ever felt', 'optionB': 'ten years of steady deep love', 'category': 'mild_but_wild'},
    {'optionA': 'find someone perfect for you but at the wrong time', 'optionB': 'someone imperfect but available at exactly the right moment', 'category': 'mild_but_wild'},
    {'optionA': 'be in a relationship where you\'re the funny one', 'optionB': 'the one who appreciates the humour', 'category': 'mild_but_wild'},
    {'optionA': 'have someone who loves you through your worst moments', 'optionB': 'someone who brings out your absolute best', 'category': 'mild_but_wild'},
    {'optionA': 'be with someone who has known you forever', 'optionB': 'someone who fell in love with who you are right now', 'category': 'mild_but_wild'},
    {'optionA': 'always date people who pursue you', 'optionB': 'always be the one to pursue', 'category': 'mild_but_wild'},
    {'optionA': 'have the ability to forget every painful romantic experience', 'optionB': 'keep them all and be wiser for it', 'category': 'mild_but_wild'},
    {'optionA': 'fall for someone and take a risk you might regret', 'optionB': 'play it safe and always wonder', 'category': 'mild_but_wild'},
    {'optionA': 'be with someone unpredictable in exciting ways', 'optionB': 'someone who surprises you in quiet thoughtful ways', 'category': 'mild_but_wild'},
    {'optionA': 'have been someone\'s first love', 'optionB': 'their last', 'category': 'mild_but_wild'},
    {'optionA': 'meet the right person right now', 'optionB': 'meet them in five years when you\'re fully ready', 'category': 'mild_but_wild'},
    {'optionA': 'build something with someone from nothing', 'optionB': 'come into something already established', 'category': 'mild_but_wild'},
    {'optionA': 'be with someone who is deeply sure of you', 'optionB': 'someone you have to earn slightly', 'category': 'mild_but_wild'},
    {'optionA': 'have your greatest love story end beautifully', 'optionB': 'never end', 'category': 'mild_but_wild'},
    {'optionA': 'be loved quietly and consistently', 'optionB': 'loudly and intensely', 'category': 'mild_but_wild'},
    {'optionA': 'be with someone who makes you feel safe', 'optionB': 'someone who makes you feel completely alive', 'category': 'mild_but_wild'},
    {'optionA': 'love someone who never fully understands you', 'optionB': 'be loved by someone you never fully understand', 'category': 'mild_but_wild'},
    {'optionA': 'always choose with your head when it comes to love', 'optionB': 'always choose with your heart', 'category': 'mild_but_wild'},
    {'optionA': 'be someone\'s reason to change', 'optionB': 'the person who loved them without asking them to', 'category': 'mild_but_wild'},
    {'optionA': 'date someone who is exactly what you imagined', 'optionB': 'completely nothing like it and better', 'category': 'mild_but_wild'},
    {'optionA': 'be in a relationship where the physical side is perfect', 'optionB': 'where the emotional depth is like nothing you\'ve known', 'category': 'mild_but_wild'},
    {'optionA': 'feel electricity every time you see someone for a year', 'optionB': 'warmth every time for a lifetime', 'category': 'mild_but_wild'},
    {'optionA': 'be the person someone always came back to', 'optionB': 'the person they finally stopped leaving', 'category': 'mild_but_wild'},
    {'optionA': 'love someone who never quite said it back', 'optionB': 'be loved by someone you couldn\'t fully love in return', 'category': 'mild_but_wild'},
    {'optionA': 'have one defining relationship that gave you everything you needed to grow', 'optionB': 'several that each gave you a piece', 'category': 'mild_but_wild'},
    {'optionA': 'be the person who made someone believe in love', 'optionB': 'the person who made them want to be better', 'category': 'mild_but_wild'},
    {'optionA': 'your family could read your text messages', 'optionB': 'your diary', 'category': 'family_night'},
    {'optionA': 'have a family holiday every year somewhere new', 'optionB': 'always return to the same beloved place', 'category': 'family_night'},
    {'optionA': 'swap lives with a sibling for a week', 'optionB': 'swap lives with a parent for a week', 'category': 'family_night'},
    {'optionA': 'your family always knew exactly how you were feeling', 'optionB': 'never knew unless you told them', 'category': 'family_night'},
    {'optionA': 'have one big family dinner every week with everyone present', 'optionB': 'small catch-ups throughout the week', 'category': 'family_night'},
    {'optionA': 'your family remembered every embarrassing thing you did as a child', 'optionB': 'completely forgot all of it', 'category': 'family_night'},
    {'optionA': 'have 5 siblings', 'optionB': 'be an only child', 'category': 'family_night'},
    {'optionA': 'your family gave you complete honesty about your decisions', 'optionB': 'always supported you even when they disagreed', 'category': 'family_night'},
    {'optionA': 'all family events happen at your home', 'optionB': 'always at someone else\'s', 'category': 'family_night'},
    {'optionA': 'have a family that is wildly funny but chaotic', 'optionB': 'very calm but slightly boring', 'category': 'family_night'},
    {'optionA': 'have a family member who always gives excellent advice', 'optionB': 'one who always makes you laugh', 'category': 'family_night'},
    {'optionA': 'go on the most adventurous holiday with your family', 'optionB': 'the most relaxing one', 'category': 'family_night'},
    {'optionA': 'have family game nights every week', 'optionB': 'family movie nights every week', 'category': 'family_night'},
    {'optionA': 'live 5 minutes from your family', 'optionB': '5 hours away', 'category': 'family_night'},
    {'optionA': 'every family gathering have a theme', 'optionB': 'be completely spontaneous', 'category': 'family_night'},
    {'optionA': 'all family members had the same talent', 'optionB': 'each had a completely different skill', 'category': 'family_night'},
    {'optionA': 'your family always celebrated every achievement', 'optionB': 'never made a fuss and let you process privately', 'category': 'family_night'},
    {'optionA': 'a family member showed up to surprise you', 'optionB': 'you always knew when visits were planned', 'category': 'family_night'},
    {'optionA': 'have a family that travels together every year', 'optionB': 'builds something together at home', 'category': 'family_night'},
    {'optionA': 'know your full family history in complete detail', 'optionB': 'discover it slowly over your lifetime', 'category': 'family_night'},
    {'optionA': 'have a large loud family with lots of cousins', 'optionB': 'a small close family with no extended relatives', 'category': 'family_night'},
    {'optionA': 'your family always spoke their minds', 'optionB': 'always kept the peace', 'category': 'family_night'},
    {'optionA': 'spend every birthday with your family', 'optionB': 'choose differently each year', 'category': 'family_night'},
    {'optionA': 'have a family tradition that lasts forever', 'optionB': 'create a new one every year', 'category': 'family_night'},
    {'optionA': 'all your family members lived in the same city', 'optionB': 'were spread all over the world', 'category': 'family_night'},
    {'optionA': 'always win every argument with a family member', 'optionB': 'never argue but sometimes feel unheard', 'category': 'family_night'},
    {'optionA': 'be the family member everyone calls for advice', 'optionB': 'the one they call to cheer them up', 'category': 'family_night'},
    {'optionA': 'have a family pet you all agree on', 'optionB': 'each have your own independent pet', 'category': 'family_night'},
    {'optionA': 'your family always arrived exactly on time', 'optionB': 'always arrived with something delicious', 'category': 'family_night'},
    {'optionA': 'have a family where everyone is an amazing cook', 'optionB': 'where no one cooks but everyone orders from great places', 'category': 'family_night'},
    {'optionA': 'your family celebrated every holiday in a big way', 'optionB': 'kept everything small and personal', 'category': 'family_night'},
    {'optionA': 'have a family group chat that\'s always active', 'optionB': 'one that only gets used when it truly matters', 'category': 'family_night'},
    {'optionA': 'every family member supported your dreams completely', 'optionB': 'told you the truth about what they really thought', 'category': 'family_night'},
    {'optionA': 'the family home stayed exactly the same forever', 'optionB': 'changed completely every 10 years', 'category': 'family_night'},
    {'optionA': 'have a family reunion every year', 'optionB': 'once every decade and make it truly special', 'category': 'family_night'},
    {'optionA': 'your family be incredibly generous with time', 'optionB': 'incredibly generous with words', 'category': 'family_night'},
    {'optionA': 'grow up in a big messy house full of laughter', 'optionB': 'a quiet tidy home full of peace', 'category': 'family_night'},
    {'optionA': 'your family always showed affection openly', 'optionB': 'expressed love through actions', 'category': 'family_night'},
    {'optionA': 'have a family that gave you total freedom as a child', 'optionB': 'clear boundaries and structure', 'category': 'family_night'},
    {'optionA': 'know every family secret', 'optionB': 'be completely in the dark and happily so', 'category': 'family_night'},
    {'optionA': 'the best family memory you have replayed every year', 'optionB': 'keep creating new ones that get better', 'category': 'family_night'},
    {'optionA': 'a family member never missed a single moment of your life', 'optionB': 'always gave you space to grow', 'category': 'family_night'},
    {'optionA': 'every family dinner be around the table together', 'optionB': 'everyone free to eat wherever they\'re comfortable', 'category': 'family_night'},
    {'optionA': 'your family had a saying that was famous among friends', 'optionB': 'a recipe that was known everywhere', 'category': 'family_night'},
    {'optionA': 'always have your family\'s backing even when you were wrong', 'optionB': 'their honest critique even when it stings', 'category': 'family_night'},
    {'optionA': 'be in a family that pushed you to be your best', 'optionB': 'one that loved every version of you equally', 'category': 'family_night'},
    {'optionA': 'have a family photo taken every year capturing honest truth', 'optionB': 'one that showed only the best', 'category': 'family_night'},
    {'optionA': 'celebrate every family member\'s success loudly', 'optionB': 'quietly with just the people who mattered', 'category': 'family_night'},
    {'optionA': 'every family member knew your biggest dream', 'optionB': 'only the people you chose to tell', 'category': 'family_night'},
    {'optionA': 'have a family that gave you roots', 'optionB': 'a family that gave you wings — if you could only choose one', 'category': 'family_night'},
    {'optionA': 'always be the youngest in the family', 'optionB': 'always be the oldest', 'category': 'family_night'},
    {'optionA': 'have a family that encouraged you to take risks', 'optionB': 'one that made sure you were always safe first', 'category': 'family_night'},
    {'optionA': 'have family members who are brutally honest critics', 'optionB': 'enthusiastic supporters of everything you do', 'category': 'family_night'},
    {'optionA': 'your family always made time for you', 'optionB': 'gave you complete independence but was there when needed', 'category': 'family_night'},
    {'optionA': 'be incredibly close to your immediate family', 'optionB': 'have a huge extended family you see regularly', 'category': 'family_night'},
    {'optionA': 'always feel understood by your family', 'optionB': 'always feel motivated by them', 'category': 'family_night'},
    {'optionA': 'have a family member who taught you something you still use every day', 'optionB': 'one who showed you something once that changed everything', 'category': 'family_night'},
    {'optionA': 'know what your family really thinks of your life choices', 'optionB': 'blissfully not know', 'category': 'family_night'},
    {'optionA': 'your family shared all major news in person', 'optionB': 'over a video call all together', 'category': 'family_night'},
    {'optionA': 'be remembered in your family as the funniest member', 'optionB': 'the most successful', 'category': 'family_night'},
    {'optionA': 'have the same values as everyone in your family', 'optionB': 'different values that spark great conversations', 'category': 'family_night'},
    {'optionA': 'every family member came to every milestone in your life', 'optionB': 'only the ones you specifically asked', 'category': 'family_night'},
    {'optionA': 'your family laughed at hard things together', 'optionB': 'treated difficult things seriously but with love', 'category': 'family_night'},
    {'optionA': 'have a parent who was your best friend', 'optionB': 'one who was your greatest teacher', 'category': 'family_night'},
    {'optionA': 'have a sibling you could tell anything to', 'optionB': 'one you could completely rely on', 'category': 'family_night'},
    {'optionA': 'the family cooked together on weekends', 'optionB': 'had long drives with the best playlists', 'category': 'family_night'},
    {'optionA': 'grow older knowing exactly how your family saw you', 'optionB': 'discover their words about you only later in letters', 'category': 'family_night'},
    {'optionA': 'your family gave you advice through stories', 'optionB': 'through direct honest conversation', 'category': 'family_night'},
    {'optionA': 'have a family that documented every moment in photos', 'optionB': 'lived every moment without a camera', 'category': 'family_night'},
    {'optionA': 'a family member helped you through something without being asked', 'optionB': 'respected your boundaries until you did', 'category': 'family_night'},
    {'optionA': 'have a family name people recognised and had to live up to', 'optionB': 'a family no one knew but that shaped everything you became', 'category': 'family_night'},
    {'optionA': 'your family gave you everything you needed', 'optionB': 'taught you to provide it for yourself', 'category': 'family_night'},
    {'optionA': 'your family told you less and showed you more', 'optionB': 'told you everything they felt', 'category': 'family_night'},
    {'optionA': 'be the family member who holds everyone together', 'optionB': 'the one who inspires everyone to be better', 'category': 'family_night'},
    {'optionA': 'your family always made you laugh at the hardest moments', 'optionB': 'cried with you instead', 'category': 'family_night'},
    {'optionA': 'a family member gave you the truth you needed at 16', 'optionB': 'at 26', 'category': 'family_night'},
    {'optionA': 'have a family where everyone had the same sense of humour', 'optionB': 'completely different ones that somehow worked together', 'category': 'family_night'},
    {'optionA': 'your family\'s greatest lesson came through something difficult', 'optionB': 'something wonderful', 'category': 'family_night'},
    {'optionA': 'be shaped more by your family\'s strengths', 'optionB': 'by their honest limitations', 'category': 'family_night'},
    {'optionA': 'have a family meal where everyone put their phones down completely', 'optionB': 'where everyone was free to be themselves', 'category': 'family_night'},
    {'optionA': 'the family you grew up in stayed exactly the same', 'optionB': 'evolved into something even better over time', 'category': 'family_night'},
    {'optionA': 'have a family that celebrated who you were becoming', 'optionB': 'who you already were', 'category': 'family_night'},
    {'optionA': 'know that your family was always proud of you', 'optionB': 'that they always believed in you', 'category': 'family_night'},
    {'optionA': 'a family member changed your life by something they said', 'optionB': 'something they did', 'category': 'family_night'},
    {'optionA': 'have a family that is present in small daily moments', 'optionB': 'there for the biggest ones', 'category': 'family_night'},
    {'optionA': 'inherit a family tradition that changed how you lived', 'optionB': 'a family value that changed how you thought', 'category': 'family_night'},
    {'optionA': 'grow up knowing exactly how loved you were', 'optionB': 'discover it slowly over decades', 'category': 'family_night'},
    {'optionA': 'have a family that asked good questions', 'optionB': 'one that always had good answers', 'category': 'family_night'},
    {'optionA': 'your family\'s story were written as a comedy', 'optionB': 'a deeply moving drama', 'category': 'family_night'},
    {'optionA': 'every family gathering ended in music', 'optionB': 'in a story told by the oldest person present', 'category': 'family_night'},
    {'optionA': 'your family remembered you for the moments you showed up', 'optionB': 'the things you said', 'category': 'family_night'},
    {'optionA': 'the family you are part of now defined who you became', 'optionB': 'who you chose to be defined it', 'category': 'family_night'},
    {'optionA': 'always have something to talk about at family dinners', 'optionB': 'the most comfortable silence', 'category': 'family_night'},
    {'optionA': 'your family legacy be something they built', 'optionB': 'something they believed in', 'category': 'family_night'},
    {'optionA': 'have a family that let you figure things out', 'optionB': 'one that always stepped in to help', 'category': 'family_night'},
    {'optionA': 'every family member remembered the same stories', 'optionB': 'each had completely different memories of the same event', 'category': 'family_night'},
    {'optionA': 'your family always had the right thing to say', 'optionB': 'always knew when to say nothing', 'category': 'family_night'},
    {'optionA': 'grow up in a family that was serious about education', 'optionB': 'one that was serious about having fun', 'category': 'family_night'},
    {'optionA': 'the happiest family memory you have happened recently', 'optionB': 'years ago', 'category': 'family_night'},
    {'optionA': 'your family knew everything about who you are now', 'optionB': 'knew everything about who you used to be', 'category': 'family_night'},
    {'optionA': 'date someone incredibly attractive who has no emotional intelligence', 'optionB': 'someone average-looking with extraordinary emotional intelligence', 'category': 'spice_it_up'},
    {'optionA': 'find out your partner has been secretly admiring someone else for months', 'optionB': 'that someone has been secretly admiring your partner', 'category': 'spice_it_up'},
    {'optionA': 'have one unforgettable night with someone you\'ll never see again', 'optionB': 'years of something real but slightly complicated', 'category': 'spice_it_up'},
    {'optionA': 'be with someone who drives you crazy in the best way', 'optionB': 'someone who brings you complete calm', 'category': 'spice_it_up'},
    {'optionA': 'know exactly what your partner thinks of you at all times', 'optionB': 'never have access to any of it', 'category': 'spice_it_up'},
    {'optionA': 'have the most passionate relationship of your life that burns out in a year', 'optionB': 'the longest relationship of your life with steady low heat', 'category': 'spice_it_up'},
    {'optionA': 'your ex sees you at your absolute best right now', 'optionB': 'your current partner saw every version you\'ve ever been', 'category': 'spice_it_up'},
    {'optionA': 'be someone\'s greatest love story that ended', 'optionB': 'their longest story that continued', 'category': 'spice_it_up'},
    {'optionA': 'find out your partner had a list of people they found attractive', 'optionB': 'know you were the only person they ever truly wanted', 'category': 'spice_it_up'},
    {'optionA': 'be irresistibly attractive to everyone but have terrible chemistry with the person you want', 'optionB': 'average to everyone but extraordinary chemistry with one person', 'category': 'spice_it_up'},
    {'optionA': 'have complete honesty in a relationship at the cost of some comfort', 'optionB': 'comfort with some things left unsaid', 'category': 'spice_it_up'},
    {'optionA': 'date someone who wants you passionately but inconsistently', 'optionB': 'someone who wants you calmly and consistently', 'category': 'spice_it_up'},
    {'optionA': 'spend one incredibly honest night talking to someone who completely gets you', 'optionB': 'one night of undeniable physical chemistry with no conversation', 'category': 'spice_it_up'},
    {'optionA': 'your partner told you everything they felt instantly', 'optionB': 'held feelings until they were certain', 'category': 'spice_it_up'},
    {'optionA': 'be wanted by many and chosen by none', 'optionB': 'wanted by one and completely chosen', 'category': 'spice_it_up'},
    {'optionA': 'know your partner\'s number', 'optionB': 'not know and never ask', 'category': 'spice_it_up'},
    {'optionA': 'have a relationship that looked perfect from the outside', 'optionB': 'one that was perfect inside and no one understood', 'category': 'spice_it_up'},
    {'optionA': 'your partner be your greatest adventure', 'optionB': 'your safest place', 'category': 'spice_it_up'},
    {'optionA': 'have a connection so intense it was almost unsettling', 'optionB': 'one so comfortable it felt effortless', 'category': 'spice_it_up'},
    {'optionA': 'fall for someone who makes your heart race', 'optionB': 'someone who makes you stop thinking completely', 'category': 'spice_it_up'},
    {'optionA': 'be with someone who has never loved anyone as much as you', 'optionB': 'someone who loved deeply before and brought everything they learned', 'category': 'spice_it_up'},
    {'optionA': 'know the moment a relationship will end before it begins', 'optionB': 'be completely surprised', 'category': 'spice_it_up'},
    {'optionA': 'have chemistry that\'s undeniable but timing that\'s completely wrong', 'optionB': 'timing that\'s perfect but chemistry that needs to be built', 'category': 'spice_it_up'},
    {'optionA': 'be remembered as the one someone loved the most', 'optionB': 'the one someone couldn\'t forget', 'category': 'spice_it_up'},
    {'optionA': 'have a partner who made every day feel like something', 'optionB': 'one who made one day a year completely unforgettable', 'category': 'spice_it_up'},
    {'optionA': 'stay in something that feels good but isn\'t growing', 'optionB': 'leave for something unknown that could be everything', 'category': 'spice_it_up'},
    {'optionA': 'your greatest love story be one people knew about', 'optionB': 'one only the two of you carried', 'category': 'spice_it_up'},
    {'optionA': 'be someone\'s reason to change', 'optionB': 'the person who loved them without asking them to', 'category': 'spice_it_up'},
    {'optionA': 'date someone who is exactly what you imagined', 'optionB': 'completely nothing like it and better', 'category': 'spice_it_up'},
    {'optionA': 'be in a relationship where the physical side is perfect', 'optionB': 'where the emotional depth is unlike anything you\'ve known', 'category': 'spice_it_up'},
    {'optionA': 'be with someone who made you feel powerful', 'optionB': 'someone who made you feel safe', 'category': 'spice_it_up'},
    {'optionA': 'confess something you\'ve been holding onto', 'optionB': 'have someone confess something they\'ve been keeping from you', 'category': 'spice_it_up'},
    {'optionA': 'know the exact moment someone fell for you', 'optionB': 'know the exact moment they started to fall away', 'category': 'spice_it_up'},
    {'optionA': 'your most passionate relationship had never ended', 'optionB': 'never started', 'category': 'spice_it_up'},
    {'optionA': 'be someone\'s first great love', 'optionB': 'their last great love', 'category': 'spice_it_up'},
    {'optionA': 'have a partner who challenged every comfortable belief you had', 'optionB': 'one who made peace with every part of you', 'category': 'spice_it_up'},
    {'optionA': 'be completely undone by someone who didn\'t stay', 'optionB': 'remain entirely composed through a life that stayed exactly the same', 'category': 'spice_it_up'},
    {'optionA': 'have one conversation that changed everything', 'optionB': 'one night that you never quite recovered from', 'category': 'spice_it_up'},
    {'optionA': 'someone fought for you when you walked away', 'optionB': 'let you go cleanly and completely', 'category': 'spice_it_up'},
    {'optionA': 'your partner knew exactly what you needed without asking', 'optionB': 'asked you directly and got it right every time', 'category': 'spice_it_up'},
    {'optionA': 'be in love and terrified', 'optionB': 'not in love and perfectly comfortable', 'category': 'spice_it_up'},
    {'optionA': 'have a relationship that moved fast and burned hard', 'optionB': 'one that started slowly and never fully burned out', 'category': 'spice_it_up'},
    {'optionA': 'your partner was everything you planned for', 'optionB': 'everything you never planned but always needed', 'category': 'spice_it_up'},
    {'optionA': 'be with someone you could tell absolutely anything to', 'optionB': 'someone who told you absolutely everything', 'category': 'spice_it_up'},
    {'optionA': 'your greatest relationship have happened at a different time in your life', 'optionB': 'exactly when it did', 'category': 'spice_it_up'},
    {'optionA': 'be with someone who would do anything for you', 'optionB': 'someone you\'d do anything for', 'category': 'spice_it_up'},
    {'optionA': 'your partner saw you at your most vulnerable and stayed', 'optionB': 'your most confident and was drawn in', 'category': 'spice_it_up'},
    {'optionA': 'have a relationship that cost you something but taught you everything', 'optionB': 'one that cost nothing and gave you comfort', 'category': 'spice_it_up'},
    {'optionA': 'be the person who made someone believe in love', 'optionB': 'the person who made them want to be better', 'category': 'spice_it_up'},
    {'optionA': 'spend a week in complete honesty with your partner where nothing is held back', 'optionB': 'a week where everything is perfect but surface level', 'category': 'spice_it_up'},
    {'optionA': 'your partner chose you after considering everyone else', 'optionB': 'chose you before they\'d even finished looking', 'category': 'spice_it_up'},
    {'optionA': 'be completely loved without having to ask for it', 'optionB': 'have to ask clearly and be given it perfectly', 'category': 'spice_it_up'},
    {'optionA': 'have a love that was simple and absolutely real', 'optionB': 'one that was complicated and absolutely alive', 'category': 'spice_it_up'},
    {'optionA': 'your partner\'s greatest memory of you be something you said', 'optionB': 'something you did', 'category': 'spice_it_up'},
    {'optionA': 'be with someone who loved your potential', 'optionB': 'someone who loved your reality', 'category': 'spice_it_up'},
    {'optionA': 'know a love that was slightly wrong but felt completely right', 'optionB': 'one that was right on paper and felt almost right', 'category': 'spice_it_up'},
    {'optionA': 'have a partner who stayed through your worst chapter', 'optionB': 'arrived in time for your best one', 'category': 'spice_it_up'},
    {'optionA': 'be more desired', 'optionB': 'more deeply known', 'category': 'spice_it_up'},
    {'optionA': 'fall for someone at the worst possible time', 'optionB': 'meet the right person when you had nothing to offer', 'category': 'spice_it_up'},
    {'optionA': 'be someone\'s greatest chapter', 'optionB': 'their favourite sentence in every chapter', 'category': 'spice_it_up'},
    {'optionA': 'have been someone\'s first choice from the beginning', 'optionB': 'the one they eventually chose after everything', 'category': 'spice_it_up'},
    {'optionA': 'your love story be remembered for how it started', 'optionB': 'how it lasted', 'category': 'spice_it_up'},
    {'optionA': 'feel electricity every time you see someone for a year', 'optionB': 'warmth every time for a lifetime', 'category': 'spice_it_up'},
    {'optionA': 'your partner be honest about every flaw they saw in you', 'optionB': 'kept them private and loved you despite them', 'category': 'spice_it_up'},
    {'optionA': 'love someone who never quite said it back', 'optionB': 'be loved by someone you couldn\'t fully love in return', 'category': 'spice_it_up'},
    {'optionA': 'have one defining relationship that gave you everything you needed to grow', 'optionB': 'several that each gave you a piece', 'category': 'spice_it_up'},
    {'optionA': 'your partner chose to stay in your hardest moment', 'optionB': 'know they wanted to leave and chose not to', 'category': 'spice_it_up'},
    {'optionA': 'be the person someone always came back to', 'optionB': 'the person they finally stopped leaving', 'category': 'spice_it_up'},
    {'optionA': 'have the love you imagined at 18', 'optionB': 'the love you needed at 28', 'category': 'spice_it_up'},
    {'optionA': 'know a love that changed the entire direction of your life', 'optionB': 'a love that gave you back the life you\'d lost', 'category': 'spice_it_up'},
    {'optionA': 'your most significant relationship have ended differently', 'optionB': 'started differently', 'category': 'spice_it_up'},
    {'optionA': 'be someone\'s safe place', 'optionB': 'their greatest discovery', 'category': 'spice_it_up'},
    {'optionA': 'be loved for who you were when you first met', 'optionB': 'for who you became along the way', 'category': 'spice_it_up'},
    {'optionA': 'have a partner who loved you loudly and imperfectly', 'optionB': 'quietly and completely', 'category': 'spice_it_up'},
    {'optionA': 'fall in love slowly and certainly', 'optionB': 'fast and completely without warning', 'category': 'spice_it_up'},
    {'optionA': 'your love story be a quiet everyday thing', 'optionB': 'a once in a lifetime extraordinary thing', 'category': 'spice_it_up'},
    {'optionA': 'be with someone who brought out a version of yourself you hadn\'t met yet', 'optionB': 'someone who reminded you of who you always were', 'category': 'spice_it_up'},
    {'optionA': 'your partner fight for you in the moment', 'optionB': 'show up months later completely changed', 'category': 'spice_it_up'},
    {'optionA': 'spend your greatest chapter with one person', 'optionB': 'have each chapter shared with the person right for it', 'category': 'spice_it_up'},
    {'optionA': 'know a love that healed you', 'optionB': 'one that showed you how strong you were', 'category': 'spice_it_up'},
    {'optionA': 'love someone who knew every version of you', 'optionB': 'someone who only knew the best one', 'category': 'spice_it_up'},
    {'optionA': 'leave something good for something potentially great', 'optionB': 'stay in something good knowing great was possible', 'category': 'spice_it_up'},
    {'optionA': 'be loved the way you love', 'optionB': 'the way you needed to be loved', 'category': 'spice_it_up'},
    {'optionA': 'carry a love you never expressed', 'optionB': 'know that you said everything and still lost them', 'category': 'spice_it_up'},
    {'optionA': 'have been brave enough to say something sooner', 'optionB': 'wise enough to say nothing at all', 'category': 'spice_it_up'},
    {'optionA': 'be remembered as the person who loved without conditions', 'optionB': 'the person who loved without losing themselves', 'category': 'spice_it_up'},
    {'optionA': 'have found your person in a moment you almost didn\'t show up for', 'optionB': 'in the most inevitable place imaginable', 'category': 'spice_it_up'},
    {'optionA': 'be someone\'s reason to stay', 'optionB': 'their reason to finally go', 'category': 'spice_it_up'},
    {'optionA': 'love someone completely knowing it would end', 'optionB': 'hold back and know it could have been more', 'category': 'spice_it_up'},
    {'optionA': 'be the kind of love that changed someone', 'optionB': 'the kind that was always exactly enough', 'category': 'spice_it_up'},
    {'optionA': 'have a love that asked nothing of you', 'optionB': 'one that drew out everything you had', 'category': 'spice_it_up'},
    {'optionA': 'be the first person someone truly chose', 'optionB': 'the last person they ever needed to', 'category': 'spice_it_up'},
    {'optionA': 'know you were someone\'s greatest love', 'optionB': 'know you were their most important lesson', 'category': 'spice_it_up'},
    {'optionA': 'be with someone who loved you before they even knew you well', 'optionB': 'someone who loved you more the longer they knew you', 'category': 'spice_it_up'},
    {'optionA': 'have a partner who always showed up for you in public', 'optionB': 'one who always showed up for you in private', 'category': 'spice_it_up'},
    {'optionA': 'know that you were deeply loved by one person', 'optionB': 'liked by many people', 'category': 'spice_it_up'},
    {'optionA': 'end a relationship that still had love but not a future', 'optionB': 'stay in one that had a future but the love had faded', 'category': 'spice_it_up'},
    {'optionA': 'be someone who made love feel easy', 'optionB': 'someone who made love feel worth it', 'category': 'spice_it_up'},
    {'optionA': 'your most significant relationship be the one that taught you the most', 'optionB': 'the one that hurt the least', 'category': 'spice_it_up'},
    {'optionA': 'be loved for your flaws', 'optionB': 'loved despite them', 'category': 'spice_it_up'},
    {'optionA': 'have the most aesthetic life with no real depth', 'optionB': 'a messy chaotic life that felt completely alive', 'category': 'girls_night'},
    {'optionA': 'be completely unbothered for the rest of your life', 'optionB': 'always feel deeply but deal with it better', 'category': 'girls_night'},
    {'optionA': 'always look effortlessly put together', 'optionB': 'always feel effortlessly confident', 'category': 'girls_night'},
    {'optionA': 'have a best friend who tells you every hard truth', 'optionB': 'one who hypes you up no matter what', 'category': 'girls_night'},
    {'optionA': 'spend a year being completely single and growing', 'optionB': 'in a comfortable relationship going nowhere', 'category': 'girls_night'},
    {'optionA': 'always know what someone really thought of your outfit', 'optionB': 'never care what anyone thought ever again', 'category': 'girls_night'},
    {'optionA': 'have the best girls trip of your life every year', 'optionB': 'the most meaningful one-on-one friendship moment once in a lifetime', 'category': 'girls_night'},
    {'optionA': 'be the friend everyone calls when they need advice', 'optionB': 'the friend everyone calls when they need to laugh', 'category': 'girls_night'},
    {'optionA': 'have a circle of 10 friends mostly surface level', 'optionB': '2 friends who knew absolutely everything', 'category': 'girls_night'},
    {'optionA': 'always say exactly what you mean to a man', 'optionB': 'always know exactly what he meant to you', 'category': 'girls_night'},
    {'optionA': 'never have to worry about your appearance again', 'optionB': 'never worry about how you came across socially', 'category': 'girls_night'},
    {'optionA': 'be the most stylish person in every room', 'optionB': 'the most magnetic', 'category': 'girls_night'},
    {'optionA': 'your main era be creative and chaotic', 'optionB': 'structured and thriving', 'category': 'girls_night'},
    {'optionA': 'be the girl who always showed up for others', 'optionB': 'the one who finally showed up for herself', 'category': 'girls_night'},
    {'optionA': 'always have the perfect response in an argument', 'optionB': 'always be able to leave one cleanly', 'category': 'girls_night'},
    {'optionA': 'never have another situationship', 'optionB': 'have one last one that actually resolved properly', 'category': 'girls_night'},
    {'optionA': 'be completely emotionally healed before your next relationship', 'optionB': 'grow within it', 'category': 'girls_night'},
    {'optionA': 'your glow up happen where everyone who knew the old you could see it', 'optionB': 'somewhere completely new', 'category': 'girls_night'},
    {'optionA': 'have a life that looked incredible online but felt ordinary', 'optionB': 'looked ordinary online and felt extraordinary', 'category': 'girls_night'},
    {'optionA': 'always be the most put-together person in your group', 'optionB': 'the most authentic', 'category': 'girls_night'},
    {'optionA': 'be loved by a man who showed up every single day consistently', 'optionB': 'one who showed up in the grandest way occasionally', 'category': 'girls_night'},
    {'optionA': 'your greatest era be before 25', 'optionB': 'after 30', 'category': 'girls_night'},
    {'optionA': 'know exactly who you are by 22', 'optionB': 'discover yourself slowly through your 30s', 'category': 'girls_night'},
    {'optionA': 'never have to deal with a toxic friendship again', 'optionB': 'always be able to see them coming', 'category': 'girls_night'},
    {'optionA': 'be someone who built something', 'optionB': 'someone who changed something', 'category': 'girls_night'},
    {'optionA': 'always have perfect skin', 'optionB': 'perfect energy', 'category': 'girls_night'},
    {'optionA': 'be completely independent and occasionally lonely', 'optionB': 'deeply connected and occasionally overwhelmed', 'category': 'girls_night'},
    {'optionA': 'your confidence came from how you looked', 'optionB': 'from what you\'d been through', 'category': 'girls_night'},
    {'optionA': 'always speak your mind completely', 'optionB': 'choose your words perfectly every single time', 'category': 'girls_night'},
    {'optionA': 'be known for your warmth', 'optionB': 'your strength', 'category': 'girls_night'},
    {'optionA': 'your most important friendship be the longest one you had', 'optionB': 'the most honest one', 'category': 'girls_night'},
    {'optionA': 'always be the one who cared a little less', 'optionB': 'the one who cared a little more', 'category': 'girls_night'},
    {'optionA': 'have a life with no regrets but fewer experiences', 'optionB': 'a life full of experiences with a handful of significant regrets', 'category': 'girls_night'},
    {'optionA': 'your best chapter be one you shared with someone else', 'optionB': 'one you built entirely alone', 'category': 'girls_night'},
    {'optionA': 'your style always turned heads', 'optionB': 'always felt completely you', 'category': 'girls_night'},
    {'optionA': 'have a conversation that changed everything about how you saw yourself', 'optionB': 'one that changed how you saw someone else', 'category': 'girls_night'},
    {'optionA': 'your love life be quiet and consistent', 'optionB': 'unpredictable and electric', 'category': 'girls_night'},
    {'optionA': 'always be the person who left', 'optionB': 'the one who was left but moved on better', 'category': 'girls_night'},
    {'optionA': 'date someone who was exactly what you wanted at 20', 'optionB': 'what you actually needed at 27', 'category': 'girls_night'},
    {'optionA': 'your career and love life peak at the same time', 'optionB': 'one arrive first so you were ready for the other', 'category': 'girls_night'},
    {'optionA': 'be loved for being soft', 'optionB': 'for being strong', 'category': 'girls_night'},
    {'optionA': 'have the kind of friendship where nothing needed to be explained', 'optionB': 'the kind where everything was said anyway', 'category': 'girls_night'},
    {'optionA': 'your life story be one people would read', 'optionB': 'one they would feel', 'category': 'girls_night'},
    {'optionA': 'have beauty that was striking', 'optionB': 'beauty that people couldn\'t quite explain', 'category': 'girls_night'},
    {'optionA': 'always be the most memorable person in any room', 'optionB': 'always be the most comfortable one to be around', 'category': 'girls_night'},
    {'optionA': 'have a best friend who challenged you to be better', 'optionB': 'one who loved every version of you exactly as it was', 'category': 'girls_night'},
    {'optionA': 'spend your 20s building something', 'optionB': 'experiencing everything', 'category': 'girls_night'},
    {'optionA': 'be with someone who made you feel chosen', 'optionB': 'someone who made you feel free', 'category': 'girls_night'},
    {'optionA': 'heal loudly with people around you', 'optionB': 'quietly and mostly alone', 'category': 'girls_night'},
    {'optionA': 'know someone was right for you immediately', 'optionB': 'only realize it looking back', 'category': 'girls_night'},
    {'optionA': 'be the kind of woman who transformed under pressure', 'optionB': 'one who remained steady through it', 'category': 'girls_night'},
    {'optionA': 'be remembered by the men you dated for the way you made them feel', 'optionB': 'the way you handled the ending', 'category': 'girls_night'},
    {'optionA': 'have a year of your absolute personal best', 'optionB': 'a year that brought you your greatest love', 'category': 'girls_night'},
    {'optionA': 'always be the planner in your friend group', 'optionB': 'the one who just showed up and made everything better', 'category': 'girls_night'},
    {'optionA': 'know your worth from early on', 'optionB': 'earn it slowly through experience', 'category': 'girls_night'},
    {'optionA': 'be in a friendship group where everyone was thriving', 'optionB': 'one where you all figured it out together', 'category': 'girls_night'},
    {'optionA': 'your era be quiet growth that surprised everyone', 'optionB': 'loud success that was completely expected', 'category': 'girls_night'},
    {'optionA': 'always express exactly how you feel', 'optionB': 'become so self-assured that your feelings didn\'t need to be justified', 'category': 'girls_night'},
    {'optionA': 'have a community who rallied around you publicly', 'optionB': 'one person who knew everything privately', 'category': 'girls_night'},
    {'optionA': 'your most significant friendship be one that lasted forever', 'optionB': 'one that was only for a season but shaped everything', 'category': 'girls_night'},
    {'optionA': 'your energy be the first thing people felt', 'optionB': 'the last thing they remembered', 'category': 'girls_night'},
    {'optionA': 'always find the words to say the right thing', 'optionB': 'learn when to say nothing at all', 'category': 'girls_night'},
    {'optionA': 'feel beautiful on the best days', 'optionB': 'feel enough on the worst ones', 'category': 'girls_night'},
    {'optionA': 'always be the one chosen first', 'optionB': 'wait for the right moment to be chosen', 'category': 'girls_night'},
    {'optionA': 'have a glow up that was visible', 'optionB': 'one that was entirely internal', 'category': 'girls_night'},
    {'optionA': 'always be the realest person in the room', 'optionB': 'the kindest', 'category': 'girls_night'},
    {'optionA': 'your most honest friendship be with someone who knew the old you', 'optionB': 'someone who only knows who you are right now', 'category': 'girls_night'},
    {'optionA': 'carry the version of yourself from 5 years ago forward', 'optionB': 'leave her behind completely', 'category': 'girls_night'},
    {'optionA': 'be loved for your best self', 'optionB': 'through your most difficult one', 'category': 'girls_night'},
    {'optionA': 'be the type of woman who made everything look easy', 'optionB': 'one who made it clear how hard she worked', 'category': 'girls_night'},
    {'optionA': 'always know when to stay in a friendship', 'optionB': 'when to let it go', 'category': 'girls_night'},
    {'optionA': 'have the kind of success that opened doors', 'optionB': 'the kind that changed how you moved through them', 'category': 'girls_night'},
    {'optionA': 'your greatest lesson come from love', 'optionB': 'from losing something you built', 'category': 'girls_night'},
    {'optionA': 'be surrounded by people who admired you', 'optionB': 'people who genuinely knew you', 'category': 'girls_night'},
    {'optionA': 'be the friend who always showed up', 'optionB': 'the one who showed up differently each time but always right', 'category': 'girls_night'},
    {'optionA': 'be completely sure of yourself in every decision', 'optionB': 'always make the most honest choice even when uncertain', 'category': 'girls_night'},
    {'optionA': 'be someone people remembered for something they saw', 'optionB': 'something they felt', 'category': 'girls_night'},
    {'optionA': 'your life be exactly what people expected of you', 'optionB': 'something nobody saw coming', 'category': 'girls_night'},
    {'optionA': 'have the strength to always walk away when you should', 'optionB': 'the courage to stay when everything felt impossible', 'category': 'girls_night'},
    {'optionA': 'choose the comfortable path and be at peace with it', 'optionB': 'the uncertain one and be at peace with it', 'category': 'girls_night'},
    {'optionA': 'be the version of yourself from before your hardest chapter', 'optionB': 'everything that version became', 'category': 'girls_night'},
    {'optionA': 'always look like you had it together', 'optionB': 'always actually have it together', 'category': 'girls_night'},
    {'optionA': 'be someone who made people better by knowing them', 'optionB': 'by something they left behind', 'category': 'girls_night'},
    {'optionA': 'your era of personal growth be your 20s', 'optionB': 'your 30s', 'category': 'girls_night'},
    {'optionA': 'be someone who was ahead of their time', 'optionB': 'someone who arrived at exactly the right moment', 'category': 'girls_night'},
    {'optionA': 'be in a relationship that asked more of you', 'optionB': 'one that expected nothing and gave everything', 'category': 'girls_night'},
    {'optionA': 'always know when someone genuinely meant what they said', 'optionB': 'always be able to tell when they didn\'t', 'category': 'girls_night'},
    {'optionA': 'your life be described as beautiful', 'optionB': 'meaningful', 'category': 'girls_night'},
    {'optionA': 'be someone who found peace in the chaos', 'optionB': 'someone who built peace from scratch', 'category': 'girls_night'},
    {'optionA': 'your most important decision be one you made alone', 'optionB': 'one you made with someone beside you', 'category': 'girls_night'},
    {'optionA': 'your greatest quality be that people felt heard by you', 'optionB': 'that they felt challenged by you', 'category': 'girls_night'},
    {'optionA': 'have been someone\'s turning point', 'optionB': 'their constant', 'category': 'girls_night'},
    {'optionA': 'always say the right thing to the right person', 'optionB': 'always be there at the right time', 'category': 'girls_night'},
    {'optionA': 'your biggest chapter be written alone', 'optionB': 'with someone who made it better', 'category': 'girls_night'},
    {'optionA': 'be completely whole on your own', 'optionB': 'grow into wholeness with someone else', 'category': 'girls_night'},
    {'optionA': 'be remembered for your resilience', 'optionB': 'your softness', 'category': 'girls_night'},
    {'optionA': 'have a life full of moments that no one else understood', 'optionB': 'moments that everyone felt with you', 'category': 'girls_night'},
    {'optionA': 'always be someone\'s first call', 'optionB': 'always be someone\'s safest place', 'category': 'girls_night'},
    {'optionA': 'carry your hardest lessons loudly', 'optionB': 'quietly into who you became', 'category': 'girls_night'},
    {'optionA': 'the most important thing people knew about you be how you loved', 'optionB': 'how you lived', 'category': 'girls_night'},
    {'optionA': 'be the best athlete of your generation with no recognition', 'optionB': 'the most recognized player with average ability', 'category': 'guys_unleashed'},
    {'optionA': 'always win but never be respected', 'optionB': 'always lose but be universally respected', 'category': 'guys_unleashed'},
    {'optionA': 'be the most loyal mate in your group', 'optionB': 'the one everyone called in a crisis', 'category': 'guys_unleashed'},
    {'optionA': 'be the strongest person you know', 'optionB': 'the fastest', 'category': 'guys_unleashed'},
    {'optionA': 'have unwavering confidence with no skill', 'optionB': 'incredible skill with crippling self-doubt', 'category': 'guys_unleashed'},
    {'optionA': 'be the funniest person in your group', 'optionB': 'the most respected', 'category': 'guys_unleashed'},
    {'optionA': 'always tell the truth to your mates even when it hurt', 'optionB': 'protect them from things they might not want to hear', 'category': 'guys_unleashed'},
    {'optionA': 'be known for what you built', 'optionB': 'what you overcame', 'category': 'guys_unleashed'},
    {'optionA': 'have a best mate who was brutally honest about everything', 'optionB': 'one who had your back no matter what', 'category': 'guys_unleashed'},
    {'optionA': 'reach the top of your career at 25 and plateau', 'optionB': 'build slowly and hit your peak at 40', 'category': 'guys_unleashed'},
    {'optionA': 'be the kind of person who made hard things look easy', 'optionB': 'someone who made it clear how difficult it was and did it anyway', 'category': 'guys_unleashed'},
    {'optionA': 'always know what a mate was going through', 'optionB': 'always know how to help when they asked', 'category': 'guys_unleashed'},
    {'optionA': 'be the first in your group to take a risk', 'optionB': 'the one who watched others go first and made a better move', 'category': 'guys_unleashed'},
    {'optionA': 'have a circle of 10 good lads', 'optionB': '2 mates who knew everything about you', 'category': 'guys_unleashed'},
    {'optionA': 'succeed at something you chose for yourself', 'optionB': 'something someone else always believed you could', 'category': 'guys_unleashed'},
    {'optionA': 'be completely driven with no balance', 'optionB': 'very balanced with slightly less ambition', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who was remembered for something they said', 'optionB': 'something they did', 'category': 'guys_unleashed'},
    {'optionA': 'have the respect of everyone you worked with', 'optionB': 'the loyalty of everyone you were close to', 'category': 'guys_unleashed'},
    {'optionA': 'be the most competitive person you knew and manage it well', 'optionB': 'have no competitive drive and be completely at peace', 'category': 'guys_unleashed'},
    {'optionA': 'make a decision under pressure that was wrong but decisive', 'optionB': 'a perfect decision that came too late', 'category': 'guys_unleashed'},
    {'optionA': 'be the first in your group to settle down', 'optionB': 'the last to and make it count', 'category': 'guys_unleashed'},
    {'optionA': 'have a career that gave you complete freedom', 'optionB': 'one that gave you complete security', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who made things happen', 'optionB': 'someone who made the most of what happened', 'category': 'guys_unleashed'},
    {'optionA': 'have a mate who called you out when you were wrong', 'optionB': 'one who let you figure it out yourself', 'category': 'guys_unleashed'},
    {'optionA': 'be the person who stayed calm in every situation', 'optionB': 'the one who felt everything intensely but handled it', 'category': 'guys_unleashed'},
    {'optionA': 'be the most physically capable you\'ve ever been at 25', 'optionB': 'the most mentally strong at 35', 'category': 'guys_unleashed'},
    {'optionA': 'have made every risk you took and failed', 'optionB': 'not taken a risk and never known', 'category': 'guys_unleashed'},
    {'optionA': 'be completely honest about how you felt and deal with the consequences', 'optionB': 'keep it private and carry it yourself', 'category': 'guys_unleashed'},
    {'optionA': 'be the mate who fixed things', 'optionB': 'the one who listened without trying to fix anything', 'category': 'guys_unleashed'},
    {'optionA': 'be in a long-term relationship that was genuinely great', 'optionB': 'have your freedom until you found the right person', 'category': 'guys_unleashed'},
    {'optionA': 'be the person who admitted when they were wrong early', 'optionB': 'realized later and changed quietly', 'category': 'guys_unleashed'},
    {'optionA': 'succeed publicly and never know if it was the right path', 'optionB': 'succeed privately on the exact right path', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who inspired others through what they achieved', 'optionB': 'through how they carried themselves', 'category': 'guys_unleashed'},
    {'optionA': 'be driven by something you feared losing', 'optionB': 'something you were working toward', 'category': 'guys_unleashed'},
    {'optionA': 'your greatest chapter be defined by competition', 'optionB': 'by building something with people you trusted', 'category': 'guys_unleashed'},
    {'optionA': 'always push through when things got hard', 'optionB': 'know exactly when to walk away', 'category': 'guys_unleashed'},
    {'optionA': 'be someone people underestimated and proved wrong', 'optionB': 'someone people expected everything of and delivered', 'category': 'guys_unleashed'},
    {'optionA': 'your most significant relationship begin with total certainty', 'optionB': 'grow into something you didn\'t see coming', 'category': 'guys_unleashed'},
    {'optionA': 'be a complete natural at the thing you loved', 'optionB': 'have to earn every inch of it', 'category': 'guys_unleashed'},
    {'optionA': 'be the mate who gave the best advice', 'optionB': 'the one who asked the best questions', 'category': 'guys_unleashed'},
    {'optionA': 'be known for your consistency', 'optionB': 'your ability to step up in a big moment', 'category': 'guys_unleashed'},
    {'optionA': 'have the confidence to ask for what you wanted in every area of your life', 'optionB': 'the patience to earn it', 'category': 'guys_unleashed'},
    {'optionA': 'your greatest moment be witnessed by everyone', 'optionB': 'experienced completely privately', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who carried others through hard periods', 'optionB': 'someone who carried only themselves and did it quietly well', 'category': 'guys_unleashed'},
    {'optionA': 'have had every difficult experience that made you who you are', 'optionB': 'gotten where you are more easily', 'category': 'guys_unleashed'},
    {'optionA': 'be the leader in a group because people trusted you', 'optionB': 'because you were the best at what you did', 'category': 'guys_unleashed'},
    {'optionA': 'be the last person your friends expected to do something great', 'optionB': 'the first they would have predicted', 'category': 'guys_unleashed'},
    {'optionA': 'be the version of yourself that faced everything hard', 'optionB': 'the version that came out the other side', 'category': 'guys_unleashed'},
    {'optionA': 'always have something to prove', 'optionB': 'be completely past needing to prove anything', 'category': 'guys_unleashed'},
    {'optionA': 'your best chapter be built alone', 'optionB': 'with the right people around you', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who moved fast and adjusted along the way', 'optionB': 'someone who took time and got it right first', 'category': 'guys_unleashed'},
    {'optionA': 'be remembered for how you competed', 'optionB': 'for what you stood for when competition was over', 'category': 'guys_unleashed'},
    {'optionA': 'always be completely honest about what you needed', 'optionB': 'figure it out yourself before asking anyone', 'category': 'guys_unleashed'},
    {'optionA': 'have the loyalty of someone who knew everything about you', 'optionB': 'the belief of someone who saw exactly what you were capable of', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who achieved exactly what he set out to do', 'optionB': 'exceeded what he thought was possible', 'category': 'guys_unleashed'},
    {'optionA': 'be the person who never let the group down', 'optionB': 'the person the group became better because of', 'category': 'guys_unleashed'},
    {'optionA': 'know a friendship that was built over years of trust', 'optionB': 'one that was forged in a single difficult moment', 'category': 'guys_unleashed'},
    {'optionA': 'be the mate who turned up without being asked', 'optionB': 'the one who asked exactly the right question at the right time', 'category': 'guys_unleashed'},
    {'optionA': 'be completely self-made', 'optionB': 'have been shaped by someone who believed in you early', 'category': 'guys_unleashed'},
    {'optionA': 'have a standard for yourself that required you to keep raising it', 'optionB': 'one that gave you peace when you hit it', 'category': 'guys_unleashed'},
    {'optionA': 'be the most feared competitor in your space', 'optionB': 'the most respected', 'category': 'guys_unleashed'},
    {'optionA': 'have complete control over your outcomes', 'optionB': 'complete peace with the outcomes you couldn\'t control', 'category': 'guys_unleashed'},
    {'optionA': 'always perform best when it mattered most', 'optionB': 'perform consistently regardless of what was at stake', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who changed under pressure for the better', 'optionB': 'someone who didn\'t change because they were already solid', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who built himself from nothing', 'optionB': 'someone who took everything he was given and maximized it completely', 'category': 'guys_unleashed'},
    {'optionA': 'your greatest strength be your discipline', 'optionB': 'your adaptability', 'category': 'guys_unleashed'},
    {'optionA': 'be the kind of man other men respected quietly', 'optionB': 'one who was openly admired', 'category': 'guys_unleashed'},
    {'optionA': 'have made every sacrifice that made you successful', 'optionB': 'had it come without the cost', 'category': 'guys_unleashed'},
    {'optionA': 'be remembered for something you built', 'optionB': 'something you stood for when it was difficult to', 'category': 'guys_unleashed'},
    {'optionA': 'always act on instinct and be right more often than not', 'optionB': 'always overthink and occasionally land on something perfect', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who could hold space for others without losing himself', 'optionB': 'someone who protected himself and gave when he could', 'category': 'guys_unleashed'},
    {'optionA': 'be the most competitive version of yourself', 'optionB': 'the most at peace version', 'category': 'guys_unleashed'},
    {'optionA': 'your hardest period have happened earlier so you were stronger sooner', 'optionB': 'happened later when you were more ready', 'category': 'guys_unleashed'},
    {'optionA': 'be someone whose values never changed even when everything else did', 'optionB': 'someone who grew enough to outgrow some of what he once believed', 'category': 'guys_unleashed'},
    {'optionA': 'your work be known everywhere for a short time', 'optionB': 'known permanently among the people who mattered', 'category': 'guys_unleashed'},
    {'optionA': 'your life be defined by what you built', 'optionB': 'by who was in the room when you built it', 'category': 'guys_unleashed'},
    {'optionA': 'always run toward what was difficult', 'optionB': 'know exactly when to let something go and redirect', 'category': 'guys_unleashed'},
    {'optionA': 'be the type of man who could be counted on in silence', 'optionB': 'one who could fill a room when it needed it', 'category': 'guys_unleashed'},
    {'optionA': 'your ambition come from love of what you did', 'optionB': 'from knowing exactly why it mattered', 'category': 'guys_unleashed'},
    {'optionA': 'have a reputation for never backing down', 'optionB': 'for always making the right call even when it wasn\'t the expected one', 'category': 'guys_unleashed'},
    {'optionA': 'your legacy be something people talked about', 'optionB': 'something they felt when they were around it', 'category': 'guys_unleashed'},
    {'optionA': 'always put the team first and be recognised for it', 'optionB': 'put yourself first and deliver something great that helped everyone', 'category': 'guys_unleashed'},
    {'optionA': 'face everything alone and find out what you were made of', 'optionB': 'face it with the right people and find out what you were all made of', 'category': 'guys_unleashed'},
    {'optionA': 'have arrived at who you are with less pain', 'optionB': 'more slowly', 'category': 'guys_unleashed'},
    {'optionA': 'your greatest strength be something you were born with', 'optionB': 'something you built over years', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who said the right thing at the right moment', 'optionB': 'who did the right thing when no one was watching', 'category': 'guys_unleashed'},
    {'optionA': 'always be completely clear on your purpose', 'optionB': 'always moving toward something you hadn\'t fully defined yet', 'category': 'guys_unleashed'},
    {'optionA': 'be known for never giving in', 'optionB': 'for always knowing when to adapt', 'category': 'guys_unleashed'},
    {'optionA': 'achieve something alone you\'d dreamed of since young', 'optionB': 'build something with others greater than any of you could have imagined', 'category': 'guys_unleashed'},
    {'optionA': 'your most meaningful relationship be the one that was hardest', 'optionB': 'the one that required the least effort', 'category': 'guys_unleashed'},
    {'optionA': 'be completely fearless', 'optionB': 'completely certain', 'category': 'guys_unleashed'},
    {'optionA': 'your story be one of comeback', 'optionB': 'one of consistency', 'category': 'guys_unleashed'},
    {'optionA': 'be the kind of man who inspired once and changed a life', 'optionB': 'someone who showed up every day and changed the direction of everything around him', 'category': 'guys_unleashed'},
    {'optionA': 'be someone who was shaped by his wins', 'optionB': 'someone who was shaped by what he lost', 'category': 'guys_unleashed'},
    {'optionA': 'have a reputation built quietly over time', 'optionB': 'one that arrived from one defining moment', 'category': 'guys_unleashed'},
    {'optionA': 'be the person who stayed when it was hard', 'optionB': 'the one who came back when it was right', 'category': 'guys_unleashed'},
    {'optionA': 'your best years already happened and you knew it', 'optionB': 'be in them right now without knowing', 'category': 'guys_unleashed'},
    {'optionA': 'be known for your honesty', 'optionB': 'your loyalty', 'category': 'guys_unleashed'},
    {'optionA': 'have the kind of friendship that made you better at being you', 'optionB': 'the kind that made being you feel enough', 'category': 'guys_unleashed'},
    {'optionA': 'leave your mark on one person who needed it', 'optionB': 'leave a small mark on everyone you ever met', 'category': 'guys_unleashed'},
  ];
}
